// The audio lane's later features (quality of life after Phase 9): the Recording section of Settings, splitting and
// enhancing a recording, the storage list, the meeting prompt, snapping the screen, files dropped on a page, export,
// and the transcripts, speakers, recap, action items, and chapters. One owner, so parallel work never edits it.

export const audioMore = {
  settings: {
    title: 'Recording',
    intro: 'Choices for recording on this PC. Recordings stay in your notes, on this device.',
    microphone: 'Microphone',
    defaultMicrophone: 'The default microphone',
    systemAudio: 'Record the PC’s sound too',
    systemAudioHelp: 'For meetings: the other people’s voices come through the speakers.',
    quality: 'Compress saved recordings to',
    qualitySmaller: 'Smaller: about half the size',
    qualitySmallest: 'Smallest: about a third of the size',
    qualityHelp: 'New recordings are always saved at full quality. This is what Compress uses later.',
    meeting: 'Offer to record when another app uses the microphone',
    meetingHelp:
      'OpenNote sees which app is using the microphone, never what is said. It never records on its own: it only asks.',
    storage: 'Manage recordings',
    storageHelp: 'See how much space each recording takes, compress it, or remove its audio.',
  },
  commands: {
    keywords:
      'audio recording enhance noise voice split storage space compress export save wav screenshot snap meeting',
    split: 'Split the recording here',
    enhance: 'Enhance the voice of the recording',
    storage: 'Manage recordings and the space they take',
    snapScreen: 'Snap the screen onto the page',
    snapWindow: 'Snap the window behind OpenNote onto the page',
    snapRegion: 'Snap a part of the screen onto the page',
    exportWav: 'Save the recording as a WAV file',
    exportOpus: 'Save the recording as an Opus file',
  },
  menu: {
    split: 'Split here ({time})',
    enhance: 'Enhance voice',
    removeEnhanced: 'Remove the enhanced copy',
    exportWav: 'Save as WAV…',
    exportOpus: 'Save as Opus…',
    transcribe: 'Make a transcript',
    importTranscript: 'Add a transcript from text…',
    fromOriginal: 'Make transcripts from the original voice',
    fromEnhanced: 'Make transcripts from the enhanced voice',
  },
  split: {
    done: 'Split into {first} and {second}.',
    tooEarly: 'Move to a moment inside the recording first.',
  },
  remove: {
    alsoPurges:
      'The words spoken in it also leave the transcript, and this page’s saved versions are deleted so the part can’t be brought back.',
  },
  enhance: {
    working: 'Enhancing the voice. Long recordings take a few minutes.',
    done: 'The enhanced copy is ready. The original is kept.',
    removed: 'The enhanced copy was removed. The original is untouched.',
    switch: 'Listen to the enhanced voice',
    switchHelp: 'The original is kept. Turn this off to compare.',
    removeTitle: 'Remove the enhanced copy?',
    removeBody: 'The original recording stays.',
    removeAction: 'Remove copy',
    cancel: 'Cancel',
  },
  storage: {
    title: 'Recordings and the space they take',
    description: 'Nothing is changed until you choose, and each choice says how much space it frees.',
    loading: 'Looking through your notebooks…',
    none: 'No recordings yet.',
    failed: 'The recordings couldn’t be listed.',
    row: '{length} · {size}',
    where: '{notebook} › {section}',
    removedRow: 'Audio removed',
    compress: 'Compress',
    compressLabel: 'Compress the recording on {page}',
    compressTitle: 'Compress this recording?',
    compressBody:
      'It becomes {quality} and frees about {size}. Notes, flags, and times stay. Any enhanced copy is removed.',
    compressAction: 'Compress',
    qualitySmaller: 'about half the size',
    qualitySmallest: 'about a third of the size',
    compressed: 'Compressed. {size} freed.',
    removeAudio: 'Remove audio',
    removeLabel: 'Remove the audio of the recording on {page}',
    removeTitle: 'Remove the audio?',
    removeBody: 'This frees {size}. The transcript, flags, and notes stay, but the recording can’t be played again.',
    removeAction: 'Remove audio',
    audioRemoved: 'Audio removed. {size} freed.',
    removedNote: 'The audio was removed to save space. The transcript and flags are kept.',
    total: 'Together they take {size}.',
    close: 'Close',
    cancel: 'Cancel',
    untitled: 'Untitled page',
  },
  meeting: {
    title: 'A meeting may have started',
    body: '{app} is using your microphone.',
    record: 'Record this meeting',
    notNow: 'Not now',
    never: 'Never for this app',
    neverDone: 'OpenNote won’t offer to record when {app} uses the microphone.',
    needsPage: 'Open a page first, then record.',
  },
  snap: {
    working: 'Snapping…',
    done: 'Snap added at {time}.',
    needsRecording: 'Start recording first, then snap the screen.',
    failed: 'The screen couldn’t be snapped: {message}',
    alt: 'Screen snap at {time}',
    regionTitle: 'Choose the part to keep',
    regionHelp: 'Drag over the picture. Choose Keep the whole picture to use all of it.',
    regionImage: 'The screen. Drag to choose a part.',
    regionUse: 'Keep the part',
    regionAll: 'Keep the whole picture',
    cancel: 'Cancel',
  },
  export: {
    name: 'Recording {date}',
    wavLabel: 'WAV audio',
    opusLabel: 'Opus audio',
    working: 'Saving the recording…',
    done: 'Saved the recording. It is {size}.',
    failed: 'The recording couldn’t be saved: {message}',
    enhancedNote: 'The enhanced voice is saved when it is the one you listen to.',
  },
  files: {
    working: 'Adding {name}…',
    done: 'Added {name} as a recording of {length}.',
    failed: 'Windows couldn’t read the sound in {name}.',
    unsupported: 'Only audio and video files can be added as recordings.',
    needsApp: 'Adding audio files needs the OpenNote app.',
    tooBig: '{name} is longer than four hours, which is the most that can be added.',
    rights: 'Only add files you have the right to use.',
  },
  transcript: {
    commands: {
      make: 'Make a transcript of the recording',
      add: 'Add a transcript from text or captions',
      actions: 'Find action items in the transcript',
      chapters: 'Make chapters from the transcript',
      recap: 'Copy the meeting recap',
      quote: 'Copy the selected transcript lines into the notes',
      keywords: 'transcript speech words captions meeting recap summary action items chapters quote',
    },
    label: 'Transcript, {count, plural, one {# line} other {# lines}}',
    heading: 'Transcript',
    summary: 'Summary',
    noSummary: 'No summary yet.',
    makeSummary: 'Make a summary',
    summarizing: 'Writing a summary…',
    noLines: 'The transcript is empty.',
    speaker: 'Speaker {n}',
    play: 'Play from {time}',
    selectLine: 'Select the line at {time}',
    edit: 'Edit',
    doneEditing: 'Done',
    lineText: 'Words at {time}',
    lineSpeaker: 'Speaker at {time}',
    nobody: 'No speaker',
    newSpeaker: 'A new speaker',
    speakers: 'Speakers',
    rename: 'Rename {name}',
    renameTitle: 'Rename {name}',
    renameBody: 'The new name shows on every line this speaker has.',
    renameLabel: 'Name',
    renameSave: 'Rename',
    renameCancel: 'Cancel',
    renameSuggestions: 'Names you used before',
    renamed: 'Renamed to {name}.',
    copyToNotes: 'Copy to notes',
    selected: '{count, plural, =0 {No lines selected} one {# line selected} other {# lines selected}}',
    includeSpeaker: 'Include speaker names',
    inserted: 'Added {count, plural, one {# line} other {# lines}} to your notes.',
    copied: 'No note has the caret, so the lines were copied. Click in your notes and paste.',
    nothingSelected: 'Select some lines first.',
    findActions: 'Find action items',
    makeChapters: 'Make chapters',
    copyRecap: 'Copy recap',
    working: 'Reading the transcript…',
    needsSummaries: 'This needs on-device summaries, which are off.',
    suggestions: 'Suggestions',
    suggestionsHelp: 'Nothing is added until you choose it.',
    actionsHeading: 'Action items and decisions',
    noActions: 'No action items or decisions were found.',
    decision: 'Decision',
    task: 'Task',
    addAction: 'Add to page',
    addActionLabel: 'Add to the page: {text}',
    actionAdded: 'Added a checkbox to your notes.',
    dismiss: 'Dismiss suggestions',
    chaptersHeading: 'Chapters',
    noChapters: 'No chapters could be made.',
    chapterPart: 'Part {n}',
    chapterGo: 'Play {title} from {time}',
    keepChapters: 'Keep the chapters',
    chaptersKept: 'The chapters are kept with the transcript.',
    clearChapters: 'Remove chapters',
    due: 'due {date}',
    engineNone: 'Speech transcription isn’t on this PC yet. You can add a transcript from text or captions instead.',
    engineWorking: 'Making the transcript. Long recordings take a few minutes.',
    engineDone: 'The transcript is ready.',
    engineFailed: 'The transcript couldn’t be made: {message}',
    transcribeFrom: 'Make it from',
    fromOriginal: 'The original voice',
    fromEnhanced: 'The enhanced voice',
    rights: 'Only make transcripts of audio you have the right to use.',
    addTitle: 'Add a transcript',
    addBody:
      'Paste captions, lines that start with a time like [12:05], or plain text. Plain text is spread by length.',
    addLabel: 'Transcript text',
    addSave: 'Add transcript',
    addCancel: 'Cancel',
    addEmpty: 'There is nothing to add.',
    added: 'Added a transcript of {count, plural, one {# line} other {# lines}}.',
    addedSpread: 'The text had no times, so it was spread over the recording by length.',
    recapTitle: 'Copy the meeting recap',
    recapBody: 'Choose what to copy. Nothing is sent anywhere.',
    recapSummary: 'Summary',
    recapDecisions: 'Decisions',
    recapActions: 'Action items',
    recapFormat: 'Copy as',
    recapFormatted: 'Formatted text',
    recapMarkdown: 'Markdown',
    recapPreview: 'Preview',
    recapCopy: 'Copy recap',
    recapCancel: 'Cancel',
    recapCopied: 'Copied the recap.',
    recapEmpty: 'Nothing is selected to copy.',
    recapFromPage: 'No transcript is available, so this is the page’s own headings and checkboxes.',
    recapNothing: 'This page has no summary, headings, or checkboxes to copy.',
    noTranscript: 'This page has no transcript. Make one from the recording’s More menu.',
    noRecording: 'This page has no recording.',
    momentGone: 'The recording for that moment isn’t on this page.',
  },
} as const;
