// Audio recording and playback (Phase 9; owner: the audio lane).
// Each namespace file has one owner, so parallel work never edits the same file.

export const audio = {
  commands: {
    record: 'Start recording',
    stop: 'Stop recording',
    pause: 'Pause recording',
    resume: 'Resume recording',
    options: 'Recording options',
    play: 'Play or pause the recording',
    playFromCaret: 'Play the recording from the caret',
    playFromInk: 'Play the recording from the selected ink',
    skipBack: 'Skip back 10 seconds',
    skipForward: 'Skip forward 10 seconds',
    flag: 'Flag this moment',
    nextFlag: 'Go to the next flag',
    previousFlag: 'Go to the previous flag',
    trimSilence: 'Trim silence from the recording',
    keywords: 'audio record recording microphone voice meeting lecture listen',
  },
  bar: {
    group: 'Recording',
    record: 'Record',
    stop: 'Stop',
    pause: 'Pause',
    resume: 'Resume',
    flag: 'Flag',
    options: 'Options',
  },
  indicator: {
    recording: 'Recording {time}',
    paused: 'Paused {time}',
    label: '{state}. Open the recording controls.',
    title: 'Recording controls',
    meter: 'Microphone level',
    systemMeter: 'PC sound level',
    goToPage: 'Go to the page',
  },
  options: {
    title: 'Recording options',
    microphone: 'Microphone',
    defaultMicrophone: 'Default microphone',
    systemAudio: 'Also record sound from this PC',
    systemAudioHint: 'For meetings: records what plays through your speakers or headset.',
    consent: 'Tell everyone before you record a meeting.',
    noDevices: 'No microphone was found. Plug one in, then open this again.',
    refresh: 'Look again',
  },
  announce: {
    started: 'Recording started.',
    stopped: 'Recording stopped. {time} saved.',
    paused: 'Recording paused.',
    resumed: 'Recording resumed.',
    flagged: 'Flag added at {time}.',
    recovered: 'Recovered {time} of a recording that stopped unexpectedly.',
    trimmed: 'Trimmed. The recording is now {time} long.',
    nothingToTrim: 'There is no silence worth trimming.',
    noFlag: 'There is no flag that way.',
    playingFrom: 'Playing from {time}.',
    nothingStamped: 'Nothing here was written while recording.',
    switched: 'Now recording from {device}.',
  },
  block: {
    label: 'Recording, {time}',
    labelWhile: 'Recording in progress',
    title: 'Recording from {date}',
    fallback: 'Audio recording',
    play: 'Play',
    pause: 'Pause',
    position: 'Position in the recording',
    positionText: '{position} of {total}',
    speed: 'Speed',
    speedValue: '{speed}×',
    skipBack: 'Back 10 seconds',
    skipForward: 'Forward 10 seconds',
    skipSilence: 'Skip silence',
    flag: 'Flag this moment',
    flags: 'Flags',
    flagLabel: 'Flag at {time}',
    flagGo: 'Go to flag at {time}',
    flagRemove: 'Remove flag at {time}',
    more: 'More',
    trimSilence: 'Trim silence at the start and end',
    removeFromHere: 'Remove from here to the end of the listened part',
    removePart: 'Remove a part',
    removeStart: 'Part starts at {time}',
    removeEnd: 'Part ends at {time}',
    removeConfirm: 'Remove this part?',
    removeBody:
      'The audio from {from} to {to} is deleted from the recording. Your notes keep their timing. This can’t be undone.',
    removeAction: 'Remove part',
    markStart: 'Start a part to remove here ({time})',
    markEnd: 'Mark where the part ends',
    cancel: 'Cancel',
    recovered: 'Recovered after the app stopped unexpectedly. {time} of audio was saved.',
    missing: 'The audio for this recording can’t be found on this PC.',
    failed: 'This recording can’t play: {message}',
    live: 'Recording…',
    recovering: 'Recovering this recording…',
    elsewhere: 'This recording is in use in another window. It shows here when that window has saved it.',
    notRecovered: 'This recording couldn’t be recovered yet. It’s tried again the next time this page opens.',
    damaged: 'This recording’s file is damaged, so it can’t be recovered. The file stays in this page’s folder.',
    liveHint: 'What you write while recording is time-stamped. Later, Alt+click a word to hear when you wrote it.',
    gutterPlay: 'Play from {time}',
    unavailable: 'Recording isn’t available in this window.',
  },
  warnings: {
    microphoneSilent: 'The microphone has been silent for {seconds} seconds.',
    deviceStalled: 'The audio device stopped sending sound.',
    lowDisk: 'Disk space is low: about {minutes} minutes of recording left.',
    lowBattery: 'The battery is low: {percent}%.',
    writerFailed: 'The recording file can’t be written: {message}',
    droppedAudio: 'Some sound was lost.',
    deviceLost: 'The microphone was unplugged.',
    notDefaultDevice: 'The PC now plays sound somewhere else.',
    followOutput: 'Record the new output',
  },
  stopped: {
    diskFull: 'The disk is full, so recording stopped. {time} was saved.',
    writerFailed: 'Recording stopped because the file couldn’t be written. {time} was saved.',
    ok: 'Recording stopped. {time} was saved.',
  },
  errors: {
    start: 'Recording couldn’t start: {message}',
    audioDevice:
      'The microphone couldn’t be opened. Check that it is plugged in and that Windows lets OpenNote use it.',
    audioEncoder: 'This build can’t encode audio.',
    audioFormat: 'The audio device uses a format OpenNote can’t record.',
    audioCorrupt: 'The recording file is damaged.',
    audioMissing: 'The recording file can’t be found.',
    audioWriter: 'The recording file can’t be written.',
    io: 'The recording file can’t be read or written.',
    unknown: 'Something went wrong with the recording.',
    noPage: 'Open a page first, then start recording.',
    busy: 'A recording is already running.',
  },
} as const;
