// The audio lane's later features (quality of life after Phase 9): the Recording section of Settings, splitting and
// enhancing a recording, the storage list, the meeting prompt, snapping the screen, files dropped on a page, export,
// and the transcripts, speakers, recap, action items and chapters. One owner, so parallel work never edits it.

export const audioMore = {
  settings: {
    title: 'Recording',
    intro: 'Choices for recording on this PC. Recordings stay in your notes, on this device.',
    microphone: 'Microphone',
    defaultMicrophone: 'The default microphone',
    systemAudio: 'Record the PC’s sound too',
    systemAudioHelp: 'For meetings: the other people’s voices come through the speakers.',
    quality: 'Compress saved recordings to',
    qualitySmaller: 'Smaller: about half the size',
    qualitySmallest: 'Smallest: about a third of the size',
    qualityHelp: 'New recordings are always saved at full quality. This is what Compress uses later.',
    meeting: 'Offer to record when another app uses the microphone',
    meetingHelp:
      'OpenNote sees which app is using the microphone, never what is said. It never records on its own: it only asks.',
    storage: 'Manage recordings',
    storageHelp: 'See how much space each recording takes, compress it, or remove its audio.',
  },
  commands: {
    keywords:
      'audio recording enhance noise voice split storage space compress export save wav screenshot snap meeting',
    split: 'Split the recording here',
    enhance: 'Enhance the voice of the recording',
    storage: 'Manage recordings and the space they take',
    snapScreen: 'Snap the screen onto the page',
    snapWindow: 'Snap the window behind OpenNote onto the page',
    snapRegion: 'Snap a part of the screen onto the page',
    exportWav: 'Save the recording as a WAV file',
    exportOpus: 'Save the recording as an Opus file',
  },
  menu: {
    split: 'Split here ({time})',
    enhance: 'Enhance voice',
    removeEnhanced: 'Remove the enhanced copy',
    exportWav: 'Save as WAV…',
    exportOpus: 'Save as Opus…',
    transcribe: 'Make a transcript',
  },
  split: {
    done: 'Split into {first} and {second}.',
    tooEarly: 'Move to a moment inside the recording first.',
  },
  remove: {
    alsoPurges:
      'The words spoken in it also leave the transcript, and this page’s saved versions are deleted so the part can’t be brought back.',
  },
  enhance: {
    working: 'Enhancing the voice. Long recordings take a few minutes.',
    done: 'The enhanced copy is ready. The original is kept.',
    removed: 'The enhanced copy was removed. The original is untouched.',
    switch: 'Listen to the enhanced voice',
    switchHelp: 'The original is kept. Turn this off to compare.',
    removeTitle: 'Remove the enhanced copy?',
    removeBody: 'The original recording stays.',
    removeAction: 'Remove copy',
    cancel: 'Cancel',
  },
  storage: {
    title: 'Recordings and the space they take',
    description: 'Nothing is changed until you choose, and each choice says how much space it frees.',
    loading: 'Looking through your notebooks…',
    none: 'No recordings yet.',
    failed: 'The recordings couldn’t be listed.',
    row: '{length} · {size}',
    where: '{notebook} › {section}',
    removedRow: 'Audio removed',
    compress: 'Compress',
    compressLabel: 'Compress the recording on {page}',
    compressTitle: 'Compress this recording?',
    compressBody:
      'The recording becomes {quality} and frees about {size}. Notes, flags and times stay. An enhanced copy, if there is one, is removed.',
    compressAction: 'Compress',
    qualitySmaller: 'about half the size',
    qualitySmallest: 'about a third of the size',
    compressed: 'Compressed. {size} freed.',
    removeAudio: 'Remove audio',
    removeLabel: 'Remove the audio of the recording on {page}',
    removeTitle: 'Remove the audio?',
    removeBody: 'This frees {size}. The transcript, flags and notes stay, but the recording can’t be played again.',
    removeAction: 'Remove audio',
    audioRemoved: 'Audio removed. {size} freed.',
    removedNote: 'The audio was removed to save space. The transcript and flags are kept.',
    total: 'Together they take {size}.',
    close: 'Close',
    cancel: 'Cancel',
    untitled: 'Untitled page',
  },
  meeting: {
    title: 'A meeting may have started',
    body: '{app} is using your microphone.',
    record: 'Record this meeting',
    notNow: 'Not now',
    never: 'Never for this app',
    neverDone: 'OpenNote won’t offer to record when {app} uses the microphone.',
    needsPage: 'Open a page first, then record.',
  },
  snap: {
    working: 'Snapping…',
    done: 'Snap added at {time}.',
    needsRecording: 'Start recording first, then snap the screen.',
    failed: 'The screen couldn’t be snapped: {message}',
    alt: 'Screen snap at {time}',
    regionTitle: 'Choose the part to keep',
    regionHelp: 'Drag over the picture. Choose Keep the whole picture to use all of it.',
    regionImage: 'The screen. Drag to choose a part.',
    regionUse: 'Keep the part',
    regionAll: 'Keep the whole picture',
    cancel: 'Cancel',
  },
  export: {
    name: 'Recording {date}',
    wavLabel: 'WAV audio',
    opusLabel: 'Opus audio',
    working: 'Saving the recording…',
    done: 'Saved the recording. It is {size}.',
    failed: 'The recording couldn’t be saved: {message}',
    enhancedNote: 'The enhanced voice is saved when it is the one you listen to.',
  },
  files: {
    working: 'Adding {name}…',
    done: 'Added {name} as a recording of {length}.',
    failed: 'Windows couldn’t read the sound in {name}.',
    unsupported: 'Only audio and video files can be added as recordings.',
    needsApp: 'Adding audio files needs the OpenNote app.',
    tooBig: '{name} is longer than four hours, which is the most that can be added.',
    rights: 'Only add files you have the right to use.',
  },
} as const;
