// The Connectors section of Settings: the list of accounts OpenNote can sign in to, what each one lets OpenNote do,
// and the messages for a sign-in that did not finish. Every interface string is a full sentence here, never joined
// from pieces (ARCHITECTURE.md section 19). Each ID under `service`, `feature`, and `access` matches an ID in the
// connector registry (app/src-tauri/src/connectors/registry.rs), and a test there keeps the two in step.

export const connectors = {
  section: 'Connectors',
  intro: 'Connect an account so a feature can use that service. Everything here is off until you connect it.',
  introMore: "You sign in on the service's own page, and you can disconnect at any time.",
  searchLabel: 'Search connectors',
  noMatches: 'No connectors match that search.',
  resultCount: '{count, plural, one {# connector matches.} other {# connectors match.}}',
  offlineNotice: 'Work offline is on, so signing in and renewing wait until you go back online.',
  groups: {
    microsoft: 'Microsoft',
    google: 'Google',
    storage: 'Storage',
    learning: 'Learning platforms',
    other: 'Other',
  },
  state: {
    notConnected: 'Not connected',
    connected: 'Connected as {account}',
    connectedNoName: 'Connected',
    needsSetup: 'Needs setup',
    expired: 'Sign-in expired',
    waiting: 'Waiting for you to finish signing in, in your browser',
    connectedOn: 'Connected on {date}',
  },
  actions: {
    connect: 'Connect',
    disconnect: 'Disconnect',
    reconnect: 'Reconnect',
    cancel: 'Cancel sign-in',
    save: 'Connect with this token',
    setup: 'Show setup steps',
    openFolder: 'Open the connectors folder',
    addClient: 'Add a client ID',
    saveClient: 'Save client ID',
    details: 'What this allows',
  },
  detail: {
    unlocksHeading: 'Features that use this account',
    accessHeading: 'What OpenNote will be able to do',
    readOnly: 'Read only',
    canChange: 'Can change data',
    hostsHeading: 'Where OpenNote connects',
    hosts: 'OpenNote talks only to {hosts} for this connector.',
    noHostsYet: "OpenNote talks only to your school's server, once you give its address.",
    lastUsed: 'Last used {date}',
    neverUsed: 'Not used yet',
    setupHelp: 'OpenNote has no client ID for {name} yet. The setup steps say how to add one.',
    tokenLabel: 'Personal token',
    tokenHelp: 'Paste the token from your account. OpenNote keeps it in Windows Credential Manager, never in a file.',
    clientIdLabel: 'Client ID',
    clientIdHelp: 'From the app you registered with the service. A client ID is not a secret.',
    clientSecretLabel: 'Client secret (only if the service gave you one)',
    clientSecretHelp: 'OpenNote keeps it on this device only, in the connectors file.',
    webdavAddressLabel: 'Server address',
    webdavAddressHelp:
      'The folder address, such as cloud.example.org/remote.php/dav/files/sam. It must start with https.',
    webdavTokenLabel: 'User name and password',
    webdavTokenHelp:
      'Type them as name:password. Use an app password if the server offers one. OpenNote keeps them in Windows Credential Manager.',
    addressLabel: 'School address',
    addressHelp: "The address you use to sign in to your school's site, such as school.instructure.com.",
  },
  service: {
    microsoft: {
      unlocks:
        'Import notebooks from OneNote, open meeting notes from Outlook events, sync Microsoft To Do, send pages to OneDrive, and share to Teams.',
    },
    google: {
      unlocks:
        'Meeting notes from Calendar events, Google Tasks, Classroom assignments, Drive, Docs, Sheets, and Slides, YouTube captions, and uploading a recording video to YouTube.',
    },
    slack: { unlocks: 'Share a page to a Slack channel.' },
    dropbox: { unlocks: 'Sync folders with Dropbox and send pages to it.' },
    box: { unlocks: 'Sync folders with Box and send pages to it.' },
    vimeo: { unlocks: 'Use the captions of your Vimeo videos as transcripts.' },
    readwise: { unlocks: 'Bring your book highlights from Readwise into a notebook.' },
    canvas: { unlocks: "Bring assignments from your school's Canvas into a section." },
    moodle: { unlocks: "Bring assignments from your school's Moodle into a section." },
    webdav: { unlocks: 'Send pages to a folder on a WebDAV server, such as Nextcloud.' },
  },
  feature: {
    importOneNote: 'Import from OneNote',
    outlookCalendar: 'Meeting notes from Outlook events',
    microsoftToDo: 'Microsoft To Do',
    googleCalendar: 'Meeting notes from Google Calendar events',
    googleTasks: 'Google Tasks',
    googleClassroom: 'Google Classroom assignments',
    googleDrive: 'Send to Google Drive',
    youtubeCaptions: 'YouTube captions',
    syncDropbox: 'Sync with Dropbox',
    sendToDropbox: 'Send to Dropbox',
    syncBox: 'Sync with Box',
    sendToBox: 'Send to Box',
    shareToSlack: 'Share to Slack',
    vimeoCaptions: 'Vimeo captions',
    readwiseHighlights: 'Readwise highlights',
    canvasAssignments: 'Canvas assignments',
    moodleAssignments: 'Moodle assignments',
    shareToTeams: 'Share to Teams',
    sendToOneDrive: 'Send to OneDrive',
    googleOffice: 'Google Docs, Sheets, and Slides',
    youtubeUpload: 'Upload a recording video to YouTube',
    sendToWebdav: 'Send to a WebDAV server',
  },
  access: {
    account: 'See your account name and email address.',
    stayConnected: 'Stay signed in without asking you again.',
    onenoteRead: 'Read your OneNote notebooks. It cannot change them.',
    calendarRead: 'Read your calendar events. It cannot change them.',
    tasksWrite: 'Read and change your tasks.',
    classroomRead: 'Read your Classroom courses and your own assignments.',
    driveFiles: 'Create files in your Drive, and change only the files OpenNote created.',
    youtubeRead: 'See your YouTube videos and their captions.',
    dropboxAccount: 'See your Dropbox account name.',
    dropboxRead: 'Read the files in your Dropbox.',
    dropboxWrite: 'Add and change files in your Dropbox.',
    boxFiles: 'Read and change the files in your Box.',
    slackPost: 'Post messages as you.',
    slackFiles: 'Upload files as you.',
    slackChannels: 'See the list of your channels.',
    vimeoRead: 'Read your Vimeo videos and their captions.',
    readwiseRead: 'Read your Readwise highlights.',
    canvasRead: 'Read your courses and assignments.',
    moodleRead: 'Read your courses and assignments.',
    onedriveFiles: 'Read and change the files in your OneDrive.',
    teamsPost: 'Post messages to the Teams channels you choose.',
    teamsRead: 'See the teams and channels you belong to.',
    driveRead: 'Read your Google Docs, Sheets, and Slides so OpenNote can import them. It cannot change them.',
    youtubeUpload: 'Upload videos to your YouTube channel.',
    youtubeCaptions: 'Read the captions of your YouTube videos.',
    classroomSubmit: 'Attach a file to your own Classroom assignment and turn it in.',
    webdavFiles: 'Read and change the files in the WebDAV folder you connect.',
  },
  confirm: {
    title: 'Disconnect {name}?',
    body: 'OpenNote forgets the sign-in on this computer. Features that use {name} stop until you connect again.',
    confirm: 'Disconnect',
  },
  announce: {
    connected: 'Connected to {name}.',
    connectedAs: 'Connected to {name} as {account}.',
    waiting: 'Opened {name} in your browser. Finish signing in there.',
    disconnected: 'Disconnected from {name}.',
    clientSaved: 'Saved the client ID for {name}. You can connect now.',
    clientRefused: 'That client ID can’t be used. It has no spaces and is not empty.',
    canceled: 'Sign-in canceled.',
  },
  revoke: {
    revoked: 'Disconnected from {name}. The service no longer lets OpenNote in.',
    notSupported: '{name} is disconnected here. To end the sign-in there too, remove OpenNote in your {name} account.',
    skippedOffline:
      'Disconnected here. Work offline was on, so {name} was not told. Remove OpenNote in your {name} account.',
    failed: 'Disconnected here. OpenNote could not reach {name}, so remove OpenNote in your {name} account.',
  },
  error: {
    offline: 'Work offline is on. Turn it off in Privacy settings, then try again.',
    unknown: 'Something went wrong, and nothing was changed. Try again.',
    notConfigured: 'This copy of OpenNote has no client ID for {name} yet. The setup steps say how to add one.',
    notConnected: '{name} is not connected.',
    expired: 'The {name} sign-in no longer works. Choose Reconnect to sign in again.',
    missingAccess: 'The {name} connection does not include the access this needs. Choose Reconnect and allow it.',
    busy: 'A sign-in to {name} is already open in your browser.',
    canceled: 'The sign-in was canceled.',
    timedOut: 'The sign-in to {name} was not finished in 5 minutes, so it was closed. Choose Connect to try again.',
    denied: 'You did not allow access, so {name} is not connected.',
    mismatch: "The browser's answer did not match this sign-in, so OpenNote ignored it. Choose Connect to start again.",
    portInUse: 'Another program is using the port {name} needs. Close it, or set another port in the connectors file.',
    browserFailed: 'OpenNote could not open your browser. Check your default browser in Windows settings.',
    network: 'OpenNote could not reach {name}. Check your connection and try again.',
    rejected: '{name} did not accept the sign-in or the token. Check it and try again.',
    badInput: "Check the school address and the token. The address must start with https and name your school's site.",
    foreignHost: 'That address is not one OpenNote may connect to for {name}.',
    storage: 'OpenNote could not save the {name} connection in Windows Credential Manager.',
  },
  privacy: {
    heading: 'Connected accounts',
    detail: 'OpenNote contacts these servers only after you connect an account, and only when a feature needs it.',
    off: '{name} is not connected, so OpenNote makes no requests to it.',
    hostsLine: '{name} uses {hosts}.',
    lastUsed: 'Last used {date}.',
    neverUsed: 'Not used yet.',
    ready: 'Sign-in, renewing, and requests happen only while you are online.',
    blocked: 'Sign-in and requests are blocked while you work offline.',
  },
} as const;
