// The crash report consent screen, the saved crash reports, the self-check, and the beta feedback file.
// Every interface string is a full sentence here, never joined from pieces (ARCHITECTURE.md section 19).

export const diagnostics = {
  commands: {
    help: 'Check OpenNote',
    helpKeywords: 'help self-check health problems diagnose version disk space notebook',
    feedback: 'Send feedback',
    feedbackKeywords: 'bug report problem issue beta log support',
    privacy: 'Privacy settings',
    privacyKeywords: 'crash reports network offline privacy data',
    workOffline: 'Work offline',
    workOfflineKeywords: 'network offline online internet updates',
  },
  help: {
    section: 'Help',
    intro: 'Check that OpenNote and your notebook are in order, or send feedback to the people who build it.',
    versionHeading: 'This copy of OpenNote',
    version: 'Version {version}',
    channel:
      '{channel, select, beta {Beta channel} nightly {Nightly channel} dev {Development build} other {Stable channel}}',
    updates: 'Updates',
    updatesOpen: 'Open update settings',
    checkHeading: 'Self-check',
    checkIntro:
      'This looks at your notebook, disk space, and updates. It changes nothing, and nothing leaves your computer.',
    problemFiles: 'Problem files',
    feedbackHeading: 'Feedback',
    feedbackIntro: 'Make a file about a problem, read all of it, and save it. You send it yourself.',
    sessionsHeading: 'Recent sessions',
    checkFailed: "The check couldn't run. Try again.",
  },
  privacy: {
    section: 'Privacy',
    intro:
      'OpenNote works on your computer and sends nothing unless you ask it to. This page lists every kind of network use it has.',
    offlineHeading: 'Work offline',
    offlineLabel: 'Work offline',
    offlineHelp: 'Blocks everything listed below until you turn it back on. Your notes are not affected.',
    announceOffline: 'Working offline. OpenNote will not use the network.',
    announceOnline: 'OpenNote can use the network again.',
    offlineFailed: "Couldn't change this setting. Try again.",
    chip: 'Working offline',
    chipTitle: 'OpenNote is working offline',
    chipBody: 'It makes no network requests, so update checks and web images are paused. Your notes are not affected.',
    chipTurnOff: 'Go online',
    chipSettings: 'Open privacy settings',
    usesHeading: 'Network use',
    usesIntro: 'Each of these runs only for the reason given, and never while you work offline.',
    blocked: 'Blocked while you work offline.',
    neverRan: 'Has not run yet.',
    lastRan: 'Last ran {date} at {time}.',
    use: {
      updates: 'Update checks',
      updatesDetail:
        'OpenNote asks the update server whether a newer version exists, and downloads it when you allow it.',
      reports: 'Sending a crash report',
      reportsDetail: 'Only when you press Send on a report you have read, and only if an address is set.',
      reportsNoAddress: 'No address is set, so a report can only stay on this computer.',
      images: 'Saving a web image you paste',
      imagesDetail:
        'When you turn on Save images from web pastes, OpenNote downloads the pictures of a web page you paste ' +
        'to keep them in your page. It is off until you turn it on.',
      imagesNever: 'Runs only when you paste, never in the background.',
    },
    reportsHeading: 'Crash reports',
    reportsSwitch: 'Save crash reports on this computer',
    reportsHelp: 'Off until you turn it on. A report never holds your notes, and it is sent only if you choose.',
    reportsLearn: 'What a report holds',
    reportsEmptyOn: 'No crash reports are saved.',
    reviewFailed: "Couldn't read the report.",
    sessionsHeading: 'Sessions',
    toolsHeading: 'Help',
    checkButton: 'Check OpenNote',
    feedbackButton: 'Send feedback',
  },
  consent: {
    title: 'Save crash reports on this computer?',
    titleReworded: 'Crash reports have changed',
    intro:
      'If OpenNote stops working, it can save a short report that helps fix the cause. Nothing is saved unless you turn this on.',
    reworded:
      'What a crash report holds has changed, so OpenNote is asking again. Your earlier answer no longer applies.',
    holdsHeading: 'What a report holds',
    holdsWhere: 'Where in the program the crash happened',
    holdsVersions: 'The versions of OpenNote and Windows',
    holdsTime: 'When it happened',
    neverHeading: 'What a report never holds',
    neverNotes: 'Your notes, page titles, or anything you typed',
    neverFiles: 'File, folder, or notebook names',
    neverNames: 'Your name or your computer name',
    control: 'A report stays on this computer. You read each one first, and you choose each time whether to send it.',
    seeExample: 'See an example report',
    hideExample: 'Hide the example report',
    exampleLabel: 'An example report',
    turnOn: 'Turn on crash reports',
    keepOff: 'Keep crash reports off',
    changeLater: 'You can change this at any time in Settings, under Privacy.',
    announceOn: 'Crash reports are on. They stay on this computer.',
    announceOff: 'Crash reports are off.',
  },
  crashReports: {
    title: 'Crash reports',
    off: 'Crash reports are off. Turn them on in Settings, under Privacy.',
    empty: 'No crash reports are saved.',
    saved:
      '{count, plural, one {# crash report is saved on this computer.} other {# crash reports are saved on this computer.}}',
    item: '{kind, select, panic {Program error} exception {Crash} other {Problem}} on {date} at {time}, version {version}',
    review: 'Review',
    delete: 'Delete',
    deleteAll: 'Delete all',
    deleteAllTitle: 'Delete all crash reports?',
    deleteAllBody: 'The saved reports are removed from this computer. This cannot be undone.',
    deleteFailed: "Couldn't delete the report.",
    deleted: 'Deleted the crash report.',
    deletedAll: 'Deleted all crash reports.',
    reviewTitle: 'Review before sending',
    reviewIntro: 'This is exactly what would be sent, and nothing else.',
    sendTo: 'It would be sent to {address}.',
    noAddress: 'No address is set for crash reports, so this report can only stay on this computer.',
    send: 'Send this report',
    sending: 'Sending…',
    sent: 'The report was sent. It is still saved here until you delete it.',
    failed: "Couldn't send the report. It is still saved on this computer.",
    notOptedIn: 'Crash reports are off, so nothing can be sent. Turn them on in Settings, under Privacy.',
    close: 'Close',
  },
  selfCheck: {
    title: 'Check OpenNote',
    run: 'Check again',
    running: 'Checking…',
    lastRun: 'Checked {date} at {time}.',
    overall: {
      pass: 'Everything is in order.',
      warn: '{count, plural, one {# thing needs attention.} other {# things need attention.}}',
      fail: '{count, plural, one {# thing is wrong.} other {# things are wrong.}}',
      skipped: 'There was nothing to check.',
    },
    status: {
      pass: 'OK',
      warn: 'Needs attention',
      fail: 'Problem',
      skipped: 'Not checked',
    },
    item: {
      diskNotebook: 'Space for your notes',
      diskApp: 'Space for updates and backups',
      notebookWritable: 'Saving in the notebook folder',
      notebookStorage: 'Where the notebook is stored',
      notebookHealth: 'The notebook',
      updates: 'Updates',
      crashReports: 'Crash reports',
    },
    notApplicable: 'No notebook is open.',
    notApplicableUpdates: 'Updates are off.',
    notApplicableReports: 'Crash reports are not kept.',
    disk: {
      ok: '{size} free.',
      low: '{size} free. Free up some space soon, so saves and updates keep working.',
      critical: '{size} free. Free up space now, or OpenNote may not be able to save.',
      unknown: "Couldn't read how much space is free.",
    },
    writable: {
      yes: 'OpenNote can save in this folder.',
      no: "OpenNote can't save in this folder. Check that it exists and that you can change files in it.",
    },
    storage: {
      fileSystem: 'The notebook is on a {fileSystem} drive.',
      networkShare: 'It is on a network share, so saves can be slow, and the folder can disappear.',
      noMetadataLog: 'This drive keeps no change log, so a power cut can lose the last save.',
      syncFolder: '{tool} syncs this folder. Syncing while OpenNote saves can cause conflicts.',
      syncTool: {
        oneDrive: 'OneDrive',
        dropbox: 'Dropbox',
        googleDrive: 'Google Drive',
        iCloud: 'iCloud',
        other: 'A sync app',
      },
      unknown: "Couldn't read details about the drive.",
    },
    health: {
      clean: '{count, plural, one {Checked # file. No problems.} other {Checked # files. No problems.}}',
      problems:
        '{count, plural, one {# problem} other {# problems}} found in {files, plural, one {# file} other {# files}} checked.',
      problemLine: '{file}: {code}',
      moreProblems: '{count, plural, one {And # more.} other {And # more.}}',
      unsaved: 'Some changes are not saved yet. They save within a few seconds.',
      failed: "The check couldn't run.",
    },
    updates: {
      neverChecked: 'OpenNote has not checked for updates yet.',
      lastChecked: 'Last checked {days, plural, =0 {today} one {# day ago} other {# days ago}}.',
      stale: 'OpenNote has not checked for updates in {days, plural, one {# day} other {# days}}.',
      staged: 'Version {version} is downloaded and ready.',
      stuck: 'Version {version} has started {attempts, plural, one {# time} other {# times}} without a clean start.',
      rolledBack: 'Version {from} did not start, so OpenNote went back to version {to}.',
      blocked: '{count, plural, one {# version is} other {# versions are}} skipped.',
    },
    reports: {
      none: 'No crash reports are saved.',
      some: '{count, plural, one {# crash report is saved.} other {# crash reports are saved.}}',
    },
  },
  feedback: {
    title: 'Send feedback',
    intro:
      'This makes a file on your computer with what is needed to understand a problem. You read it first. ' +
      'OpenNote does not send it. You attach it to your report yourself.',
    descriptionLabel: 'What happened?',
    descriptionHelp: 'Optional. It goes in the file as you write it, so leave out anything private.',
    building: 'Collecting…',
    buildFailed: "Couldn't collect the file. Try again.",
    fileLabel: 'The whole file',
    partsLabel: 'What the file holds',
    saving: 'Saving…',
    canceled: 'Nothing was saved. Choose Save the file to pick a folder.',
    includeLogs: 'Include recent log lines',
    includeCrashReports: 'Include saved crash reports',
    crashReportsNone: 'No crash reports are saved.',
    crashReportsCount:
      '{count, plural, one {# crash report is saved.} other {# crash reports are saved.}} The newest 3 are included.',
    review: 'Review the file',
    reviewTitle: 'Review before saving',
    reviewIntro: 'This is exactly what the file will hold.',
    save: 'Save the file',
    saved: 'Saved as {name}. Attach it to your report or email.',
    failed: "Couldn't save the file. Pick another folder and try again.",
    close: 'Close',
    done: 'Done',
    back: 'Back',
    section: {
      description: 'What you wrote',
      system: 'System',
      selfCheck: 'Self-check',
      logs: 'Recent log lines',
      crashReports: 'Crash reports',
    },
    sectionCount: {
      description: '{count, plural, one {# character} other {# characters}}',
      system: '{count, plural, one {# line} other {# lines}}',
      selfCheck: '{count, plural, one {# check} other {# checks}}',
      logs: '{count, plural, one {# line} other {# lines}}',
      crashReports: '{count, plural, one {# report} other {# reports}}',
    },
    notIncluded: 'Not included',
    removedNothing: 'Nothing needed to be removed.',
    removed:
      '{count, plural, one {# thing was removed} other {# things were removed}} and replaced by marks such as <path>.',
  },
  safeStart: {
    title: 'OpenNote did not close properly',
    titleAgain: 'OpenNote stopped again in safe mode',
    intro: 'OpenNote stopped working during its last {count, plural, one {start} other {# starts}}.',
    introSafe: 'You can open it in safe mode, which turns off some extras so that your notebooks can open.',
    introAgain: 'OpenNote stopped working even in safe mode. Your notebooks are not changed by this.',
    introAgainAdvice:
      'You can try safe mode once more, or open OpenNote normally and send feedback so the cause can be found.',
    offHeading: 'Safe mode turns off',
    off: {
      backgroundWork: 'Background work, such as search indexing',
      embeds: 'Embeds, which show their saved preview instead',
      onDeviceModels: 'On-device models, such as handwriting recognition',
    },
    kept: 'Your notebooks stay open for reading and editing.',
    startSafe: 'Start in safe mode',
    startNormal: 'Start normally',
    announceSafe: 'Starting in safe mode.',
    announceNormal: 'Starting normally.',
    notice: {
      title: 'OpenNote is in safe mode',
      body: 'Some features are off so that your notebooks can open.',
      offHeading: 'Turned off',
      restart: 'To turn them back on, restart OpenNote normally.',
      restartButton: 'Restart normally',
    },
    stats: {
      none: 'There are no earlier sessions to count yet.',
      oneClean: 'The one earlier session ended without a crash.',
      oneCrashed: 'The one earlier session ended in a crash.',
      line: '{clean} of the last {sessions} sessions ended without a crash.',
    },
  },
} as const;
