// Formatting and block commands, the slash menu, outline, typing helpers, and text styles (owner: WP4).
// Each namespace file has one owner, so parallel work never edits the same file.

export const editor = {
  list: {
    emptyTask: 'Empty task',
  },
  callout: {
    named: '{type}: {title}',
    typeButton: 'Callout type: {type}',
    typeMenu: 'Callout type',
    types: {
      note: 'Note',
      tip: 'Tip',
      important: 'Important',
      warning: 'Warning',
      caution: 'Caution',
      info: 'Info',
      question: 'Question',
      success: 'Success',
      danger: 'Danger',
      example: 'Example',
      quote: 'Quote',
    },
  },
  fold: {
    collapse: 'Collapse {name}',
    expand: 'Expand {name}',
    expanded: 'Expanded {name}.',
    collapsedCallout: 'Folded {name}.',
    folded: 'Folded {name}, {count, plural, one {# paragraph} other {# paragraphs}} hidden.',
    nothing: 'Nothing here folds.',
    levels: 'Showing levels 1 to {level}.',
    all: 'Showing everything.',
  },
  math: {
    inline: 'Math: {source}',
    block: 'Display math: {source}',
    field: 'Math source',
  },
  image: {
    chip: 'Image: {alt}',
    chipUnnamed: 'Image without a description',
    chipText: 'Image',
    notLoaded: 'This image comes from {src}. OpenNote doesn’t load images from outside the page.',
  },
  commands: {
    bold: 'Bold',
    italic: 'Italic',
    underline: 'Underline',
    strike: 'Strikethrough',
    highlight: 'Highlight',
    code: 'Inline code',
    subscript: 'Subscript',
    superscript: 'Superscript',
    larger: 'Larger text',
    smaller: 'Smaller text',
    textColor: 'Text color',
    textSize: 'Text size',
    clear: 'Clear formatting',
    clearAll: 'Clear all formatting',
    link: 'Link',
    normal: 'Normal text',
    heading1: 'Heading 1',
    heading2: 'Heading 2',
    heading3: 'Heading 3',
    heading4: 'Heading 4',
    heading5: 'Heading 5',
    heading6: 'Heading 6',
    bulletList: 'Bulleted list',
    orderedList: 'Numbered list',
    checklist: 'Checklist',
    todoCycle: 'To Do',
    toggleCheck: 'Check or uncheck',
    quote: 'Quote',
    codeBlock: 'Code block',
    callout: 'Callout',
    divider: 'Divider',
    turnInto: 'Turn into',
    moveUp: 'Move up',
    moveDown: 'Move down',
    promote: 'Promote',
    demote: 'Demote',
    showLevel: 'Show level {level}',
    showAll: 'Show all levels',
    fold: 'Fold',
    unfold: 'Unfold',
    date: 'Date',
    time: 'Time',
    dateTime: 'Date and time',
    setColor: 'Text color of the selected blocks',
    textStyles: 'Text styles',
    styles: 'Styles',
    outdent: 'Outdent',
    indent: 'Indent',
  },
  keywords: {
    marks: 'format character style emphasis',
    color: 'font ink pen hue',
    size: 'font bigger smaller scale',
    clear: 'remove reset plain formatting',
    link: 'url hyperlink address web',
    block: 'paragraph style block format',
    list: 'bullets numbers items',
    task: 'todo to do tick check box',
    insert: 'add new block',
    outline: 'move reorder level indent outline',
    fold: 'collapse expand outline hide',
    date: 'today now timestamp',
  },
  announce: {
    on: '{name} on.',
    off: '{name} off.',
    block: '{name}.',
    sizeNormal: 'Normal size.',
    checked: 'Checked.',
    unchecked: 'Unchecked.',
    linkRemoved: 'Link removed.',
    noChange: '{name} doesn’t apply here.',
  },
  highlightColors: {
    honey: 'Honey',
    mint: 'Mint',
    rose: 'Rose',
    apricot: 'Apricot',
    lilac: 'Lilac',
    none: 'No highlight',
  },
  sizes: {
    small: 'Small',
    normal: 'Normal',
    large: 'Large',
    xlarge: 'Extra large',
  },
  colorMenu: {
    label: 'Text color',
    custom: 'Custom color…',
    automatic: 'Automatic',
  },
  sizeMenu: 'Text size',
  highlightMenu: 'Highlight color',
  turnIntoMenu: 'Turn into',
  link: {
    dialog: 'Link',
    address: 'Address',
    text: 'Text to show',
    save: 'Save link',
    remove: 'Remove link',
    open: 'Open link',
    copy: 'Copy link',
    edit: 'Edit link',
    invalid: 'Enter a web address, an email address, or an OpenNote link.',
    blocked: 'OpenNote doesn’t make links that run scripts.',
    copied: 'Link copied.',
    inert: 'OpenNote doesn’t open {scheme} links.',
  },
  textMenu: 'Text',
  linkMenu: 'Link',
  escapeHint: 'Press Escape, then Tab, to leave the text box.',
  tab: {
    bulleted: 'Bulleted list.',
    paragraph: 'Text.',
  },
  cross: {
    printable: 'Press Enter to edit, or Delete to remove the selected blocks.',
  },
  outline: {
    movedUp: 'Moved up.',
    movedDown: 'Moved down.',
    top: 'Top of the text box.',
    bottom: 'End of the text box.',
    level: 'Level {level}.',
    noLevel: 'Only list items and headings change level.',
    maxLevel: 'Heading 6 is the deepest level.',
    minLevel: 'Heading 1 is the top level.',
  },
  slash: {
    label: 'Insert a block',
    results: '{count, plural, =0 {No results.} one {# result.} other {# results.}}',
    option: '{name}, {position} of {count}.',
    groups: {
      basic: 'Basic blocks',
      lists: 'Lists',
      media: 'Media',
      advanced: 'Advanced',
    },
    keywords: {
      text: 'paragraph plain normal body',
      heading: 'heading title header h',
      bulletList: 'bullets unordered list ul',
      orderedList: 'numbers ordered list ol',
      checklist: 'todo task check box',
      quote: 'blockquote citation',
      callout: 'note tip warning admonition',
      codeBlock: 'code snippet program pre',
      divider: 'rule line separator hr',
      table: 'grid rows columns',
      image: 'picture photo figure',
      date: 'today',
      time: 'now clock',
      dateTime: 'timestamp now',
    },
  },
  autocorrect: {
    title: 'AutoCorrect',
    enabled: 'Correct as I type',
    enabledHint: 'Replaces the text on the left with the text on the right when a word ends.',
    list: 'Replacements',
    from: 'Replace',
    to: 'With',
    add: 'Add replacement',
    remove: 'Remove {from}',
    empty: 'No replacements yet.',
    duplicate: 'There’s already a replacement for {from}.',
    reset: 'Restore the default replacements',
  },
  general: {
    title: 'Typing',
    markdownShortcuts: 'Markdown shortcuts',
    markdownShortcutsHint: 'Typing # and a space makes a heading, ** around words makes them bold, and so on.',
    slashMenu: 'Slash menu',
    slashMenuHint: 'Typing / at the start of a line opens a menu of blocks.',
    formattingBar: 'Show the formatting bar',
    formattingBarTouch: 'For touch and pen',
    formattingBarAlways: 'Always',
    formattingBarNever: 'Never',
    dateLine: 'Add the date and time under the title of a new page',
  },
  styles: {
    title: 'Text styles',
    list: 'Styles',
    names: {
      normal: 'Normal text',
      h1: 'Heading 1',
      h2: 'Heading 2',
      h3: 'Heading 3',
      h4: 'Heading 4',
      h5: 'Heading 5',
      h6: 'Heading 6',
      title: 'Page title',
      quote: 'Quote',
      code: 'Code',
    },
    font: 'Font',
    size: 'Size',
    weight: 'Weight',
    color: 'Color',
    colorHex: 'Custom color, as #rrggbb',
    spaceBefore: 'Space before',
    spaceAfter: 'Space after',
    lineHeight: 'Line height',
    reset: 'Reset to default',
    resetAll: 'Reset every style',
    preview: 'The quick brown fox jumps over the lazy dog.',
    previewLight: 'Preview on a light page',
    previewDark: 'Preview on a dark page',
    defaultColor: 'Default',
    contrast: 'This color is hard to read on {theme, select, dark {dark} other {light}} pages.',
    saved: 'Text styles saved.',
    saveFailed: 'The text styles couldn’t be saved. Try again.',
    noNotebook: 'Open a page to change its notebook’s text styles.',
  },
  bar: {
    label: 'Formatting',
    more: 'More formatting',
  },
} as const;
