// Compare versions, named versions, and deleting history (owner: WP7).
// Each namespace file has one owner, so parallel work never edits the same file.

export const history = {
  commands: {
    open: 'Page history',
    compareWith: 'Compare with another version',
    nextChange: 'Next change',
    previousChange: 'Previous change',
    nameVersion: 'Name this version',
    deleteHistory: 'Delete page history',
    keywords: 'history versions compare restore older earlier changes',
  },
  panel: 'Page history',
  close: 'Close page history',
  loading: 'Loading versions…',
  failed: "Couldn't load this page's history.",
  empty: 'No earlier versions yet. Versions are saved as you work.',
  versions: 'Versions',
  current: 'Current page',
  named: 'Named',
  version: '{when} on {device}',
  reasons: {
    beforeEdit: 'Saved before editing here',
    closed: 'Saved when you closed the page',
    interval: 'Saved while you worked',
    exit: 'Saved when OpenNote closed',
    named: 'Saved with a name',
    beforeRestore: 'Saved before restoring a version',
    beforeUpgrade: 'Saved before an update',
    beforeLargeDelete: 'Saved before a large deletion',
    beforeRepair: 'Saved before a repair',
    conflict: 'Kept from another device',
    recovered: 'Recovered after a crash',
    unknown: 'Saved',
  },
  compare: {
    title: 'Comparing {older} with {newer}',
    with: 'Compare with',
    back: 'Back to versions',
    summary:
      '{changed, plural, one {# block changed} other {# blocks changed}}, {added} added, {removed} removed, {moved} moved.',
    noChanges: 'No differences.',
    added: 'Added:',
    removed: 'Removed:',
    unchanged: '{count, plural, one {# unchanged paragraph} other {# unchanged paragraphs}}',
    moved: 'Moved',
    table:
      'Table: {cells, plural, one {# cell changed} other {# cells changed}}, {added} rows added, {removed} removed',
    image: 'Image: {alt}',
    imageNotes: '{notes} changed',
    crop: 'crop',
    size: 'size',
    alt: 'alt text',
    blockAdded: 'Block added',
    blockRemoved: 'Block removed',
    other: '{type} changed',
    ink: 'Handwriting changed: {added} strokes added, {removed} removed',
    noMore: 'No more changes.',
    change: 'Change {index} of {total}',
  },
  restore: {
    paragraph: 'Restore this paragraph',
    block: 'Restore this block',
    version: 'Restore this version',
    copy: 'Restore as a copy',
    done: 'Restored.',
    copyDone: 'Restored as a copy.',
    failed: "Couldn't restore that. The current page hasn't changed.",
    gone: 'That paragraph changed since you opened this comparison. Compare again to restore it.',
  },
  name: {
    title: 'Name this version',
    label: 'Name',
    keep: 'Keep this version when history is trimmed',
    save: 'Save name',
    cancel: 'Cancel',
    done: 'Version named.',
  },
  delete: {
    action: 'Delete history',
    title: 'Delete the history of "{name}"?',
    page: "Saved versions of this page are removed. The current page isn't changed.",
    pages:
      "Saved versions of its {count, plural, one {# page} other {# pages}} are removed. Current pages aren't changed.",
    keepNamed: 'Keep named versions',
    confirm: 'Delete history',
    cancel: 'Cancel',
    done: 'History deleted.',
    failed: "Couldn't delete the history. Nothing was removed.",
  },
  settings: {
    title: 'Page history',
    keep: 'Keep history for',
    month: '30 days',
    year: '1 year',
    forever: 'Forever',
    help: 'Named versions are always kept. Older versions are thinned out over time.',
  },
} as const;
