// Image import, crop, and alt text (owner: WP5).
// Each namespace file has one owner, so parallel work never edits the same file.

export const images = {
  insert: 'Image…',
  insertKeywords: 'picture photo screenshot file insert',
  crop: 'Crop image',
  cropKeywords: 'trim cut edges',
  altText: 'Alt text…',
  altTextKeywords: 'description accessibility screen reader decorative',
  label: 'Image: {alt}',
  unnamed: 'Image, no description',
  decorativeLabel: 'Decorative image',
  noAltBadge: 'No alt text',
  missing: 'This image is still syncing or is missing.',
  adding: '{count, plural, one {Adding # image} other {Adding # images}}',
  added: '{count, plural, one {Added # image.} other {Added # images.}}',
  failed: "{count, plural, one {# image couldn't be added.} other {# images couldn't be added.}}",
  unsupported: "This image type can't be added. Save it as PNG or JPEG and try again.",
  tooLarge: "This image is larger than 50 MB, so it can't be added.",
  onlyImages: 'Only images can be added to a page for now.',
  toolbar: 'Image',
  resizeHandle: 'Resize from the {edge}',
  edges: {
    n: 'top',
    s: 'bottom',
    e: 'right',
    w: 'left',
    ne: 'top right corner',
    nw: 'top left corner',
    se: 'bottom right corner',
    sw: 'bottom left corner',
  },
  fitColumn: 'Fit to column',
  actualSize: 'Actual size',
  cropMode: {
    label: 'Crop image. Drag the handles, or use the arrow keys on a handle. Enter keeps the crop; Escape cancels.',
    handle: 'Crop from the {edge}',
    applied: 'Cropped the image.',
    cancelled: 'Crop canceled.',
  },
  cropFields: {
    legend: 'Crop',
    left: 'Crop left',
    top: 'Crop top',
    right: 'Crop right',
    bottom: 'Crop bottom',
    unit: 'percent',
    reset: 'Reset crop',
  },
  altDialog: {
    title: 'Alt text',
    description: "Describe the image for people who can't see it. Screen readers read this aloud.",
    field: 'Description',
    decorative: 'Decorative (screen readers skip it)',
    save: 'Save',
    count: '{count} of 2,000 characters',
  },
} as const;
