// Ink: the Draw tab, the pens, the erasers, the lasso, shapes, and palm rejection (owner: the Phase 5 ink lane).
// Each namespace file has one owner, so parallel work never edits the same file.

export const ink = {
  tools: {
    group: 'Drawing tools',
    select: 'Select and type',
    pen: 'Pen',
    pencil: 'Pencil',
    highlighter: 'Highlighter',
    eraser: 'Stroke eraser',
    partialEraser: 'Partial eraser',
    lasso: 'Lasso select',
    insertSpace: 'Insert space',
    writing: 'Writing pen',
    keywords: 'draw ink pen pencil highlighter write handwriting eraser erase lasso select',
  },
  pens: {
    group: 'Pens',
    slot: '{tool}, {color}, {width} mm',
    color: 'Color',
    width: 'Width',
    widthValue: '{width} mm',
    colorMenu: 'Pen color',
    widthMenu: 'Pen width',
  },
  colors: {
    Ink: 'Ink',
    Indigo: 'Indigo',
    Brick: 'Brick',
    Fern: 'Fern',
    Plum: 'Plum',
    Amber: 'Amber',
    Walnut: 'Walnut',
    Honey: 'Honey',
    Mint: 'Mint',
    Rose: 'Rose',
    Apricot: 'Apricot',
    Lilac: 'Lilac',
    custom: 'Custom color',
  },
  shapes: {
    inkToShape: 'Ink to shape',
    keywords: 'shape recognition line rectangle circle arrow snap',
    made: '{shape, select, line {Line} arrow {Arrow} rectangle {Rectangle} circle {Circle} other {Shape}}',
  },
  selection: {
    frame: 'Selected ink and text',
    move: 'Move the selection',
    resize: 'Resize the selection from the {corner} corner',
    corners: {
      nw: 'top left',
      ne: 'top right',
      se: 'bottom right',
      sw: 'bottom left',
    },
    delete: 'Delete the selection',
    recolor: 'Recolor the selection',
    thicker: 'Make ink thicker',
    thinner: 'Make ink thinner',
  },
  announce: {
    erased: '{count, plural, one {Erased # stroke} other {Erased # strokes}}',
    deleted: 'Selection deleted',
    tool: '{tool} chosen',
  },
  errors: {
    notSaved: "That ink wasn't saved. Try again.",
  },
  ask: { cancel: 'Cancel' },
  canvasLock: {
    title: 'Canvas lock',
    keywords: 'lock canvas scroll zoom pan freeze page',
    on: 'Canvas locked. The page stays still while you write.',
    off: 'Canvas unlocked',
  },
  hover: {
    title: 'Pen hover circle',
    keywords: 'hover preview cursor circle pen tip eraser size',
  },
  describe: {
    title: 'Describe drawing',
    keywords: 'alt text description decorative accessibility drawing ink screen reader',
    description: 'Say what the ink shows, for people who use a screen reader. It is saved with the page and its exports.',
    label: 'Description',
    decorative: 'This ink only decorates the page',
    save: 'Save',
    saved: 'Description saved',
    markedDecorative: 'Marked as decorative',
    none: 'There is no ink on this page to describe.',
  },
  options: {
    group: 'Eraser and lasso options',
    eraserType: 'Eraser type',
    eraserAll: 'Erase all ink',
    eraserHighlighter: 'Erase highlighter only',
    eraserPens: 'Erase pen and pencil only',
    eraserPen: 'Erase pen only',
    eraserPencil: 'Erase pencil only',
    returnToLast: 'Go back to the last tool after erasing',
    lasso: 'Lasso options',
    lassoFree: 'Freehand lasso',
    lassoRectangle: 'Rectangle lasso',
    pickGroup: 'Lasso picks up',
    pickInk: 'Ink',
    pickHighlighter: 'Highlighter',
    pickText: 'Typed text',
    pickImages: 'Images',
    pickShapes: 'Shapes',
  },
  settings: {
    title: 'Pen and touch',
    handedness: 'Writing hand',
    handednessAuto: 'Detect',
    handednessRight: 'Right hand',
    handednessLeft: 'Left hand',
    fingerDraw: 'Draw with a finger',
    fingerDrawAuto: 'Until a pen is used',
    fingerDrawOn: 'Always',
    fingerDrawOff: 'Never',
    fingerDrawHint: 'While a pen is near the screen, a touch never draws.',
  },
} as const;
