// Ink: the Draw tab, the pens, the erasers, the lasso, shapes, and palm rejection (owner: the Phase 5 ink lane).
// Each namespace file has one owner, so parallel work never edits the same file.

export const ink = {
  tools: {
    group: 'Drawing tools',
    select: 'Select and type',
    pen: 'Pen',
    pencil: 'Pencil',
    highlighter: 'Highlighter',
    eraser: 'Stroke eraser',
    partialEraser: 'Partial eraser',
    lasso: 'Lasso select',
    insertSpace: 'Insert space',
    writing: 'Writing pen',
    keywords: 'draw ink pen pencil highlighter write handwriting eraser erase lasso select',
  },
  pens: {
    group: 'Pens',
    slot: '{tool}, {color}, {width} mm',
    color: 'Color',
    width: 'Width',
    widthValue: '{width} mm',
    colorMenu: 'Pen color',
    widthMenu: 'Pen width',
  },
  colors: {
    Ink: 'Ink',
    Indigo: 'Indigo',
    Brick: 'Brick',
    Fern: 'Fern',
    Plum: 'Plum',
    Amber: 'Amber',
    Walnut: 'Walnut',
    Honey: 'Honey',
    Mint: 'Mint',
    Rose: 'Rose',
    Apricot: 'Apricot',
    Lilac: 'Lilac',
    custom: 'Custom color',
  },
  shapes: {
    inkToShape: 'Ink to shape',
    keywords: 'shape recognition line rectangle circle arrow snap',
    made: '{shape, select, line {Line} arrow {Arrow} rectangle {Rectangle} circle {Circle} polygon {Polygon} star {Star} arc {Arc} curvedArrow {Curved arrow} doubleArrow {Double arrow} other {Shape}}',
  },
  selection: {
    frame: 'Selected ink and text',
    move: 'Move the selection',
    resize: 'Resize the selection from the {corner} corner',
    corners: {
      nw: 'top left',
      ne: 'top right',
      se: 'bottom right',
      sw: 'bottom left',
    },
    delete: 'Delete the selection',
    recolor: 'Recolor the selection',
    thicker: 'Make ink thicker',
    thinner: 'Make ink thinner',
  },
  announce: {
    erased: '{count, plural, one {Erased # stroke} other {Erased # strokes}}',
    deleted: 'Selection deleted',
    tool: '{tool} chosen',
  },
  errors: {
    notSaved: "That ink wasn't saved. Try again.",
  },
  ask: { cancel: 'Cancel' },
  penEdit: {
    strikeThrough: 'Strike through words to delete them',
    addSpace: 'Draw a line between words to add a space',
    splitParagraph: 'Draw a long line between words to split the paragraph',
    circleSelect: 'Circle words to select them',
    deleted: 'Deleted "{text}"',
    selected: 'Selected "{text}"',
    spaced: 'Space added',
    split: 'Paragraph split',
    keywords: 'pen edit typed text strike through delete space split paragraph circle select words',
  },
  gridTable: {
    offer: 'That looks like a grid, {rows} rows by {columns} columns.',
    convert: 'Convert to table',
    converted: 'Table made, {rows} rows by {columns} columns',
  },
  handwriting: {
    working: 'Reading handwriting',
    none: 'No words found in that ink.',
    convert: 'Convert to text',
    straighten: 'Straighten',
    evenSpacing: 'Even spacing',
    reflowHandle: 'Drag to rewrap the handwriting to a new width',
    converted: 'Converted to text. The ink stays.',
    label: 'Added as the shape label. The ink stays.',
    tidied: 'Handwriting tidied. The original strokes moved, and one undo puts them back.',
    tidyNothing: 'The handwriting is already tidy.',
    written: '{count, plural, one {Wrote # line as text} other {Wrote # lines as text}}',
    noWritten: 'No ink has been turned into text yet.',
    inkShown: 'Written ink shown',
    inkHidden: 'Written ink faded',
    showInk: 'Show written ink',
    writingKeywords: 'writing pen convert handwriting text as you write words typed',
    tidyKeywords: 'tidy straighten even spacing reflow rewrap handwriting lines',
    convertKeywords: 'convert handwriting to text lasso recognize',
    group: 'Handwriting',
  },
  replay: {
    title: 'Replay ink',
    keywords: 'replay play back ink strokes timelapse written order audio',
    bar: 'Ink replay',
    play: 'Play',
    pause: 'Pause',
    position: 'Replay position',
    speed: '{speed}x',
    speedLabel: 'Speed {speed} times',
    shorten: 'Shorten pauses',
    close: 'Close',
    clock: '{at} of {total} seconds',
    none: 'There is no timed ink to replay.',
    audioKeepsPauses: 'Pauses stay as they were while the recording plays.',
  },
  library: {
    group: 'Shape libraries',
    menu: 'Shapes',
    keywords: 'shape library flowchart network entity diagram connector text label',
    addText: 'Add text to shape',
    addTextTitle: 'Add text to shape',
    textAdded: 'Text box added inside the shape. Type its label.',
    selectShape: 'Select one shape first.',
    inserted: '{shape} added',
    handle: 'Reshape handle',
    groups: { basic: 'Basic shapes', flowchart: 'Flowchart', network: 'Network', entity: 'Entity diagram' },
    line: 'Line',
    arrow: 'Arrow',
    doubleArrow: 'Double arrow',
    curvedArrow: 'Curved arrow',
    rectangle: 'Rectangle',
    circle: 'Circle',
    ellipse: 'Ellipse',
    triangle: 'Triangle',
    pentagon: 'Pentagon',
    hexagon: 'Hexagon',
    star: 'Star',
    process: 'Process',
    decision: 'Decision',
    terminator: 'Start or end',
    data: 'Data',
    document: 'Document',
    database: 'Database',
    cloud: 'Cloud',
    server: 'Server',
    router: 'Router',
    entity: 'Entity',
    weakEntity: 'Weak entity',
    relationship: 'Relationship',
    attribute: 'Attribute',
  },
  snap: {
    group: 'Ruler, protractor, and grid',
    ruler: 'Ruler',
    protractor: 'Protractor',
    grid: 'Snap to grid',
    gridSize: 'Grid size',
    gridValue: '{mm} mm',
    keywords: 'snap ruler protractor grid straight line angle align',
    on: '{tool} on',
    off: '{tool} off',
    rulerLabel: 'Ruler. Arrow keys move it, and the bracket keys turn it.',
    protractorLabel: 'Protractor. Arrow keys move it, and the bracket keys turn it.',
    turn: 'Turn',
    angle: '{degrees} degrees',
    placed: 'Placed',
  },
  space: {
    title: 'Insert space',
    keywords: 'insert space gap push down close move content line',
    description: 'Moves ink, floating text, and images below the middle of the view. Locked items stay.',
    height: 'Height in millimeters',
    heightHelp: 'A negative number closes a gap.',
    insert: 'Insert',
    invalid: 'Enter a number of millimeters, such as 10 or -10.',
    inserted:
      '{moved, plural, one {# item moved} other {# items moved}}{locked, plural, =0 {} one {, 1 locked item stays in place} other {, # locked items stay in place}}',
    none: 'No space was inserted.',
    nothing: 'There is nothing below the line to move.',
  },
  gestures: {
    erased: '{count, plural, one {Erased # stroke} other {Erased # strokes}}',
    undo: 'Undo',
    undone: 'Undone',
    redone: 'Redone',
    group: 'Pen and touch gestures',
    scribbleErase: 'Scribble to erase',
    circleSelect: 'Circle and tap to select',
    twoFingerUndo: 'Two-finger double tap to undo',
    threeFingerRedo: 'Three-finger double tap to redo',
    keywords: 'gesture scribble circle tap select undo redo finger touch pen',
  },
  canvasLock: {
    title: 'Canvas lock',
    keywords: 'lock canvas scroll zoom pan freeze page',
    on: 'Canvas locked. The page stays still while you write.',
    off: 'Canvas unlocked',
  },
  hover: {
    title: 'Pen hover circle',
    keywords: 'hover preview cursor circle pen tip eraser size',
  },
  describe: {
    title: 'Describe drawing',
    keywords: 'alt text description decorative accessibility drawing ink screen reader',
    description:
      'Say what the ink shows, for people who use a screen reader. It is saved with the page and its exports.',
    label: 'Description',
    decorative: 'This ink only decorates the page',
    save: 'Save',
    saved: 'Description saved',
    markedDecorative: 'Marked as decorative',
    none: 'There is no ink on this page to describe.',
  },
  options: {
    group: 'Eraser and lasso options',
    eraserType: 'Eraser type',
    eraserAll: 'Erase all ink',
    eraserHighlighter: 'Erase highlighter only',
    eraserPens: 'Erase pen and pencil only',
    eraserPen: 'Erase pen only',
    eraserPencil: 'Erase pencil only',
    returnToLast: 'Go back to the last tool after erasing',
    lasso: 'Lasso options',
    lassoFree: 'Freehand lasso',
    lassoRectangle: 'Rectangle lasso',
    pickGroup: 'Lasso picks up',
    pickInk: 'Ink',
    pickHighlighter: 'Highlighter',
    pickText: 'Typed text',
    pickImages: 'Images',
    pickShapes: 'Shapes',
  },
  settings: {
    title: 'Pen and touch',
    handedness: 'Writing hand',
    handednessAuto: 'Detect',
    handednessRight: 'Right hand',
    handednessLeft: 'Left hand',
    fingerDraw: 'Draw with a finger',
    fingerDrawAuto: 'Until a pen is used',
    fingerDrawOn: 'Always',
    fingerDrawOff: 'Never',
    fingerDrawHint: 'While a pen is near the screen, a touch never draws.',
    hover: 'Show a circle where a hovering pen will land',
    pen: 'Pen',
    penDefault: 'Any pen',
    penNumber: 'Pen {number}',
    penButtons: 'Pen buttons',
    penButtonsHint: 'These choices are saved for the pen you choose here.',
    barrel: 'Side button',
    barrelLasso: 'Lasso',
    barrelStrokeEraser: 'Stroke eraser',
    barrelPartialEraser: 'Partial eraser',
    barrelHighlighter: 'Highlighter',
    barrelPan: 'Pan the page',
    barrelRightClick: 'Right-click menu',
    barrelNothing: 'Nothing',
    eraserEnd: 'Eraser end',
    eraserEndStroke: 'Stroke eraser',
    eraserEndPartial: 'Partial eraser',
    eraserEndHighlighter: 'Highlighter eraser',
    eraserEndNothing: 'Nothing',
    pressure: 'Pressure curve',
    pressureHint: 'How hard you press sets how wide the line is. Each pen keeps its own curve.',
    curveSoft: 'Soft',
    curveNormal: 'Normal',
    curveFirm: 'Firm',
    curveCustom: 'Custom',
    curveLight: 'Light touch',
    curveHeavy: 'Firm touch',
    minWidth: 'Thinnest line',
    minWidthValue: '{percent}%',
    preview: 'Preview of a stroke with this curve',
    steady: 'Steady pen',
    steadyHint: 'Smooths a shaky hand. It is off until you turn it on.',
    steadyLight: 'Light',
    steadyMedium: 'Medium',
    steadyStrong: 'Strong',
    steadyStrength: 'Steady pen strength',
    zoomBox: 'Zoom writing box',
    magnification: 'Magnification',
    magnificationValue: '{times} times',
    autoAdvance: 'Move the box along as you write',
  },
} as const;
