// Ink: the Draw tab, the pens, the erasers, the lasso, shapes, and palm rejection (owner: the Phase 5 ink lane).
// Each namespace file has one owner, so parallel work never edits the same file.

export const ink = {
  tools: {
    group: 'Drawing tools',
    select: 'Select and type',
    pen: 'Pen',
    pencil: 'Pencil',
    highlighter: 'Highlighter',
    eraser: 'Stroke eraser',
    partialEraser: 'Partial eraser',
    lasso: 'Lasso select',
    keywords: 'draw ink pen pencil highlighter write handwriting eraser erase lasso select',
  },
  pens: {
    group: 'Pens',
    slot: '{tool}, {color}, {width} mm',
    color: 'Color',
    width: 'Width',
    widthValue: '{width} mm',
    colorMenu: 'Pen color',
    widthMenu: 'Pen width',
  },
  colors: {
    Ink: 'Ink',
    Indigo: 'Indigo',
    Brick: 'Brick',
    Fern: 'Fern',
    Plum: 'Plum',
    Amber: 'Amber',
    Walnut: 'Walnut',
    Honey: 'Honey',
    Mint: 'Mint',
    Rose: 'Rose',
    Apricot: 'Apricot',
    Lilac: 'Lilac',
    custom: 'Custom color',
  },
  shapes: {
    inkToShape: 'Ink to shape',
    keywords: 'shape recognition line rectangle circle arrow snap',
    made: '{shape, select, line {Line} arrow {Arrow} rectangle {Rectangle} triangle {Triangle} circle {Circle} ellipse {Ellipse} other {Shape}}',
  },
  selection: {
    frame: 'Selected ink and text',
    move: 'Move the selection',
    resize: 'Resize the selection from the {corner} corner',
    corners: {
      nw: 'top left',
      ne: 'top right',
      se: 'bottom right',
      sw: 'bottom left',
    },
    delete: 'Delete the selection',
    recolor: 'Recolor the selection',
    thicker: 'Make ink thicker',
    thinner: 'Make ink thinner',
  },
  announce: {
    erased: '{count, plural, one {Erased # stroke} other {Erased # strokes}}',
    deleted: 'Selection deleted',
    tool: '{tool} chosen',
  },
  errors: {
    notSaved: "That ink wasn't saved. Try again.",
  },
  settings: {
    title: 'Pen and touch',
    handedness: 'Writing hand',
    handednessAuto: 'Detect',
    handednessRight: 'Right hand',
    handednessLeft: 'Left hand',
    fingerDraw: 'Draw with a finger',
    fingerDrawAuto: 'Until a pen is used',
    fingerDrawOn: 'Always',
    fingerDrawOff: 'Never',
    fingerDrawHint: 'While a pen is near the screen, a touch never draws.',
  },
} as const;
