// Importing notes from other apps and exporting to files (Phase 11).
// Each namespace file has one owner, so parallel work never edits the same file.

export const interop = {
  commands: {
    import: 'Import notes…',
    export: 'Export…',
    keywords: 'import export obsidian evernote notion onenote markdown word html backup bring in save as',
  },
  import: {
    title: 'Import notes',
    intro:
      'Choose a file or folder exported from another app. OpenNote checks it first, and adds nothing until you say so.',
    chooseHeading: 'Choose what to import',
    chooseFile: 'Choose a file…',
    chooseFolder: 'Choose a folder…',
    stickyNotes: 'Import Sticky Notes from this PC',
    sourcesHeading: 'What you can import',
    sources: {
      markdown: 'Markdown folders from Obsidian, Joplin, and Logseq',
      evernote: 'Evernote exports (.enex)',
      notion: 'Notion exports',
      word: 'Word documents (.docx), including OneNote exports',
      web: 'Web pages (.html, .mht), text, and CSV files',
      other: 'Exports from Google Keep and Bear, and the Windows sticky notes app',
    },
    checking: 'Checking {name}…',
    checkingLabel: 'Checking your notes',
    importing: 'Importing {name}…',
    importingLabel: 'Importing your notes',
    building: 'Adding the notebook to your list…',
    progressOf: '{done} of {total} pages',
    progressDone: '{done, plural, one {# page so far} other {# pages so far}}',
    review: {
      summary: '{pages, plural, one {# page} other {# pages}} will come into a new notebook called "{title}".',
      noFiles: 'No pictures or files.',
      files: '{assets, plural, one {# picture or file} other {# pictures and files}} ({size}).',
      sections: '{count, plural, one {# section} other {# sections}}',
      sectionPages: '{pages, plural, one {# page} other {# pages}}',
      lossesHeading: 'What will change',
      noLosses: 'Everything in this source comes over as it is.',
      simplified: 'Simplified',
      skipped: 'Not imported',
      lossPages: '{pages, plural, =0 {} one {# page} other {# pages}}',
      reportPage: 'Add an "Import report" page to the notebook',
      reportPageHint: 'It lists what changed, page by page, so you can check later.',
      start: 'Import',
      back: 'Choose another',
      empty: 'There are no notes to import in this source.',
    },
    done: {
      title: 'Import finished',
      summary: '{pages, plural, one {# page was} other {# pages were}} added to the notebook "{title}".',
      changed: '{lost, plural, one {# page changed} other {# pages changed}} on the way in.',
      open: 'Open notebook',
      close: 'Done',
      undo: 'Undo import',
      undone: 'The import was moved to the Trash.',
    },
    unsupported: {
      title: "OpenNote can't import this yet",
      fallback: 'This version of OpenNote cannot read it.',
    },
    canceled: 'Import canceled. Nothing was added.',
    failed: {
      title: "The import didn't finish",
      unreadable: "OpenNote couldn't read this source. {detail}",
      io: "OpenNote couldn't open this source. Check that it is still there, then try again.",
      tooBig: 'This source is too big to import in one go. Try a smaller folder or fewer files.',
      other: 'Something went wrong, and nothing was added. {detail}',
      tryAgain: 'Try again',
    },
  },
  export: {
    title: 'Export "{name}"',
    intro: 'Choose a format and a folder. OpenNote makes a new folder or file there, so nothing is overwritten.',
    optionsHeading: 'Choose what to export',
    scopeLabel: 'What to export',
    scopes: {
      page: 'This page: "{name}"',
      section: 'This section: "{name}"',
      notebook: 'The whole notebook: "{name}"',
    },
    formatLabel: 'Format',
    formats: {
      markdown: 'Markdown files',
      markdownHint: 'A folder of .md files, with pictures in an assets folder.',
      html: 'Web pages',
      htmlHint: 'A folder of .html pages with an index.',
      htmlSingle: 'One web page',
      htmlSingleHint: 'A single .html file with the pictures inside it.',
      docx: 'Word document',
      docxHint: 'One .docx file with headings, lists, tables, and pictures.',
      pdf: 'PDF files',
      pdfHint: 'A folder of PDF files, one for each page.',
      xlsx: 'Tables as an Excel workbook',
      xlsxHint: 'One .xlsx file with a sheet for each table. Text outside tables is left out.',
      csv: 'Tables as CSV files',
      csvHint: 'One .csv file for a table, or a folder of them. Text outside tables is left out.',
    },
    folderLabel: 'Where to save it',
    folderNone: 'No folder chosen yet',
    chooseFolder: 'Choose a folder…',
    changeFolder: 'Change folder…',
    start: 'Export',
    exporting: 'Exporting {name}…',
    exportingLabel: 'Exporting your notes',
    nothing: 'There are no pages here to export. Choose something else, or add a page first.',
    nothingBack: 'Choose something else',
    done: {
      title: 'Export finished',
      summary: '{pages, plural, one {# page was} other {# pages were}} exported to {where}.',
      changed: '{lost, plural, one {# page changed} other {# pages changed}} on the way out.',
      show: 'Show in folder',
      close: 'Done',
    },
    canceled: 'Export canceled. Nothing was kept.',
    failed: {
      title: "The export didn't finish",
      io: "OpenNote couldn't write to that folder. Choose another folder, then try again.",
      unsupported: 'This format is not in this version yet. Choose another one.',
      other: 'Something went wrong, and nothing was kept. {detail}',
    },
  },
} as const;
