// More on-device intelligence (Phase 12): model downloads, the custom vocabulary, background work controls, the
// setup step, handwriting extras, search by meaning, ask your notes, and writing tools.
// Each namespace file has one owner, so parallel work never edits the same file.

export const intelPlus = {
  models: {
    heading: 'Models',
    intro: 'Some features need a model, a file that is downloaded once and then used on this device.',
    consent: 'Download only what you want. The size is shown first, and nothing downloads until you choose it.',
    sizeOf: '{size}',
    speechHeading: 'Speech to text',
    speechHelp: 'Turns a recording into a transcript. Choose one model.',
    download: 'Download',
    downloadNamed: 'Download {name}, {size}',
    cancel: 'Cancel',
    cancelNamed: 'Cancel the download of {name}',
    resume: 'Resume',
    resumeNamed: 'Resume the download of {name}',
    remove: 'Remove',
    removeNamed: 'Remove {name}',
    use: 'Use this model',
    inUse: 'In use',
    state: {
      notInstalled: 'Not downloaded',
      partial: '{done} of {size} downloaded. You can resume.',
      downloading: 'Downloading, {done} of {size}',
      installed: 'Downloaded',
      failed: 'Stopped: {reason}',
    },
    errors: {
      offline: 'Work offline is on. Turn it off in Privacy to download.',
      safeMode: 'Models are off in safe mode.',
      network: "Couldn't reach the download server. Try again.",
      checksum: "The file didn't match its checksum, so it was deleted. Try again.",
      io: "Couldn't save the file. Check the free space on this device.",
      invalid: "Couldn't download that. Try again.",
      unknown: "Couldn't download that. Try again.",
    },
    confirmTitle: 'Download {name}?',
    confirmBody:
      'It is {size}. It is saved on this device, and you can remove it later. The download uses your internet connection.',
    confirmYes: 'Download',
    confirmNo: 'Not now',
    removeTitle: 'Remove {name}?',
    removeBody: 'This deletes the file from this device. You can download it again later.',
    removeYes: 'Remove',
    privacyTitle: 'Model downloads',
    privacyDetail: 'Models for on-device features, only when you choose to download one.',
    folder: 'Saved on this device only. A portable install keeps them beside its other files.',
  },
  vocabulary: {
    title: 'Custom vocabulary',
    forNotebook: 'Custom vocabulary for {notebook}',
    forAll: 'Custom vocabulary for all notebooks',
    description: 'Names, course terms, acronyms, and spellings that the transcriber prefers. It stays on this device.',
    label: 'Terms, one on each line',
    help: 'Write "Calvin cycle | calvin psyche, kelvin cycle" to say how a term is often misheard. A line that starts with # is a note.',
    count: '{count, plural, =0 {No terms} one {# term} other {# terms}}',
    save: 'Save',
    cancel: 'Cancel',
    saved: 'Saved the vocabulary.',
    saveFailed: "Couldn't save the vocabulary.",
    import: 'Import a file',
    export: 'Export',
    imported: 'Added the terms from the file.',
    exportName: 'vocabulary.txt',
    editCommand: 'Edit custom vocabulary',
    editKeywords: 'transcript words names terms spelling dictionary',
    settingsButton: 'Edit custom vocabulary',
    settingsHelp: 'Words the transcriber should spell your way. One list for each notebook.',
    offerMessage: 'Add "{term}" to your vocabulary?',
    offerAdd: 'Add',
    added: 'Added "{term}".',
    previewTitle: 'Fix words with your vocabulary?',
    previewBody: '{count, plural, one {# change} other {# changes}} found. Nothing changes until you apply them.',
    previewChange: '"{from}" becomes "{to}"',
    previewNone: 'No words in this text need fixing.',
    apply: 'Apply',
    applied: 'Fixed {count, plural, one {# word} other {# words}}.',
    undo: 'Undo',
  },
  background: {
    title: 'Background work',
    openCommand: 'Show background work',
    openKeywords: 'activity queue pause idle plugged in battery limit',
    description: 'What OpenNote is doing for you in the background, in plain words. All of it runs on this device.',
    empty: 'Nothing is waiting.',
    kind: {
      imageText: 'Reading text in images',
      handwriting: 'Recognizing handwriting',
      transcription: 'Transcribing a recording',
      indexing: 'Indexing pages for search by meaning',
    },
    status: {
      waiting: 'Waiting',
      running: 'Working',
      paused: 'Paused',
      failed: "Didn't finish",
      done: 'Done',
    },
    unnamedImage: 'An image on the page',
    pause: 'Pause background work',
    resume: 'Resume background work',
    pausedNotice: 'Background work is paused.',
    onlyIdle: 'Only work when the computer is idle',
    onlyPlugged: 'Only work when plugged in',
    onlyRequest: 'Only run when I ask',
    onlyRequestHelp: 'Nothing is queued by itself. Use the commands to start work yourself.',
    cap: 'Share of the processor to use',
    capOption: '{percent}%',
    cancelJob: 'Cancel',
    cancelNamed: 'Cancel {name}',
    retry: 'Try again',
    clear: 'Clear finished',
    close: 'Close',
    waitingFor: {
      idle: 'Waiting for the computer to be idle.',
      power: 'Waiting for the computer to be plugged in.',
      paused: 'Paused.',
      request: 'Waiting for you to ask.',
    },
    summary: '{running} running, {waiting} waiting',
  },
  smart: {
    title: 'On-device intelligence',
    subtitle: 'Smart features read your notes on this computer. Nothing leaves the device.',
    privacy:
      'Everything runs on this device. Nothing is sent anywhere, and every feature can be turned off in Settings.',
    group: 'Choose how to set up smart features',
    recommended: 'Recommended',
    recommendedHelp:
      'Transcription, handwriting recognition, text in images, and summaries, all running on this device.',
    custom: 'Custom',
    customHelp: 'Pick each feature yourself. Each one runs on this device.',
    notNow: 'Not now',
    notNowHelp: 'Everything stays off. You can turn features on later in Settings.',
    downloads: 'Downloads',
    downloadSize: 'The speech model is {size}. It downloads only if you choose to, and only after you finish setup.',
    noDownload: 'Nothing needs to be downloaded for this feature.',
    features: 'Features',
    featureOn: 'Use {feature}',
    transcription: 'transcription',
    speechModel: 'Speech model',
    speechModelNone: 'Choose later',
    speechModelOption: '{name}, {size}',
    committed: 'Smart features are set up.',
  },
  handwriting: {
    reviewTitle: 'Check the handwriting',
    reviewBody:
      '{count, plural, =0 {Every word looks clear.} one {# word is underlined because it may be wrong.} ' +
      'other {# words are underlined because they may be wrong.}}',
    reviewHelp:
      'Choose an underlined word to see other readings. Symbols and chemical formulas are tidied when you insert.',
    alternatives: 'Other readings',
    unsureWord: '{word}, unsure. Choose another reading.',
    insert: 'Insert',
    cancel: 'Cancel',
  },
  extras: {
    heading: 'Search and writing',
    intro: 'These read your pages on this device with no model to download. Each one stays off until you turn it on.',
    offerTitle: 'Turn on {feature}?',
    meaning: {
      name: 'search by meaning',
      label: 'Search by meaning and related pages',
      help:
        'Finds pages about the same idea even when the words differ, and lists related pages beside a page. ' +
        'It keeps a private index of your pages on this device, and skips locked sections.',
      offer:
        'OpenNote can find pages by meaning and list related pages. It keeps a private index of your pages on this device.',
    },
    ask: {
      name: 'ask your notes',
      label: 'Ask your notes',
      help: 'Answers a question from your own pages and lists the pages it used, so you can check it. It turns on search by meaning too.',
      offer:
        'OpenNote can answer a question from your own pages and list the pages it used. This turns on search by meaning too.',
    },
    writing: {
      name: 'writing tools',
      label: 'Writing tools',
      help:
        'Proofread, rewrite, shorten, make a list, or tidy the structure of selected text. ' +
        'Changes are marked, and nothing is replaced until you accept.',
      offer:
        'OpenNote can suggest changes to the text you select. Changes are marked, and nothing is replaced until you accept.',
    },
    forget: 'The index of your pages was deleted from this device.',
  },
  meaning: {
    findCommand: 'Find by meaning',
    findKeywords: 'semantic related similar concept idea search ask',
    findTitle: 'Find by meaning',
    findBody: 'Describe what you are looking for. Pages about the same idea are listed, even when the words differ.',
    findLabel: 'What are you looking for?',
    results: 'Pages that match',
    none: 'No pages match yet. Try other words.',
    stillReading: 'No match yet. OpenNote is still reading your pages.',
    progress: 'Reading your pages: {done} of {total}',
    how: 'Matches use the words and word parts in your pages, and a short list of words that mean the same. A trained model is not needed.',
    untitled: 'Untitled page',
    close: 'Close',
    indexingLabel: 'Your pages',
    relatedCommand: 'Show related pages',
    relatedKeywords: 'similar pages like this meaning suggestions',
    relatedTitle: 'Related pages',
    relatedNone: 'No related pages yet.',
    relatedNoPage: 'Open a page to see pages related to it.',
  },
  ask: {
    command: 'Ask your notes',
    keywords: 'question answer chat search notes assistant',
    title: 'Ask your notes',
    body: 'Ask a question in your own words. The answer comes from your pages, and the pages it used are listed.',
    label: 'Your question',
    ask: 'Ask',
    close: 'Close',
    working: 'Looking through your pages',
    none: "Your pages don't seem to say. Try other words.",
    quoted: 'These sentences are quoted from your pages.',
    composed: 'This answer was written from your pages by a model on this device.',
    check: 'Answers can be wrong. Open the pages below to check.',
    sources: 'Pages used',
    openSource: 'Open page {number}, {title}',
  },
  writing: {
    tools: {
      proofread: 'Proofread',
      rewrite: 'Rewrite in plain words',
      shorten: 'Shorten',
      list: 'Make a list',
      tidy: 'Tidy structure',
    },
    keywords: 'writing proofread rewrite shorten list tidy grammar spelling edit',
    reviewBody:
      '{count, plural, =0 {No changes to suggest.} one {# change is marked.} other {# changes are marked.}} ' +
      'Nothing is replaced until you accept.',
    legend: 'Added words are underlined. Removed words are crossed out.',
    addedStart: 'Added: ',
    addedEnd: ' End of added text.',
    removedStart: 'Removed: ',
    removedEnd: ' End of removed text.',
    accept: 'Accept',
    cancel: 'Cancel',
    accepted: 'Replaced the selected text.',
    undo: 'Undo',
    noSelection: 'Select some text first.',
  },
} as const;
