// The page area (owner after WP0: WP3): the page view, blocks, objects, and page zoom. Every interface string is a
// full sentence here, never joined from pieces (ARCHITECTURE.md section 19).

export const page = {
  zoom: {
    in: 'Zoom page in',
    out: 'Zoom page out',
    reset: 'Actual page size',
    fitWidth: 'Fit page to width',
    keywords: 'zoom page magnify bigger smaller scale',
    announce: 'Page zoom {percent} percent.',
  },
  title: {
    label: 'Page title',
    placeholder: 'Untitled page',
  },
  block: {
    text: 'Text box',
    textEditor: 'Text',
    placeholder: 'Start writing',
    image: 'Image: {alt}',
    imageUnnamed: 'Image without a description',
    table: 'Table',
    unknown: 'A {type} block that this version can’t show yet',
    roleText: 'text box',
    roleImage: 'image',
    roleTable: 'table',
    floatingName: 'Text box {index} of {count}',
    flowName: 'Page text',
    flowPartName: 'Page text, part {index} of {count}',
  },
  commands: {
    newTextBox: 'New text box',
    newTextBoxKeywords: 'add insert text box note container',
    layout: 'Change page layout',
    layoutKeywords: 'freeform flow canvas column layout',
    readingView: 'Switch between reading view and canvas',
    readingViewKeywords: 'reading view canvas compact column',
    readingOrderPane: 'Reading order',
    readingOrderPaneKeywords: 'reading order screen reader accessibility tab order',
  },
  layout: {
    nowFlow: 'This page now flows in one column.',
    nowFreeform: 'This page is now freeform.',
  },
  reading: {
    toCanvas: 'Canvas',
    toReading: 'Reading view',
    nowReading: 'Reading view. Blocks show in reading order in one column.',
    nowCanvas: 'Canvas. Blocks show where they were placed.',
  },
  object: {
    bringToFront: 'Bring to front',
    sendToBack: 'Send to back',
    bringForward: 'Bring forward',
    sendBackward: 'Send backward',
    alreadyFront: 'Already in front',
    alreadyBack: 'Already at the back',
    arrangeKeywords: 'arrange order z-order front back layer',
    edit: 'Edit text',
    editKeywords: 'edit type text enter',
    delete: 'Delete',
    deleteKeywords: 'delete remove object block',
    deleted: '{count, plural, one {Deleted # object.} other {Deleted # objects.}}',
    undo: 'Undo',
    lock: 'Lock',
    lockPosition: 'Lock position',
    unlock: 'Unlock',
    lockKeywords: 'lock pin freeze position',
    locked: 'This text box is locked in place. Unlock it from its menu.',
    lockedNow: 'Locked.',
    lockedPositionNow: 'Position locked.',
    unlockedNow: 'Unlocked.',
    float: 'Float',
    putInFlow: 'Put in flow',
    floatKeywords: 'float flow column position',
    moved: 'Moved.',
    resized: 'Width {width}.',
    sizeAndPosition: 'Size and position',
    sizeKeywords: 'size position width height x y exact',
    x: 'X',
    y: 'Y',
    width: 'Width',
    height: 'Height',
    apply: 'Apply',
    grip: 'Move {name}',
    widthHandle: 'Change the width of {name}',
    nothingSelected: 'Select a block on the page first.',
    menuLabel: 'Object',
  },
  selection: {
    count: '{count, plural, one {# item selected.} other {# items selected.}}',
    badge: '{count, plural, one {# selected} other {# selected}}',
    none: 'Nothing selected.',
    allBlocks: 'Selected every block on the page.',
  },
  order: {
    title: 'Reading order',
    list: 'Blocks in reading order',
    text: 'Text: {summary}',
    textEmpty: 'Text box',
    image: 'Image: {alt}',
    imageUnnamed: 'Image',
    table: '{columns, plural, one {Table: # column} other {Table: # columns}}',
    ink: 'Handwriting',
    other: 'Block',
    moveUp: 'Move up',
    moveDown: 'Move down',
    reset: 'Reset to default order',
    close: 'Close reading order',
    movedTo: 'Moved to {index} of {count}.',
    resetDone: 'Reading order reset to the default.',
  },
  openFailed: 'This page couldn’t be opened. Try again, or choose another page.',
} as const;
