// More page layouts, sheets, and export (the pages area's second pass): layout templates, the sheet navigator, accessible
// PDF, the elements library, selection export, presenting with a laser pointer, and syllable marks. Each namespace file
// has one owner, so parallel work never edits the same file.

export const pagesPlus = {
  commands: {
    keywords:
      'layout template lab notebook planner storyboard spacing sheet navigator elements laser present syllables',
    templateLab: 'Lab notebook',
    templatePlanner: 'Planner',
    templateStoryboard: 'Storyboard',
    templateKeywords: 'template layout lab notebook planner storyboard paper',
    spacing: 'Line spacing…',
    spacingKeywords: 'spacing ruled grid lines squares millimeters custom',
    layoutTemplates: 'Layout templates…',
    layoutTemplatesKeywords: 'save share import export template layout custom paper',
    notebookDefault: 'Use this layout for new pages in this notebook',
    notebookDefaultClear: 'Stop using a layout for new pages in this notebook',
    sheetNavigator: 'Sheet strip',
    sheetFlip: 'Flip sheets one at a time',
    sheetGoTo: 'Go to sheet…',
    sheetNext: 'Next sheet',
    sheetPrevious: 'Previous sheet',
    sheetAdd: 'Add a sheet',
    sheetKeywords: 'sheet page navigator thumbnails strip flip go to add next previous',
    notebookDefaultKeywords: 'notebook default layout new pages paper',
  },
  pdf: {
    accessible: 'Accessible PDF',
    accessibleHelp:
      'Adds headings, lists, tables, reading order, picture descriptions, the page’s language, and bookmarks, so a screen reader can follow the file.',
  },
  sheets: {
    strip: 'Sheets',
    goTo: 'Go to sheet {n}',
    previous: 'Previous sheet',
    next: 'Next sheet',
    add: 'Add a sheet',
    added: 'Sheet {n} added',
    at: 'Sheet {n} of {total}',
    dialog: {
      title: 'Go to sheet',
      description: 'Jump to any sheet of this page.',
      field: 'Sheet number, 1 to {max}',
      invalid: 'Enter a whole number from 1 to {max}.',
      go: 'Go',
      cancel: 'Cancel',
    },
  },
  layouts: {
    lab: { title: 'Title', date: 'Date', project: 'Project', signed: 'Signed', witnessed: 'Witnessed' },
    planner: { date: 'Date', todo: 'To do', notes: 'Notes' },
    applied: '{name} layout applied',
    spacing: {
      title: 'Line spacing',
      description: 'The distance between lines or grid squares on this page.',
      field: 'Spacing in millimeters',
      help: 'From {min} to {max} mm.',
      invalid: 'Enter a number from {min} to {max}.',
      apply: 'Apply',
      cancel: 'Cancel',
      none: 'This paper has no lines to space. Choose ruled, grid, or dot paper first.',
      done: 'Spacing set to {mm} mm',
    },
    templates: {
      title: 'Layout templates',
      description: 'Keep this page’s paper and background, and use or share it later.',
      name: 'Name for the new template',
      withPaper: 'Include the paper size and margins',
      save: 'Save this layout',
      saved: 'Saved the {name} template',
      empty: 'No saved templates yet.',
      use: 'Use',
      useLabel: 'Use {name} on this page',
      share: 'Share',
      shareLabel: 'Save {name} as a file',
      remove: 'Delete',
      removeLabel: 'Delete {name}',
      import: 'Import a template…',
      importDone: 'Imported the {name} template',
      close: 'Done',
      full: 'You can keep up to {max} templates. Delete one first.',
      badName: 'Give the template a name.',
      fileLabel: 'Layout template',
      tooBig: 'That file is too large to be a layout template.',
      notJson: 'That file isn’t a layout template.',
      notLayout: 'That file isn’t a layout template.',
      newer: 'That template was made by a newer version of OpenNote.',
      invalid: 'That template file is damaged.',
      fileSaved: 'Saved {name}',
      failed: 'The template couldn’t be saved.',
      deleted: 'Deleted the {name} template',
    },
    notebook: {
      set: 'New pages in this notebook will use this layout.',
      cleared: 'New pages in this notebook start plain again.',
      none: 'Open a page in a notebook first.',
      failed: 'This device couldn’t keep the setting.',
    },
  },
} as const;
