// Page views and export (Phase 6): the View tab's page layout, paper, and backgrounds, print and export, the page
// gallery, and slides. Each namespace file has one owner, so parallel work never edits the same file.

export const pageViews = {
  commands: {
    keywords: 'page view paper sheet print pdf export markdown html image gallery slides present background',
    canvas: 'Infinite canvas',
    pages: 'Pages with breaks',
    modeKeywords: 'paginated pages page breaks infinite canvas sheets paper view',
    flow: 'Document flow',
    freeCanvas: 'Free canvas',
    layoutKeywords: 'layout flow document free canvas freeform',
    paperMenu: 'Paper',
    paperKeywords: 'paper size letter a4 a5 legal tabloid portrait landscape margins',
    backgroundMenu: 'Background',
    backgroundKeywords: 'background lined ruled grid dot dots graph cornell plain paper',
    fitSheet: 'Fit page',
    readingAids: 'Reading aids',
    readingKeywords: 'reading aids focus line tint spacing syllables dyslexia',
    print: 'Print…',
    exportMenu: 'Export',
    exportPdf: 'Export as PDF…',
    exportMarkdown: 'Export as Markdown…',
    exportHtml: 'Export as HTML…',
    exportImage: 'Export selection as image…',
    exportKeywords: 'export save as pdf markdown html png svg image',
    gallery: 'Page gallery',
    galleryKeywords: 'gallery thumbnails grid pages reorder',
    present: 'Present as slides',
    presentKeywords: 'present slides slideshow full screen',
  },
  paper: {
    size: {
      letter: 'Letter',
      a4: 'A4',
      a5: 'A5',
      legal: 'Legal',
      tabloid: 'Tabloid',
      custom: 'Custom size',
    },
    portrait: 'Portrait',
    landscape: 'Landscape',
    margins: { narrow: 'Narrow margins', normal: 'Normal margins', wide: 'Wide margins' },
    dimensions: '{width} × {height} in',
  },
  background: {
    plain: 'Plain',
    'ruled-narrow': 'Lined, narrow',
    'ruled-college': 'Lined, college',
    'ruled-wide': 'Lined, wide',
    'grid-5mm': 'Grid, 5 mm',
    'grid-quarter-inch': 'Grid, quarter inch',
    'grid-1cm': 'Grid, 1 cm',
    dots: 'Dot grid',
    isometric: 'Isometric',
    cornell: 'Cornell notes',
    staff: 'Music staff',
    marginLine: 'Margin line',
  },
  status: {
    nowPages: 'Pages with breaks. {sheets, plural, one {# sheet} other {# sheets}}.',
    nowCanvas: 'Infinite canvas.',
    nowFlow: 'Document flow.',
    nowFree: 'Free canvas.',
    paperSet: 'Paper set to {paper}.',
    backgroundSet: 'Background set to {background}.',
    sheetCount: 'Sheet {sheet} of {sheets}',
    pageTooLong: 'This page is longer than {max} sheets. Only the first {max} show.',
  },
  reading: {
    title: 'Reading aids',
    description: 'These change how the page looks on this device. They never change the note or what you print.',
    focus: 'Line focus',
    focusHelp: 'Dim every line but the one you are on.',
    tint: 'Page tint',
    tints: { none: 'None', cream: 'Cream', blue: 'Blue', green: 'Green', gray: 'Gray' },
    lineSpacing: 'Line spacing',
    letterSpacing: 'Letter spacing',
    lineWidth: 'Line width',
    syllables: 'Show syllable breaks',
    syllablesHelp: 'Marks where long words can be read in parts.',
    reset: 'Reset',
    close: 'Done',
    spacing: { normal: 'Normal', relaxed: 'Relaxed', loose: 'Loose' },
    width: { full: 'Full', medium: 'Medium', narrow: 'Narrow' },
  },
  print: {
    title: 'Print',
    exportTitle: 'Export as PDF',
    description: 'The PDF has the same page breaks as the view. Ink stays sharp at any size.',
    sheets: 'Sheets',
    range: 'Pages',
    rangeAll: 'All sheets',
    rangeSome: 'These sheets',
    rangePlaceholder: 'For example 1-3, 5',
    parity: 'Print',
    parityAll: 'Every sheet',
    parityOdd: 'Odd sheets',
    parityEven: 'Even sheets',
    header: 'Header',
    footer: 'Footer',
    headerHint: 'Use {title}, {page}, {pages}, {date}',
    paperPattern: 'Print the paper lines',
    previewLabel: 'Preview of sheet {sheet}',
    previewing: 'Preparing the preview…',
    previewFailed: "The preview isn't available.",
    sheetCount: '{count, plural, one {# sheet} other {# sheets}} on {paper}',
    badRange: 'That range has no sheets in it. This page has {sheets, plural, one {# sheet} other {# sheets}}.',
    export: 'Export…',
    print: 'Print…',
    cancel: 'Cancel',
    working: 'Making the PDF…',
    stage: {
      prepare: 'Laying out the sheets…',
      render: 'Printing to PDF…',
      verify: 'Checking the file…',
    },
    stop: 'Stop',
    done: 'Saved {name}.',
    stopped: 'Export stopped.',
    failed: "The PDF couldn't be made. Nothing was saved.",
    timedOut: 'The PDF took too long. Nothing was saved.',
    unavailable: 'Making a PDF needs the OpenNote app for Windows.',
    openFile: 'Show in folder',
    problems: 'The PDF was saved with a few things to know',
    problem: {
      pageCount: 'The file has a different number of pages than planned.',
      pageSize: 'A page is not the size of the sheet.',
      untagged: "The PDF doesn't have reading structure for screen readers yet.",
      noLanguage: "The PDF doesn't name its language.",
      noText: 'A page has no text you can search.',
      variableFonts: 'The fonts are saved as shapes, so some viewers show text slightly differently.',
      blankPage: 'A page came out blank.',
    },
    handwriting: 'Handwriting',
    untitled: 'Untitled page',
  },
  files: {
    saved: 'Saved {name}.',
    failed: "The file couldn't be saved.",
    markdownLabel: 'Markdown',
    htmlLabel: 'Web page',
    pdfLabel: 'PDF',
    pngLabel: 'PNG image',
    svgLabel: 'SVG image',
    unavailable: 'Saving files needs the OpenNote app for Windows.',
    nothing: 'There is no page open to export.',
  },
  image: {
    title: 'Export selection as image',
    description: 'Select blocks on the page first, or export the whole page.',
    selection: 'Selected blocks',
    wholePage: 'Whole page',
    format: 'Format',
    scale: 'Resolution',
    scales: { one: 'Standard', two: 'Sharp (2×)', three: 'Print (3×)' },
    save: 'Save…',
    copy: 'Copy',
    preview: 'Preview of the picture',
    copied: 'Copied the picture.',
    nothingSelected: 'Select something on the page first, or choose the whole page.',
    tooLarge: 'The picture is too large at this resolution. Choose a lower one.',
    failed: "The picture couldn't be made.",
    smart: 'Smart select',
  },
  gallery: {
    title: 'Page gallery',
    label: 'Pages in {section}',
    cell: '{title}, {position} of {total}',
    empty: 'This section has no pages yet.',
    moveUp: 'Move earlier',
    moveDown: 'Move later',
    open: 'Open',
    close: 'Close gallery',
    moved: 'Moved {count, plural, one {# page} other {# pages}}.',
    noSection: 'Open a section to see its pages here.',
    modified: 'Changed {date}',
    thumbnail: 'Preview of {title}',
    selected: '{count, plural, one {# page selected} other {# pages selected}}',
  },
  slides: {
    title: 'Slides',
    label: 'Slide {n} of {total}',
    counter: '{n} / {total}',
    next: 'Next slide',
    previous: 'Previous slide',
    exit: 'Exit slides',
    untitled: 'Slide {n}',
    splitHeadings: 'Start a slide at each heading',
    splitRules: 'Start a slide at each divider line',
    help: 'Arrow keys or space to move. Escape to leave.',
    empty: 'This page has nothing to present yet.',
    navigator: 'Slides',
    gone: 'Slide {n}: {title}',
  },
} as const;
