// The quality-of-life features of typed notes and the page chrome (owner: the typed-notes lane): Reading mode, word
// count, checklist extras, find and replace, the table of contents, templates, series pages, the Markdown source,
// attachments, text wrap, and their settings. Each namespace file has one owner, so parallel work never edits the
// same file.

export const pageExtras = {
  lock: {
    command: 'Lock page for reading',
    commandKeywords: 'reading mode lock read only protect freeze',
    on: 'Page locked for reading.',
    off: 'Page unlocked.',
    blocked: 'The page is locked for reading. Unlock it to make changes.',
    chip: 'Locked for reading',
    unlock: 'Unlock',
  },
  words: {
    command: 'Announce word count',
    commandKeywords: 'word count reading time length how long',
    page: '{count, plural, one {# word} other {# words}} · {minutes, plural, one {# min read} other {# min read}}',
    selection:
      '{count, plural, one {# word} other {# words}} selected · {total, plural, one {# word} other {# words}} in all',
    announcePage:
      '{count, plural, one {# word} other {# words}} on this page. About {minutes, plural, one {# minute} other {# minutes}} to read.',
    announceSelection: '{count, plural, one {# word} other {# words}} selected.',
    empty: 'No words yet.',
  },
  checklist: {
    checkAll: 'Check all items',
    uncheckAll: 'Uncheck all items',
    keep: 'Keep finished items in place',
    bottom: 'Move finished items to the bottom',
    hide: 'Hide finished items',
    toggleCount: 'Show done count',
    commandKeywords: 'checklist check all uncheck finished done tasks to do',
    count: '{done} of {total} done',
    hidden: '{count, plural, one {# finished item hidden} other {# finished items hidden}}',
    show: 'Show',
    hideAgain: 'Hide',
    notInList: 'Put the caret in a checklist first.',
    checkedAll: 'All items checked.',
    uncheckedAll: 'All items unchecked.',
    modeKeep: 'Finished items stay in place.',
    modeBottom: 'Finished items move to the bottom.',
    modeHide: 'Finished items are hidden.',
  },
  caret: {
    title: 'Caret',
    windows: 'Follow the Windows text cursor settings',
    windowsHelp: 'Width and blinking come from Settings, then Accessibility, then Text cursor, in Windows.',
    width: 'Caret width',
    widthHelp: '1 to 6 pixels.',
    steady: 'Keep the caret steady',
    steadyHelp: 'A steady caret does not blink.',
  },
  typewriter: {
    title: 'Typewriter scrolling',
    on: 'Keep the line you type at one height',
    help: 'The page moves under the caret as you type. It jumps instead of gliding when Windows animation is off.',
    at: 'Height of the line',
    atHelp: 'As a percentage of the page, from the top. 50 is the middle.',
    command: 'Turn typewriter scrolling on or off',
    commandKeywords: 'typewriter scrolling center caret line focus',
  },
  pasteSize: {
    title: 'Pasted screenshots and images',
    actual: 'Actual size',
    fit: 'Fit to the column',
    ask: 'Ask each time',
    help: 'Actual size follows the scaling of this display, so a screenshot looks as it did on screen.',
    askMessage: 'Pasted at the width of the column.',
    useActual: 'Use actual size',
  },
  linkTitles: {
    title: 'Link titles',
    on: 'Show the page title when I paste a web address',
    help: 'This asks the site for its page title. The site sees this PC’s network address and the request, and nothing else. It never runs while Work offline is on, and never for addresses on your own network.',
    privacyTitle: 'Link titles on paste',
    privacyDetail:
      'Asks a site for its page title when you paste its address, only if you turned this on in Settings, then Editing.',
    privacyNever: 'Not turned on',
    privacyOn: 'Turned on',
  },
  settings: {
    title: 'Page extras',
    doneCount: 'Show the done count beside checklists',
    wordCount: 'Show the word count under the page',
  },
  find: {
    openFind: 'Find on page',
    openReplace: 'Find and replace on page',
    keywords: 'find replace search text page',
    next: 'Find next',
    previous: 'Find previous',
    label: 'Find',
    replaceLabel: 'Replace with',
    matchCase: 'Match case',
    wholeWord: 'Whole word',
    replaceOne: 'Replace',
    replaceAll: 'Replace all',
    close: 'Close',
    bar: 'Find on page',
    none: 'No matches',
    count: '{index} of {total}',
    total: '{count, plural, one {# match} other {# matches}}',
    replaced: '{count, plural, one {Replaced # match.} other {Replaced # matches.}}',
    readOnly: 'The page is read-only.',
  },
  toc: {
    command: 'Show or hide the table of contents',
    commandKeywords: 'table of contents headings outline navigate jump',
    title: 'Contents',
    label: 'Table of contents',
    empty: 'No headings yet. Make a heading with Ctrl+Alt+1.',
    jumped: 'Moved to {title}.',
    close: 'Close contents',
  },
} as const;
