// The quality-of-life features of typed notes and the page chrome (owner: the typed-notes lane): Reading mode, word
// count, checklist extras, find and replace, the table of contents, templates, series pages, the Markdown source,
// attachments, text wrap, and their settings. Each namespace file has one owner, so parallel work never edits the
// same file.

export const pageExtras = {
  lock: {
    command: 'Lock page for reading',
    commandKeywords: 'reading mode lock read only protect freeze',
    on: 'Page locked for reading.',
    off: 'Page unlocked.',
    blocked: 'The page is locked for reading. Unlock it to make changes.',
    chip: 'Locked for reading',
    unlock: 'Unlock',
  },
  words: {
    command: 'Announce word count',
    commandKeywords: 'word count reading time length how long',
    page: '{count, plural, one {# word} other {# words}} · {minutes, plural, one {# min read} other {# min read}}',
    selection:
      '{count, plural, one {# word} other {# words}} selected · {total, plural, one {# word} other {# words}} in all',
    announcePage:
      '{count, plural, one {# word} other {# words}} on this page. About {minutes, plural, one {# minute} other {# minutes}} to read.',
    announceSelection: '{count, plural, one {# word} other {# words}} selected.',
    empty: 'No words yet.',
  },
  checklist: {
    checkAll: 'Check all items',
    uncheckAll: 'Uncheck all items',
    keep: 'Keep finished items in place',
    bottom: 'Move finished items to the bottom',
    hide: 'Hide finished items',
    toggleCount: 'Show done count',
    commandKeywords: 'checklist check all uncheck finished done tasks to do',
    count: '{done} of {total} done',
    hidden: '{count, plural, one {# finished item hidden} other {# finished items hidden}}',
    show: 'Show',
    hideAgain: 'Hide',
    notInList: 'Put the caret in a checklist first.',
    checkedAll: 'All items checked.',
    uncheckedAll: 'All items unchecked.',
    modeKeep: 'Finished items stay in place.',
    modeBottom: 'Finished items move to the bottom.',
    modeHide: 'Finished items are hidden.',
  },
  caret: {
    title: 'Caret',
    windows: 'Follow the Windows text cursor settings',
    windowsHelp: 'Width and blinking come from Settings, then Accessibility, then Text cursor, in Windows.',
    width: 'Caret width',
    widthHelp: '1 to 6 pixels.',
    steady: 'Keep the caret steady',
    steadyHelp: 'A steady caret does not blink.',
  },
  typewriter: {
    title: 'Typewriter scrolling',
    on: 'Keep the line you type at one height',
    help: 'The page moves under the caret as you type. It jumps instead of gliding when Windows animation is off.',
    at: 'Height of the line',
    atHelp: 'As a percentage of the page, from the top. 50 is the middle.',
    command: 'Turn typewriter scrolling on or off',
    commandKeywords: 'typewriter scrolling center caret line focus',
  },
  pasteSize: {
    title: 'Pasted screenshots and images',
    actual: 'Actual size',
    fit: 'Fit to the column',
    ask: 'Ask each time',
    help: 'Actual size follows the scaling of this display, so a screenshot looks as it did on screen.',
    askMessage: 'Pasted at the width of the column.',
    useActual: 'Use actual size',
  },
  linkTitles: {
    title: 'Link titles',
    on: 'Show the page title when I paste a web address',
    help: 'This asks the site for its page title. The site sees this PC’s network address and the request, and nothing else. It never runs while Work offline is on, and never for addresses on your own network.',
    privacyTitle: 'Link titles on paste',
    privacyDetail:
      'Asks a site for its page title when you paste its address, only if you turned this on in Settings, then Editing.',
    privacyNever: 'Not turned on',
    privacyOn: 'Turned on',
  },
  settings: {
    title: 'Page extras',
    doneCount: 'Show the done count beside checklists',
    wordCount: 'Show the word count under the page',
    seriesCarry: 'Carry unfinished checkboxes into the next page of a series',
  },
  find: {
    openFind: 'Find on page',
    openReplace: 'Find and replace on page',
    keywords: 'find replace search text page',
    next: 'Find next',
    previous: 'Find previous',
    label: 'Find',
    replaceLabel: 'Replace with',
    matchCase: 'Match case',
    wholeWord: 'Whole word',
    replaceOne: 'Replace',
    replaceAll: 'Replace all',
    close: 'Close',
    bar: 'Find on page',
    none: 'No matches',
    count: '{index} of {total}',
    total: '{count, plural, one {# match} other {# matches}}',
    replaced: '{count, plural, one {Replaced # match.} other {Replaced # matches.}}',
    readOnly: 'The page is read-only.',
  },
  templates: {
    newPage: 'New page from template',
    insertCommand: 'Insert template',
    saveCommand: 'Use this page as a template',
    removeCommand: 'Stop using this page as a template',
    defaultCommand: 'Set the default template for this section',
    keywords: 'template page new insert default section reuse',
    newPageTitle: 'New page from template',
    newPageDescription: 'The new page starts with the template’s text, tables, and checklists.',
    create: 'Create page',
    insertTitle: 'Insert template',
    insertDescription: 'The template goes in after the text you are writing.',
    insert: 'Insert',
    inserted: 'Template inserted.',
    notInserted: 'Nothing was inserted.',
    defaultTitle: 'Default template',
    defaultDescription: 'New pages in this section start from this template.',
    setDefault: 'Set default',
    defaultSet: 'New pages in this section start from the template.',
    defaultCleared: 'New pages in this section start empty.',
    noTemplate: 'No template',
    saved: 'This page is now a template.',
    removed: 'This page is no longer a template.',
    none: 'No templates yet. Open a page and choose Use this page as a template.',
    untitled: 'Untitled page',
  },
  series: {
    command: 'New page in series',
    keywords: 'series next page daily weekly meeting repeat copy structure',
    before: 'Before:',
    next: 'Next:',
    untitled: 'Series',
    carry: 'Carry unfinished checkboxes forward in a new page in a series',
  },
  extract: {
    command: 'Extract selection to a new page',
    keywords: 'extract move selection new page link split out',
    nothingSelected: 'Select some text first.',
    untitled: 'Extracted text',
    done: 'Moved the text to “{title}” and left a link.',
  },
  merge: {
    command: 'Merge pages',
    keywords: 'merge join combine pages headings',
    dialogTitle: 'Merge pages',
    dialogDescription: 'Pick the pages in this section to join into a new page. Each title becomes a heading.',
    action: '{count, plural, one {Merge # page} other {Merge # pages}}',
    title: '{first} and {count, plural, one {# more} other {# more}}',
    done: 'Joined {count} pages into a new page.',
  },
  split: {
    command: 'Split page at headings',
    keywords: 'split page headings sections separate pages',
    none: 'This page has no headings to split at.',
    untitled: 'Untitled section',
    done: '{count, plural, one {Made # page from a heading.} other {Made # pages from headings.}}',
    doneSkipped:
      '{count, plural, one {Made # page from a heading.} other {Made # pages from headings.}} {skipped, plural, one {# image or drawing stays on this page.} other {# images and drawings stay on this page.}}',
  },
  embed: {
    loading: 'Loading the embedded page.',
    failed: 'The embedded page couldn’t be opened.',
    missing: 'No page called “{title}”.',
    self: 'A page can’t embed itself.',
    ambiguous: 'Several pages have this name; showing the first.',
    headingMissing: 'That heading isn’t on the page any more; showing the page.',
    empty: 'Nothing to show here yet.',
    open: 'Open',
    label: 'Embedded page: {title}',
  },
  source: {
    command: 'Show page as Markdown',
    keywords: 'markdown source text raw view edit syntax',
    label: 'Markdown source of the page',
    hint: 'Markdown source. Images and other objects are comment lines; leave them where they are.',
    back: 'Back to the page',
    on: 'Showing the Markdown source.',
    off: 'Back on the page.',
  },
  attach: {
    command: 'Attach file',
    keywords: 'attach file document word excel powerpoint pdf insert',
    openCommand: 'Open attachment',
    displayCommand: 'Show attachment as icon or preview',
    menu: 'Attachment',
    open: 'Open',
    label: 'Attachment: {name}, {size}',
    missing: 'Attachment, file missing',
    opened: 'Opened {name}. Changes you save there come back into this page.',
    saved: 'Saved the changes from the other app.',
    added: '{count, plural, one {Attached # file.} other {Attached # files.}}',
    linkAdded: 'Added a link.',
    tooLarge:
      '{count, plural, one {# file is over 200 MB and can’t be attached.} other {# files are over 200 MB and can’t be attached.}}',
    failed: '{count, plural, one {# file couldn’t be attached.} other {# files couldn’t be attached.}}',
    blocked: 'Windows would run this file instead of opening it, so a note won’t open it.',
    noApp: 'Windows has no app set up to open this kind of file.',
    desktopOnly: 'Opening an attachment in its own app needs the desktop app.',
    openFailed: 'The attachment couldn’t be opened.',
  },
  wrap: {
    menu: 'Text wrap',
    command: 'Wrap text around image',
    keywords: 'text wrap image left right in line alone float',
    alone: 'Stand alone',
    inline: 'In line',
    left: 'Image on the left, text wraps',
    right: 'Image on the right, text wraps',
    gapHandle: 'Space between image and text',
    set: '{mode}.',
  },
  altDraft: {
    button: 'Use text from the image',
    help: 'Reads the words in the image on this device and adds them as a draft to edit.',
  },
  toc: {
    command: 'Show or hide the table of contents',
    commandKeywords: 'table of contents headings outline navigate jump',
    title: 'Contents',
    label: 'Table of contents',
    empty: 'No headings yet. Make a heading with Ctrl+Alt+1.',
    jumped: 'Moved to {title}.',
    close: 'Close contents',
  },
} as const;
