// Settings, then App permissions: the local API, the apps connected to it, what each may do, the access log, the
// questions OpenNote asks before an app connects or changes notes, and outgoing webhooks (docs/help/local-api.md).
// Calm and plain (BRAND.md): nothing here hurries the person, and every question has a clear No.

export const platformApi = {
  section: 'App permissions',
  intro:
    'Programs on this PC, such as the opennote command, an AI assistant, or the web clipper, ' +
    'can read or add notes only as far as you allow here.',
  enable: 'Let apps on this PC connect',
  enableNote: 'OpenNote listens only on this PC, never on the network. Turning this off stops every app at once.',
  running: 'Apps on this PC can connect.',
  stopped: 'No app can connect right now.',
  unavailable: 'The local API is not part of this build.',
  apps: {
    heading: 'Connected apps',
    empty: 'No apps are connected. When an app asks to connect, OpenNote asks you first.',
    kind: {
      app: 'App or script',
      cli: 'opennote command',
      assistant: 'AI assistant',
      clipper: 'Web clipper',
      mail: 'Mail add-in',
    },
    access: {
      label: 'What it can do',
      read: 'Read notes',
      readWrite: 'Read and add to notes',
      addPages: 'Add new pages only',
    },
    notebooks: {
      label: 'Notebooks',
      all: 'Every notebook',
      some: 'Only the notebooks I pick',
      none: 'No notebooks yet. Pick at least one.',
    },
    lockedNote: 'Locked sections are never shared with any app.',
    ask: 'Ask me before each change',
    lastUsed: 'Last used {date}',
    neverUsed: 'Not used yet',
    connected: 'Connected {date}',
    revoke: 'Revoke',
    revokeLabel: 'Revoke {name}',
    revokeTitle: 'Revoke {name}?',
    revokeBody: '{name} stops working with OpenNote at once. Your notes stay as they are.',
    revoked: '{name} can no longer use OpenNote.',
    saved: 'Saved.',
  },
  pair: {
    heading: 'Pair the web clipper or a mail add-in',
    help: 'Make a code, then type it into the extension or add-in. A code works once, for 10 minutes.',
    make: 'Make a pairing code',
    code: 'Pairing code: {code}',
    port: 'Port: {port}',
    expires: 'Works until {time}',
    cancel: 'Cancel the code',
    notRunning: 'Turn on Let apps on this PC connect first.',
  },
  cli: {
    heading: 'The opennote command',
    help:
      'Add pages, add to the daily note, search, export, and back up from a terminal or a ' +
      'script. Run opennote --help to see how.',
    installed: 'Installed in {folder}.',
    missing: 'The opennote command comes with OpenNote once setup has moved it into your Programs folder.',
    path: 'Add the opennote command to PATH',
    pathNote: 'So any terminal finds it. Only your own Windows account changes.',
  },
  mcp: {
    heading: 'AI assistants',
    help:
      'An assistant that speaks MCP, such as Claude Desktop, can use OpenNote through the ' +
      'opennote command. Paste this into the assistant’s MCP settings.',
    copy: 'Copy MCP config',
    copied: 'The MCP config is on the clipboard.',
    missing: 'The opennote command isn’t installed yet. Setup installs it next to OpenNote.',
  },
  log: {
    heading: 'Access log',
    help: 'Every time an app reads, adds, or is refused. The log never holds note text or keys, and stays on this PC.',
    empty: 'Nothing yet.',
    clear: 'Clear the log',
    clearTitle: 'Clear the access log?',
    clearBody: 'The list of what apps did is removed. The apps keep their access.',
    cleared: 'The access log is clear.',
    unknownApp: 'An unknown app',
    outcome: {
      allowed: 'Allowed',
      refused: 'Refused',
      failed: 'Didn’t finish',
    },
    row: 'At {time}, {name} asked for {action}: {outcome}',
    columns: {
      time: 'When',
      app: 'App',
      action: 'What',
      target: 'Where',
      outcome: 'Result',
    },
  },
  ask: {
    connectTitle: 'Let {name} connect to OpenNote?',
    connectBody: 'A program on this PC calls itself “{name}” ({kind}). Allow it only if you started it.',
    connectAllow: 'Allow',
    changeTitle: 'Allow this change?',
    changeBody: '{name} wants to {action}, in “{target}”.',
    changeOnce: 'Allow once',
    changeAlways: 'Always allow for this app',
    deny: 'Don’t allow',
    waiting: 'An app is waiting for your answer.',
    pickNotebook: 'Pick at least one notebook, or choose Every notebook.',
  },
  webhooks: {
    heading: 'Webhooks',
    help:
      'Tell a service such as Zapier or Power Automate when a page is added or changed. Only ' +
      'titles and links are sent, unless you choose to send the text too.',
    empty: 'No webhooks yet.',
    add: 'Add a webhook',
    edit: 'Edit',
    editLabel: 'Edit {name}',
    remove: 'Remove',
    removeLabel: 'Remove {name}',
    removeTitle: 'Remove {name}?',
    removeBody: 'OpenNote stops telling {name} about changes.',
    test: 'Send a test',
    testLabel: 'Send a test to {name}',
    testSent: 'The test reached {name}.',
    testFailed: 'The test didn’t reach {name}. Check the address.',
    name: 'Name',
    url: 'Address (https only)',
    secret: 'Signing secret (optional)',
    secretNote: 'Kept in Windows Credential Manager. Leave it empty to keep the one saved before.',
    secretShown:
      'OpenNote made this signing secret for the new webhook. Copy it into the service now; it isn’t shown again.',
    secretDone: 'Done',
    events: 'Send when',
    event: {
      pageCreated: 'A page is added',
      pageChanged: 'A page changes',
      tagAdded: 'A tag is added',
    },
    includeText: 'Send the page’s text too',
    enabled: 'On',
    save: 'Save',
    badUrl: 'Use a web address that starts with https://, such as https://hooks.zapier.com/…',
    noEvents: 'Pick at least one thing to send.',
    saved: 'The webhook is saved.',
    dialogTitle: 'Webhook',
  },
} as const;
