// The shell and storage quality-of-life features: selecting several rows, pins, sorting, archive, tabs, windows,
// docking, focus mode, low-power mode, backups, opening a notebook from a folder, the notebook check, quick capture,
// the Home page, shortcuts, conflicts, and the accessibility checker.
// Every interface string is a full sentence here, never joined from pieces (ARCHITECTURE.md section 19).

export const qol = {
  commands: {
    pin: 'Pin page',
    unpin: 'Unpin page',
    duplicate: 'Duplicate',
    copyTo: 'Copy to',
    sort: 'Sort',
    sortTitle: 'Sort by title',
    sortCreated: 'Sort by date created',
    sortModified: 'Sort by date modified',
    archive: 'Archive',
    unarchive: 'Restore from archive',
    showArchived: 'Show archived',
    openInTab: 'Open in new tab',
    openInWindow: 'Open in new window',
    duplicateTab: 'Duplicate tab',
    closeTab: 'Close tab',
    nextTab: 'Go to the next tab',
    previousTab: 'Go to the previous tab',
    reopenClosed: 'Reopen closed tab',
    focusMode: 'Focus mode',
    miniWindow: 'Keep on top',
    dockLeft: 'Dock to the left edge',
    dockRight: 'Dock to the right edge',
    quickNote: 'Quick note',
    home: 'Home',
    openFolder: 'Open a notebook from a folder',
    checkNotebook: 'Check notebook',
    backupNow: 'Back up now',
    createShortcut: 'Create shortcut',
    checkAccessibility: 'Check accessibility',
  },
  multi: {
    pages: '{count, plural, one {# page} other {# pages}}',
    sections: '{count, plural, one {# section} other {# sections}}',
    trashed: '{count, plural, one {Moved # item to Trash.} other {Moved # items to Trash.}}',
    moved: '{count, plural, one {Moved # item to {target}.} other {Moved # items to {target}.}}',
    colored: '{count, plural, one {Colored # section.} other {Colored # sections.}}',
    undoColor: 'Restored the colors of {items}',
    redoColor: 'Colored {items} again',
  },
  copy: {
    done: '{count, plural, one {Copied # item to {target}.} other {Copied # items to {target}.}}',
    undone: 'Took back the copy in {target}',
    redone: 'Copied to {target} again',
  },
  pin: {
    pinned: 'Pinned {title}.',
    unpinned: 'Unpinned {title}.',
    describe: 'Pinned.',
  },
  duplicate: {
    done: 'Made a copy of {title}.',
    undone: 'Took back the copy of {title}',
    redone: 'Copied {title} again',
  },
  sort: {
    already: 'The list is already in that order.',
    done: {
      title: 'Sorted by title.',
      created: 'Sorted by date created, newest first.',
      modified: 'Sorted by date modified, newest first.',
    },
  },
  archive: {
    archived: 'Archived {title}.',
    restored: 'Restored {title} from the archive.',
    undoArchive: 'Restored {title} from the archive',
    redoArchive: 'Archived {title} again',
    undoRestore: 'Archived {title} again',
    redoRestore: 'Restored {title} from the archive again',
    shown: 'Showing archived items.',
    hidden: 'Hiding archived items.',
  },
  tabs: {
    label: 'Open pages',
    untitled: 'Untitled page',
    opened: 'Opened {title} in a new tab.',
    closed: 'Closed the tab for {title}.',
    close: 'Close tab {title}',
    nothingToReopen: 'There is no closed tab to reopen.',
    reopenDetail: 'Recently closed tab',
    group: 'Recently closed',
  },
  focus: {
    on: 'Focus mode is on.',
    off: 'Focus mode is off.',
    exit: 'Exit focus mode',
  },
  mini: {
    on: 'OpenNote stays on top of other windows.',
    off: 'OpenNote no longer stays on top.',
    failed: 'OpenNote could not keep itself on top.',
  },
  dock: {
    left: 'left',
    right: 'right',
    docked: 'Docked to the {edge} edge of the screen.',
    undocked: 'Back in a regular window.',
    failed: 'OpenNote could not dock to the screen edge.',
  },
  power: {
    on: 'Low-power mode is on. Animations are reduced.',
    off: 'Low-power mode is off.',
    title: 'Low-power mode',
    auto: 'Reduce animations and background work on battery',
    nowOn: 'Low-power mode is on now.',
    nowOff: 'Low-power mode is off now.',
  },
  external: {
    changed: 'Another program changed this page. Reload it to see the change.',
    reload: 'Reload page',
    dismiss: 'Not now',
  },
  conflict: {
    banner:
      '{count, plural, one {A sync tool made a copy of this page.} other {A sync tool made # copies of this page.}}',
    compare: 'Compare versions',
    title: 'Two versions of this page',
    explain: 'Nothing was overwritten. Choose the version to keep, or keep both as separate pages.',
    more: '{count, plural, one {Another copy waits after this one.} other {# more copies wait after this one.}}',
    mine: 'This version',
    theirs: 'From {device}, saved {date}',
    otherDevice: 'another device',
    keepMine: 'Keep this version',
    keepTheirs: 'Keep the other version',
    keepBoth: 'Keep both',
    loading: 'Loading both versions.',
    unreadable: 'The other version could not be read.',
    failed: 'The page could not be updated.',
    done: {
      keepMine: 'Kept this version.',
      keepTheirs: 'Kept the other version.',
      keepBoth: 'Kept both as separate pages.',
    },
  },
  cloud: {
    title: 'This notes folder is in {service}',
    explain:
      '{service} can keep files only in the cloud. OpenNote waits for each file to download, so a page never looks empty.',
    conflicts:
      'If {service} makes a conflict copy of a page, OpenNote shows a banner and a side-by-side view, not a duplicate page.',
    keep: 'Always keep on this device',
    kept: 'This folder stays on this device',
    keepFailed: 'The folder could not be kept on this device.',
    manual: 'To keep this folder on this device, turn on offline access for it in {service}.',
  },
  open: {
    title: 'Open a notebook from a folder',
    body: 'Open a notebook from another drive, a USB stick, a network share, or a Git folder. It opens where it is, with no copy.',
    button: 'Choose a folder',
    missing: 'That folder is not there.',
    convertTitle: 'Turn {title} into a notebook?',
    convertBody:
      'This folder is not a notebook yet. OpenNote will add its notebook files to the folder and leave everything else as it is.',
    convert: 'Make notebook',
    opened: 'Opened {title}.',
    failed: 'The folder could not be opened as a notebook.',
    lostTitle: 'Notebooks that cannot be found',
    lostBody: '{title} was in {path}. Plug in the drive, or point OpenNote to the folder.',
    locate: 'Locate {title}',
    notThere: 'That folder is not this notebook.',
  },
  backup: {
    title: 'Backups',
    body: 'OpenNote copies changed files from your notebooks to a folder you pick, such as a USB drive. Protected sections stay encrypted.',
    enable: 'Back up on a schedule',
    noFolder: 'No backup folder chosen.',
    choose: 'Choose backup folder',
    now: 'Back up now',
    every: 'How often',
    schedule: {
      h1: 'Every hour',
      h6: 'Every 6 hours',
      h24: 'Every day',
      h168: 'Every week',
    },
    daily: 'Daily copies to keep',
    weekly: 'Weekly copies to keep',
    monthly: 'Monthly copies to keep',
    never: 'No backup has run yet.',
    restore: 'To bring pages back, open a backup folder as a notebook. It opens read-only, so you can copy pages out.',
    last: '{count, plural, one {Last backup: {when}, 1 notebook.} other {Last backup: {when}, # notebooks.}}',
    lastFailed: 'The last backup, on {when}, did not finish.',
    done: 'The backup finished.',
    failed: 'The backup could not run.',
  },
  check: {
    title: 'Check notebook',
    body: 'Look for damaged files, missing images and recordings, and tree problems. Nothing changes until you pick a repair.',
    run: 'Check {title}',
    dialogTitle: 'Check {title}',
    checking: 'Checking {title}.',
    failed: 'The notebook could not be checked.',
    clean: 'No problems found in {count, plural, one {# file} other {# files}}.',
    found: '{count, plural, one {Found # problem.} other {Found # problems.}}',
    again: 'Check again',
    rebuildIndex: 'Rebuild search index',
    rebuilt: 'The search index is rebuilding.',
    rebuildFailed: 'The search index could not be rebuilt.',
    rescanned: 'The notebook was scanned again.',
    rescanFailed: 'The notebook could not be scanned again.',
    fixRescan: 'Scan the notebook again',
    fixHistory: 'Open the page to restore it from its history',
    fixBackup: 'Restore this file from a backup.',
    categories: {
      damaged: 'A file is damaged.',
      missing: 'An image, recording, or other file is missing.',
      tree: 'The list of sections or pages does not match the folders.',
      other: 'A file has a problem.',
    },
  },
  portable: {
    title: 'Run from a USB drive',
    body: 'To keep settings and caches beside the program, add an empty file named portable next to it. Nothing goes in your profile.',
  },
  capture: {
    label: 'Quick note',
    placeholder: 'Type a note. The first line is the title.',
    help: 'Press Ctrl+Enter to save it in Quick notes, or Escape to close.',
    failed: 'The note could not be saved. Your text is still here.',
    save: 'Save note',
    settingsTitle: 'Quick capture',
    settingsBody: 'A shortcut that opens a small note window from anywhere in Windows.',
    enable: 'Turn on the quick capture shortcut',
    keys: 'Shortcut',
    keysHelp: 'Use Ctrl, Alt, or the Windows key with a letter, digit, or F key, such as Win+Shift+Q.',
    keysInvalid: 'That shortcut cannot be used.',
    keysAltGr:
      'Ctrl+Alt with a letter or digit is also AltGr, which types characters such as @ on many keyboards. Add the Windows key, or pick other keys.',
    keysClash: 'OpenNote uses these keys for {commands}. Inside OpenNote they will open quick capture instead.',
    taken: 'Another program is using these keys, so the shortcut is off. Pick other keys.',
  },
  modes: {
    title: 'Window',
    mini: 'Keep OpenNote on top of other windows',
    dockLeft: 'Dock to the left edge',
    dockRight: 'Dock to the right edge',
    undock: 'Undock',
  },
  home: {
    title: 'Home',
    customize: 'Customize',
    done: 'Done',
    hide: 'Hide',
    moveUp: 'Move up',
    moveDown: 'Move down',
    hiddenTitle: 'Hidden sections',
    show: 'Show {section}',
    opened: 'Home.',
    sections: {
      recent: 'Recent pages',
      pinned: 'Pinned pages',
      today: 'Today',
      saved: 'Saved searches',
      upcoming: 'Upcoming',
    },
    recentNone: 'Pages you open appear here.',
    pinnedNone: 'Pin a page from its menu to keep it here.',
    todayNone: 'There is no note for {date} yet.',
    todayStart: 'Start today note',
    savedNone: 'Searches you save in the search panel appear here.',
    upcomingOpen: 'Open Upcoming',
    upcomingNone: 'Upcoming is not available.',
    settingsTitle: 'Start page',
    startOnHome: 'Start on Home',
    startHelp: 'When this is off, OpenNote opens the last page you used.',
  },
  shortcut: {
    made: 'Made a shortcut to {title} on the desktop.',
    failed: 'The shortcut could not be made.',
    empty: '{title} has no pages to open.',
  },
  settings: {
    storage: 'Storage and backups',
    windows: 'Windows and power',
  },
  setup: {
    title: 'Keys and pen',
    subtitle: 'Choose the shortcuts you know. You can change this in Settings.',
    onenoteClash:
      'Where the sets clash, this set keeps the meaning OneNote gives a key. The shortcut list shows where the other command went.',
    penTitle: 'Pen top button',
    penBody:
      'To open a quick note with the top button of your pen, choose OpenNote for the pen shortcut in Windows pen settings.',
    penOpen: 'Open pen settings',
    penOpened: 'Pen settings opened',
  },
  a11y: {
    title: 'Check accessibility',
    checking: 'Checking for problems.',
    none: 'No accessibility problems found.',
    summary: '{count, plural, one {Found # problem.} other {Found # problems.}}',
    altLabel: 'Description of the image',
    altApply: 'Add description',
    decorative: 'Mark as decorative',
    fixFailed: 'The fix could not be applied.',
    issues: {
      imageAlt: 'An image has no description for screen readers.',
      headingSkip: 'A heading jumps from level {from} to level {to}.',
      tableHeader: 'A table has no header row.',
      lowContrast: 'Text in the color {color} is hard to read, with a contrast of {ratio} to 1.',
      colorOnly: 'Text uses {count} colors, and color may be the only sign of its meaning.',
      readingOrder: 'A free-form page with {count} objects has no reading order.',
    },
    fixes: {
      imageAlt: 'Add description',
      headingSkip: 'Use the next heading level',
      tableHeader: 'Make the first row a header',
      lowContrast: 'Use the normal text color',
      colorOnly: 'Also make the colored text bold',
      readingOrder: 'Set the order from top to bottom',
    },
  },
} as const;
