// Beta 4 additions to search and linking: line tags, links to paragraphs, the daily note, page properties,
// collections, the graph, the canvas, replace, and text read from media. One namespace file for the lane.
// Every string is a full sentence, never joined from pieces (ARCHITECTURE.md section 19).

export const qolSearch = {
  commands: {
    copyPageLink: 'Copy link to this page',
    copyParagraphLink: 'Copy link to this paragraph',
    tagsPane: 'Show tagged lines',
    tagLine: 'Tag this line',
    replace: 'Replace in all notebooks',
    dailyOpen: "Open today's note",
    dailyCalendar: 'Open the daily notes calendar',
    tag: {
      todo: 'Tag as To do',
      important: 'Tag as Important',
      question: 'Tag as Question',
      idea: 'Tag as Idea',
      remember: 'Tag as Remember for later',
      definition: 'Tag as Definition',
      highlight: 'Tag as Highlight',
      contact: 'Tag as Contact',
      phone: 'Tag as Phone number',
    },
    keywords: {
      copyPageLink: 'share url opennote address paste outlook word teams',
      copyParagraphLink: 'share url heading block anchor reference',
      tagsPane: 'tag summary to do checkboxes important question idea collect',
      tag: 'line tag label icon checkbox onenote',
      daily: 'journal today diary weekly monthly yearly calendar template',
      replace: 'find and replace substitute change words everywhere',
    },
  },
  tagsPane: {
    title: 'Tagged lines',
    description: 'Lines you tagged and boxes still open, from the page, the section, or the notebooks.',
    lookIn: 'Look in',
    groupBy: 'Group by',
    scopes: { page: 'This page', section: 'This section', notebook: 'This notebook', all: 'All notebooks' },
    groups: { tag: 'Tag', page: 'Page', date: 'Date' },
    openBoxes: 'Open checkboxes',
    count: '{count, plural, one {# line} other {# lines}}',
    loading: 'Reading your pages.',
    none: 'No tagged lines or open boxes here. Use Tag this line, or Ctrl+1 in the OneNote shortcut set.',
    noPlace: 'Open a page to look in its section or notebook.',
    boxLabel: 'Done: {text}',
    emptyLine: 'Empty line',
    go: 'Open page',
    checked: 'Checked off: {text}',
    reopened: 'Opened again: {text}',
    checkFailed: 'The box could not be changed.',
    createSummary: 'Create summary page',
    summaryTitle: 'Tag summary {date}',
    summaryMade: 'Saved as the page {title}.',
    summaryFailed: 'The summary page could not be made.',
  },
  media: {
    image: 'In a picture:',
    ink: 'In a drawing or handwriting:',
  },
  replace: {
    open: 'Replace…',
    title: 'Replace',
    description: 'Find words in every notebook and replace them. Nothing changes until you press Replace.',
    find: 'Find',
    with: 'Replace with',
    matchCase: 'Match case',
    wholeWord: 'Whole words',
    start: 'Type the words to find.',
    none: 'No page holds those words.',
    summary: '{count, plural, one {# change} other {# changes}} on {pages, plural, one {# page} other {# pages}}.',
    truncated: 'Showing the first {count} pages.',
    page: '{title}, {count, plural, one {# match} other {# matches}}',
    keep: 'Replace this match on {title}',
    run: '{count, plural, =0 {Replace} one {Replace # match} other {Replace # matches}}',
    done: 'Replaced {count, plural, one {# match} other {# matches}} on {pages, plural, one {# page} other {# pages}}.',
    undo: 'Undo',
    undone: 'Put back {count, plural, one {# change} other {# changes}}.',
    unchangedTitle: 'Not changed',
    unchanged:
      '{count, plural, one {# more place holds} other {# more places hold}} these words in recognized handwriting or in a picture. They stay as drawn.',
  },
  daily: {
    sectionTitle: 'Daily notes',
    title: 'Daily notes',
    description: 'Pick a day to open its note. A day with pages shows a dot and how many.',
    previous: 'Previous',
    next: 'Next',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    today: 'Today',
    pages: '{count, plural, one {# page} other {# pages}}',
    openDay: 'Open {title}',
    openWeek: 'Open week {title}',
    openMonth: 'Open month {title}',
    openYear: 'Open year {title}',
    templates: 'Templates',
    templateFor: 'Template for',
    kinds: { day: 'Day', week: 'Week', month: 'Month', year: 'Year' },
    templateHelp: 'The Markdown a new note starts with. Placeholders: {placeholders}.',
    saveTemplate: 'Save template',
    resetTemplate: 'Use the standard template',
    templateSaved: 'Template saved.',
    noNotebook: 'Open a notebook first, and the note will go in its Daily notes section.',
    failed: 'The note could not be opened.',
  },
  links: {
    copied: 'Link copied.',
    copyFailed: 'The link could not be copied.',
    gone: 'That page is no longer in your notebooks.',
  },
  lineTags: {
    names: {
      todo: 'To do',
      important: 'Important',
      question: 'Question',
      idea: 'Idea',
      remember: 'Remember for later',
      definition: 'Definition',
      highlight: 'Highlight',
      contact: 'Contact',
      phone: 'Phone number',
    },
    todoBox: 'To do, check off when done',
    chipLabel: 'Tag: {tag}',
    custom: 'Custom tag',
    menu: 'Tag this line',
    customTitle: 'Custom tag',
    customDescription: 'Name a tag for the lines you have selected. Use a slash to nest tags, such as school/biology.',
    customName: 'Tag name',
    customAdd: 'Add tag',
  },
} as const;
