// Beta 4 additions to search and linking: line tags, links to paragraphs, the daily note, page properties,
// collections, the graph, the canvas, replace, and text read from media. One namespace file for the lane.
// Every string is a full sentence, never joined from pieces (ARCHITECTURE.md section 19).

export const qolSearch = {
  commands: {
    copyPageLink: 'Copy link to this page',
    copyParagraphLink: 'Copy link to this paragraph',
    tagsPane: 'Show tagged lines',
    tagLine: 'Tag this line',
    replace: 'Replace in all notebooks',
    collections: 'Open collections',
    graph: 'Open the graph view',
    canvas: 'Open the canvas',
    dailyOpen: "Open today's note",
    dailyCalendar: 'Open the daily notes calendar',
    tag: {
      todo: 'Tag as To do',
      important: 'Tag as Important',
      question: 'Tag as Question',
      idea: 'Tag as Idea',
      remember: 'Tag as Remember for later',
      definition: 'Tag as Definition',
      highlight: 'Tag as Highlight',
      contact: 'Tag as Contact',
      phone: 'Tag as Phone number',
    },
    keywords: {
      copyPageLink: 'share url opennote address paste outlook word teams',
      copyParagraphLink: 'share url heading block anchor reference',
      tagsPane: 'tag summary to do checkboxes important question idea collect',
      tag: 'line tag label icon checkbox onenote',
      daily: 'journal today diary weekly monthly yearly calendar template',
      replace: 'find and replace substitute change words everywhere',
      collections: 'database table board gallery view saved filter properties',
      graph: 'connections links map network backlinks orphans',
      canvas: 'board cards whiteboard arrows diagram',
    },
  },
  canvas: {
    title: 'Canvas',
    description: 'Cards on an open board, joined by arrows. Drag a card, or focus it and use the arrow keys.',
    noPage: 'Open a page first. The canvas is saved with that page.',
    addKind: 'Add a card',
    add: 'Add card',
    kinds: {
      page: 'Page',
      note: 'Note',
      image: 'Image',
      pdf: 'PDF',
      web: 'Web address',
      group: 'Group',
    },
    entry: {
      page: 'Find a page',
      note: 'Note text',
      image: 'Image file name or web address',
      pdf: 'PDF file name or web address',
      web: 'Web address',
      group: 'Group name',
    },
    newNote: 'New note',
    newGroup: 'New group',
    added: 'Card added.',
    removed: 'Card removed.',
    from: 'Arrow from',
    to: 'Arrow to',
    chooseCard: 'Choose a card',
    arrowLabel: 'Arrow label',
    connect: 'Connect',
    connected: 'Arrow from {from} to {to}.',
    arrange: 'Arrange chosen cards',
    align: { row: 'Line up in a row', column: 'Line up in a column', grid: 'Arrange in a grid' },
    deleteSelected: 'Delete chosen cards',
    selected: '{count, plural, =0 {No cards chosen} one {# card chosen} other {# cards chosen}}',
    chosen: 'chosen',
    open: 'Open',
    edit: 'Edit',
    editText: 'Text of the card',
    jsonTitle: 'JSON Canvas',
    export: 'Show as JSON',
    import: 'Replace the canvas with this JSON',
    importFailed: 'That text is not a JSON Canvas.',
  },
  graph: {
    title: 'Graph',
    description: 'Pages are dots and links are lines. The Connections list below says the same in words.',
    show: 'Show',
    around: 'Pages near this page',
    notebook: 'This notebook',
    all: 'All notebooks',
    depth: 'Reach',
    links: '{count, plural, one {# link} other {# links}}',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    summary: '{pages, plural, one {# page} other {# pages}} and {links, plural, one {# link} other {# links}}.',
    cut: 'Showing the {count} best connected pages.',
    picture:
      'Graph of {pages, plural, one {# page} other {# pages}} joined by {links, plural, one {# link} other {# links}}.',
    selected: '{title} selected.',
    connections: 'Connections',
    pageLabel: 'Page',
    choose: 'Choose a page',
    open: 'Open {title}',
    outgoing: 'Links from this page, {count}',
    incoming: 'Links to this page, {count}',
    times: '{count, plural, one {# link} other {# links}}',
    unlinked: 'Pages with no links, {count}',
  },
  collections: {
    title: 'Collections',
    description: 'Saved views of pages chosen by words, a tag, a section, or property values.',
    pick: 'Collection',
    new: 'New collection',
    newName: 'Collection {number}',
    rules: 'Rules',
    delete: 'Delete collection',
    empty: 'No collections yet. Make one, then choose which pages it holds.',
    name: 'Name',
    text: 'Pages that contain these words',
    tag: 'Tag',
    section: 'Section',
    any: 'Any',
    property: 'Property',
    operator: 'Is',
    value: 'Value',
    operators: {
      is: 'equal to',
      isNot: 'not equal to',
      contains: 'containing',
      empty: 'empty',
      notEmpty: 'not empty',
      before: 'before',
      after: 'after',
      atLeast: 'at least',
      atMost: 'at most',
    },
    addRule: 'Add a rule',
    removeRule: 'Remove rule',
    groupBy: 'Group by',
    groupDate: 'Group dates by',
    dateGroups: { day: 'Day', week: 'Week', month: 'Month' },
    dateField: 'Date for the calendar',
    showAs: 'Show as',
    views: { table: 'Table', list: 'List', board: 'Board', calendar: 'Calendar', gallery: 'Gallery' },
    loading: 'Reading your pages.',
    nothing: 'No page matches these rules.',
    pages: '{count, plural, one {# page} other {# pages}}',
    count: '{count, plural, one {# page} other {# pages}}',
    pageTitle: 'Page',
    noValue: 'No value',
    yes: 'Yes',
    no: 'No',
    cellLabel: '{name} of {title}',
    moveTo: 'Move {title} to',
    byDate: 'by {name}',
    boardNeedsGroup: 'Choose a property to group by, and its values become the columns of the board.',
    calendarNeedsDate: 'Choose a date property for the calendar, or add a date field to a page.',
    editFailed: 'The page could not be changed.',
  },
  properties: {
    title: 'Properties',
    count: '{count, plural, =0 {none} one {# field} other {# fields}}',
    empty: 'No properties yet. Add a field such as a status, a due date, or a link to another page.',
    none: 'None',
    type: 'Type of field',
    add: 'Add property',
    remove: 'Remove {name}',
    removeShort: 'Remove',
    nameOf: 'Name of this {type} field',
    optionsOf: 'Choices for {name}',
    optionsHint: 'Choices, separated by commas',
    firstChoice: 'Open',
    pages: 'Pages to link to',
    types: {
      text: 'Text',
      number: 'Number',
      date: 'Date',
      checkbox: 'Checkbox',
      choice: 'Choice',
      page: 'Page link',
    },
  },
  tagsPane: {
    title: 'Tagged lines',
    description: 'Lines you tagged and boxes still open, from the page, the section, or the notebooks.',
    lookIn: 'Look in',
    groupBy: 'Group by',
    scopes: { page: 'This page', section: 'This section', notebook: 'This notebook', all: 'All notebooks' },
    groups: { tag: 'Tag', page: 'Page', date: 'Date' },
    openBoxes: 'Open checkboxes',
    count: '{count, plural, one {# line} other {# lines}}',
    loading: 'Reading your pages.',
    none: 'No tagged lines or open boxes here. Use Tag this line, or Ctrl+1 in the OneNote shortcut set.',
    noPlace: 'Open a page to look in its section or notebook.',
    boxLabel: 'Done: {text}',
    emptyLine: 'Empty line',
    go: 'Open page',
    checked: 'Checked off: {text}',
    reopened: 'Opened again: {text}',
    checkFailed: 'The box could not be changed.',
    createSummary: 'Create summary page',
    summaryTitle: 'Tag summary {date}',
    summaryMade: 'Saved as the page {title}.',
    summaryFailed: 'The summary page could not be made.',
  },
  media: {
    image: 'In a picture:',
    ink: 'In a drawing or handwriting:',
  },
  replace: {
    open: 'Replace…',
    title: 'Replace',
    description: 'Find words in every notebook and replace them. Nothing changes until you press Replace.',
    find: 'Find',
    with: 'Replace with',
    matchCase: 'Match case',
    wholeWord: 'Whole words',
    start: 'Type the words to find.',
    none: 'No page holds those words.',
    summary: '{count, plural, one {# change} other {# changes}} on {pages, plural, one {# page} other {# pages}}.',
    truncated: 'Showing the first {count} pages.',
    page: '{title}, {count, plural, one {# match} other {# matches}}',
    keep: 'Replace this match on {title}',
    run: 'Replace {count, plural, one {# match} other {# matches}}',
    done: 'Replaced {count, plural, one {# match} other {# matches}} on {pages, plural, one {# page} other {# pages}}.',
    undo: 'Undo',
    undone: 'Put back {count, plural, one {# change} other {# changes}}.',
    unchangedTitle: 'Not changed',
    unchanged:
      // checks-disable-next-line length: one sentence kept whole, because t() reads its parameters from the literal
      '{count, plural, one {# more place holds} other {# more places hold}} these words in recognized handwriting or in a picture. They stay as drawn.',
  },
  daily: {
    sectionTitle: 'Daily notes',
    title: 'Daily notes',
    description: 'Pick a day to open its note. A day with pages shows a dot and how many.',
    previous: 'Previous',
    next: 'Next',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    today: 'Today',
    pages: '{count, plural, one {# page} other {# pages}}',
    openDay: 'Open {title}',
    openWeek: 'Open week {title}',
    openMonth: 'Open month {title}',
    openYear: 'Open year {title}',
    templates: 'Templates',
    templateFor: 'Template for',
    kinds: { day: 'Day', week: 'Week', month: 'Month', year: 'Year' },
    templateHelp: 'The Markdown a new note starts with. Placeholders: {placeholders}.',
    saveTemplate: 'Save template',
    resetTemplate: 'Use the standard template',
    templateSaved: 'Template saved.',
    noNotebook: 'Open a notebook first, and the note will go in its Daily notes section.',
    failed: 'The note could not be opened.',
  },
  links: {
    copied: 'Link copied.',
    copyFailed: 'The link could not be copied.',
    gone: 'That page is no longer in your notebooks.',
  },
  lineTags: {
    names: {
      todo: 'To do',
      important: 'Important',
      question: 'Question',
      idea: 'Idea',
      remember: 'Remember for later',
      definition: 'Definition',
      highlight: 'Highlight',
      contact: 'Contact',
      phone: 'Phone number',
    },
    todoBox: 'To do, check off when done',
    chipLabel: 'Tag: {tag}',
    custom: 'Custom tag',
    menu: 'Tag this line',
    customTitle: 'Custom tag',
    customDescription: 'Name a tag for the lines you have selected. Use a slash to nest tags, such as school/biology.',
    customName: 'Tag name',
    customAdd: 'Add tag',
  },
} as const;
