// Search and linking: the search panel, [[page links]], the linked pages pane, and tags (Phase 8).
// Every string is a full sentence, never joined from pieces (ARCHITECTURE.md section 19).

export const search = {
  commands: {
    open: 'Search notes',
    linkedPages: 'Show linked pages',
    manageTags: 'Manage tags',
    insertLink: 'Link to a page',
    followLink: 'Open the linked page',
    previewLink: 'Preview the linked page',
    rebuild: 'Rebuild the search index',
    keywords: {
      open: 'find text full-text look up everywhere query filter',
      linkedPages: 'backlinks references mentions links pane',
      manageTags: 'rename merge delete tags',
      insertLink: 'wiki double brackets page link',
      followLink: 'follow go to link',
      previewLink: 'hover peek link card',
      rebuild: 'reindex repair search damaged',
    },
  },
  groups: {
    matches: 'Found in text',
  },
  panel: {
    title: 'Search',
    description: 'Find words in every page. Press Enter to open the highlighted page.',
    input: 'Search notes',
    placeholder: 'Search words, "phrases", tag:name, title:word',
    // checks-disable-next-line length: one sentence kept whole, because t() reads its parameters from the literal
    help: 'Words must all match. Use "quotes" for a phrase, OR for either word, a minus sign to leave a word out, tag:name, title:word, type:table, and after:7d.',
    filters: 'Filters',
    regex: 'Regular expression',
    titleOnly: 'Titles only',
    tag: 'Tag',
    anyTag: 'Any tag',
    date: 'Changed',
    dates: {
      any: 'Any time',
      today: 'Today',
      week: 'In the last 7 days',
      month: 'In the last 30 days',
    },
    type: 'Look in',
    types: {
      all: 'Everything',
      text: 'Text',
      table: 'Tables',
      image: 'Images',
      ink: 'Handwriting',
    },
    saved: 'Saved searches',
    savedPick: 'Choose a saved search',
    save: 'Save this search',
    saveName: 'Name for this search',
    saveConfirm: 'Save',
    savedAs: 'Saved the search as "{name}".',
    forget: 'Delete saved search',
    results: 'Results',
    count: '{count, plural, =0 {No results} one {# result} other {# results}}',
    none: 'No pages match.',
    failed: "Couldn't search. Try again in a moment.",
    partial: 'The search stopped early. These are the best matches from what it read.',
    preview: 'Preview',
    previewEmpty: 'Select a result to preview it.',
    changed: 'Changed {date}',
  },
  rename: {
    title: 'Update links to the renamed page?',
    // checks-disable-next-line length: one sentence kept whole, because t() reads its parameters from the literal
    body: 'You renamed "{oldTitle}" to "{newTitle}". {links, plural, one {# link} other {# links}} to it will change, on {pages, plural, one {# other page} other {# other pages}}.',
    confirm: 'Update links',
    keep: 'Keep the old links',
    done: 'Updated {links, plural, one {# link} other {# links}} on {pages, plural, one {# page} other {# pages}}.',
    nothing: 'No links needed updating.',
  },
  links: {
    status: {
      resolved: 'Links to a page. Ctrl+click to open it.',
      ambiguous: 'Several pages have this title. Ctrl+click opens the closest.',
      renamed: 'The page has a new title. Ctrl+click opens it.',
      broken: 'No page has this title. Ctrl+click to make it.',
    },
    suggestions: 'Pages to link',
    suggestionCount: '{count, plural, one {# page} other {# pages}} to link. Use the arrow keys, then Enter.',
    cardLabel: 'Preview of {title}',
    emptyPage: 'This page is empty.',
    headingMissing: 'The page has no heading "{heading}", so this shows the start of the page.',
    open: 'Open page',
    broken: 'No page is titled "{title}".',
    create: 'Make the page',
    created: 'Made the page "{title}".',
    createFailed: 'Couldn\'t make the page "{title}". Open a section first, then try again.',
  },
  backlinks: {
    title: 'Linked pages',
    loading: 'Looking for links…',
    noPage: 'Open a page to see the pages that link to it.',
    linksHeading: '{count, plural, =0 {Pages that link here} one {# page links here} other {# pages link here}}',
    none: 'No page links here yet. Type [[ in a page to link to this one.',
    stale: 'Uses an earlier title of this page.',
    update: 'Update links to the new title',
    mentionsHeading:
      '{count, plural, =0 {Pages that mention this title} one {# page mentions this title} other {# pages mention this title}}',
    noMentions: 'No page says this title without linking to it.',
    mentionCount: '{count, plural, one {# mention} other {# mentions}}',
    link: 'Link',
    linkLabel: 'Link the mentions on {title}',
    linked: 'Linked {count, plural, one {# mention} other {# mentions}} on "{title}".',
    failed: "Couldn't change the links. Try again.",
  },
  tags: {
    title: 'Tags',
    description: 'Rename a tag to change it on every page, or give it a name that exists to merge the two.',
    loading: 'Loading tags…',
    addLabel: 'Add a tag to the open page',
    add: 'Add tag',
    added: 'Added the tag {tag} to this page.',
    has: 'This page has the tag {tag} already.',
    noPage: 'Open a page to add a tag to it.',
    none: 'No page has a tag yet. Open a page and add one here.',
    list: 'Tags',
    pages: '{count, plural, one {# page} other {# pages}}',
    rename: 'Rename',
    renameLabel: 'Rename the tag {tag}',
    merge: 'Merge',
    delete: 'Delete',
    deleteLabel: 'Delete the tag {tag}',
    newName: 'New name for {tag}',
    nothing: 'No page carries {tag}.',
    renamePlan: 'Renaming {from} to {to} changes {count, plural, one {# page} other {# pages}}.',
    mergePlan: '{to} exists, so {from} merges into it on {count, plural, one {# page} other {# pages}}.',
    deletePlan: 'Deleting {tag} takes the hash off its words on {count, plural, one {# page} other {# pages}}.',
    done: 'Changed tags on {count, plural, one {# page} other {# pages}}.',
    failed: "Couldn't change the tags. Try again.",
  },
  index: {
    rebuilding: 'Rebuilding the search index. Search works as it fills.',
    rebuilt: 'The search index is up to date.',
  },
} as const;
