// The Settings page and its General and About sections.
// Every interface string is a full sentence here, never joined from pieces (ARCHITECTURE.md section 19).

export const settings = {
  title: 'Settings',
  back: 'Back to notes',
  backToSections: 'Back to settings',
  nav: 'Settings sections',
  sections: {
    general: 'General',
    appearance: 'Appearance',
    updates: 'Updates',
    shortcuts: 'Shortcuts',
    about: 'About',
  },
  general: {
    folderTitle: 'Notes folder',
    folderNone: "You haven't chosen a notes folder yet.",
    openFolder: 'Open folder',
    openFolderFailed: "Couldn't open the notes folder.",
    appTitle: 'Where OpenNote lives',
    appDev: 'This is a development build, so it runs from the build folder.',
    appHome: 'OpenNote is in your user programs folder, so it can update itself.',
    appElsewhere: 'OpenNote runs from {path}. Move it to your user programs folder so it can update itself.',
    addToStart: 'Add OpenNote to the Start menu',
    moveFailed: "Couldn't move OpenNote. Try again, or move it yourself.",
    startupTitle: 'Start-up',
    openLastPage: 'Open the last page at start-up',
    openLastPageHelp: 'When this is off, OpenNote opens your notebooks without a page.',
  },
  about: {
    details: 'About OpenNote',
    version: 'Version',
    architecture: 'Architecture',
    channel: 'Channel',
    webview: 'WebView2 version',
    license: 'License',
    licenseValue: 'Apache License 2.0',
    logFolder: 'Open the log folder',
    logFolderFailed: "Couldn't open the log folder.",
    goBack: 'Go back to version {version}',
    goBackTitle: 'Go back to version {version}?',
    goBackBody: 'OpenNote restarts with the earlier version. Your notes and settings stay as they are.',
    goBackConfirm: 'Go back',
    goBackFailed: "Couldn't go back to the earlier version.",
    snapshot: 'Notes in this version are a preview. They stay in a temporary file until storage arrives.',
    experimental: 'Experimental features',
    experimentalHelp: "These features aren't finished. Turn one on to try it, and expect problems.",
    channels: { dev: 'Development', nightly: 'Nightly', beta: 'Beta', stable: 'Stable' },
    architectures: { x64: 'x64', x86: 'x86', arm64: 'ARM64' },
  },
} as const;
