// The keyboard shortcut list and the shortcut set choice.
// Every interface string is a full sentence here, never joined from pieces (ARCHITECTURE.md section 19).

export const shortcuts = {
  title: 'Keyboard shortcuts',
  description: 'Every command and the keys that run it.',
  filter: 'Filter shortcuts',
  filterHelp: 'Type a command name or a key, such as Ctrl+K.',
  tables: 'Shortcut tables',
  commandColumn: 'Command',
  keysColumn: 'Shortcut',
  actionsColumn: 'Actions',
  or: 'or',
  none: 'None',
  noMatch: 'No shortcuts match "{query}".',
  reset: 'Reset',
  resetLabel: 'Reset {command}',
  resetDone: 'Reset {command} to its usual shortcut.',
  resetAll: 'Reset all shortcuts',
  resetAllDone: 'All shortcuts are back to the {set} set.',
  movedTo: 'Moved from {keys}, which {command} uses in the OneNote set.',
  movedAway: 'Moved from {keys} in the default set.',
  categories: {
    general: 'General',
    navigation: 'Navigation',
    notebooks: 'Notebooks and pages',
    view: 'View',
    appearance: 'Appearance',
    updates: 'Updates',
    help: 'Help',
    editing: 'Editing',
    format: 'Format',
    insert: 'Insert',
    table: 'Tables',
    object: 'Objects',
  },
  fixed: {
    title: 'Keys that always work',
    description: "These keys can't be changed, so you can always get around with the keyboard.",
    keysColumn: 'Keys',
    actionColumn: 'What they do',
    arrows: 'Move between items, rows, and tabs.',
    startEnd: 'Go to the first or last item.',
    typeahead: 'Type the first letters to jump to an item.',
    tab: 'Move between controls.',
    enter: 'Open or choose the item.',
    regions: 'Move between the parts of the window.',
    menu: 'Open the menu for the item.',
    escape: 'Close the open menu or dialog, or return to the page.',
    windowMenu: 'Open the window menu.',
    letters: 'Letters and digits',
  },
  set: {
    label: 'Shortcut set',
    default: 'OpenNote',
    defaultHelp: 'The shortcuts OpenNote is designed around.',
    onenote: 'OneNote',
    onenoteHelp: 'Keys keep the meaning they have in OneNote, such as Ctrl+E for search.',
    changed: 'Using the {set} shortcut set.',
  },
} as const;
