// The keyboard shortcut list and the shortcut set choice.
// Every interface string is a full sentence here, never joined from pieces (ARCHITECTURE.md section 19).

export const shortcuts = {
  title: 'Keyboard shortcuts',
  description: 'Every command and the keys that run it.',
  filter: 'Filter shortcuts',
  filterHelp: 'Type a command name or a key, such as Ctrl+K.',
  tables: 'Shortcut tables',
  commandColumn: 'Command',
  keysColumn: 'Shortcut',
  actionsColumn: 'Actions',
  or: 'or',
  none: 'None',
  noMatch: 'No shortcuts match "{query}".',
  reset: 'Reset',
  resetLabel: 'Reset {command}',
  resetDone: 'Reset {command} to its usual shortcut.',
  change: 'Change',
  changeLabel: 'Change the shortcut for {command}',
  capture: {
    label: 'New shortcut for {command}',
    hint: 'Press the new shortcut. Escape cancels, and Backspace removes it.',
    unknown: "That key press can't be a shortcut. Try another one.",
    navigation: "{keys} is used to move around the app, so it can't be a shortcut.",
    windows: "{keys} belongs to Windows, so it can't be a shortcut.",
    typesText: '{keys} types text. Add Ctrl or Alt, or use a function key.',
    conflict: '{keys} is already used by {other}. Use it for {command} instead?',
    conflictMore:
      '{keys} is already used by {other} and {more, plural, one {# other command} other {# other commands}}. Use it for {command} instead?',
    useHere: 'Use it here',
    changed: 'The shortcut for {command} is now {keys}.',
    removed: '{command} has no shortcut now.',
    canceled: 'The shortcut for {command} is unchanged.',
  },
  find: {
    toggle: 'Find by shortcut',
    field: 'Shortcut to find',
    hint: 'Press a shortcut to see the command that uses it. Escape stops.',
    waiting: 'Waiting for a shortcut',
  },
  resetAll: 'Reset all shortcuts',
  resetAllDone: 'All shortcuts are back to the {set} set.',
  movedTo: 'Moved from {keys}, which {command} uses in the OneNote set.',
  movedAway: 'Moved from {keys} in the default set.',
  categories: {
    general: 'General',
    navigation: 'Navigation',
    notebooks: 'Notebooks and pages',
    view: 'View',
    appearance: 'Appearance',
    updates: 'Updates',
    help: 'Help',
    editing: 'Editing',
    format: 'Format',
    insert: 'Insert',
    table: 'Tables',
    object: 'Objects',
  },
  fixed: {
    title: 'Keys that always work',
    description: "These keys can't be changed, so you can always get around with the keyboard.",
    keysColumn: 'Keys',
    actionColumn: 'What they do',
    arrows: 'Move between items, rows, and tabs.',
    startEnd: 'Go to the first or last item.',
    typeahead: 'Type the first letters to jump to an item.',
    tab: 'Move between controls.',
    enter: 'Open or choose the item.',
    regions: 'Move between the parts of the window.',
    menu: 'Open the menu for the item.',
    escape: 'Close the open menu or dialog, or return to the page.',
    windowMenu: 'Open the window menu.',
    letters: 'Letters and digits',
  },
  set: {
    label: 'Shortcut set',
    default: 'OpenNote',
    defaultHelp: 'The shortcuts OpenNote is designed around.',
    onenote: 'OneNote',
    onenoteHelp: 'Keys keep the meaning they have in OneNote, such as Ctrl+E for search.',
    changed: 'Using the {set} shortcut set.',
  },
} as const;
