// Smart tables, charts, math, and the study tool windows (Phases 7 and 10; owner: the expression-engine lane).
// Every interface string is a full sentence here, never joined from pieces (ARCHITECTURE.md section 19).

export const smart = {
  math: {
    insertBlock: 'Insert equation',
    insertInline: 'Insert inline equation',
    keywords: 'math equation formula latex symbol',
    problem: 'LaTeX problem: {message}',
    announceInserted: 'Equation added. Type its LaTeX, then press Enter.',
    actions: 'Equation actions',
    simplify: 'Simplify',
    solve: 'Solve',
    done: 'The equation was changed. Press Enter to keep it, or Escape to put the old one back.',
    unsupported: 'This uses LaTeX the action cannot read yet.',
    unchanged: 'It is already as simple as this action can make it.',
    none: 'No solution was found between -1000 and 1000.',
    letters: 'Solve needs an equation with exactly one letter in it.',
  },
  grapher: {
    insert: 'Insert graph',
    insertKeywords: 'graph plot function curve desmos equation',
    function: 'Function {number}',
    add: 'Add a function',
    label: 'Graph of {count, plural, one {# function} other {# functions}}',
    keys: 'Arrow keys move the view. Plus and minus zoom. Zero resets. Shift with the left or right arrow reads values.',
    role: 'graph',
    parameter: 'Value of {name}',
    zoomIn: 'Zoom in',
    zoomOut: 'Zoom out',
    reset: 'Reset view',
    readout: 'x = {x}, y = {y}',
    readoutSlope: 'x = {x}, y = {y}, slope = {slope}',
    readoutNone: 'Move over the graph, or hold Shift and press the left or right arrow, to read a value.',
    announceInserted: 'Graph added. Edit its functions in the box above the plot.',
  },
  tools: {
    openTimers: 'Open timers',
    openCalculator: 'Open calculator',
    openUpcoming: 'Open upcoming',
    keywords: 'timer stopwatch pomodoro focus calculator scientific graphing upcoming due tasks study tool window',
    window: {
      close: 'Close {title}',
      keepOnTop: 'Keep on top',
      popOut: 'Open in its own window',
      move: 'Move {title}. Use the arrow keys, or drag.',
    },
    timers: {
      title: 'Timers',
      empty: 'No timers yet. Add one below.',
      add: 'Add timer',
      form: 'New timer',
      kind: 'Kind',
      kinds: { countdown: 'Countdown', stopwatch: 'Stopwatch', focus: 'Focus' },
      name: 'Name',
      defaultName: 'Timer {number}',
      minutes: 'Minutes',
      seconds: 'Seconds',
      work: 'Work minutes',
      rest: 'Break minutes',
      rounds: 'Rounds',
      start: 'Start',
      pause: 'Pause',
      resume: 'Resume',
      reset: 'Reset',
      lap: 'Lap',
      remove: 'Remove {name}',
      laps: 'Laps',
      lapEntry: 'Lap {number}: {time}',
      phaseWork: 'Work, round {cycle} of {cycles}',
      phaseBreak: 'Break after round {cycle} of {cycles}',
      status: { idle: 'Ready', running: 'Running', paused: 'Paused', done: 'Finished' },
      finished: '{name} finished.',
      tooLong: 'Choose a time of at least one second.',
    },
    calculator: {
      title: 'Calculator',
      tabs: 'Calculator modes',
      scientific: 'Scientific',
      graphing: 'Graphing',
      expression: 'Expression',
      placeholder: '2pi * 3, sin(30), 5 km to mi',
      calculate: 'Calculate',
      history: 'History',
      historyEmpty: 'Answers appear here and stay on this device.',
      clearHistory: 'Clear history',
      useEntry: 'Use {expression} again',
      angle: 'Angle unit',
      degrees: 'Degrees',
      radians: 'Radians',
      memoryStore: 'Store answer in memory',
      memoryRecall: 'Add memory to the expression',
      memoryClear: 'Clear memory',
      memoryHolds: 'Memory holds {value}.',
      memoryEmpty: 'Memory is empty.',
      copy: 'Copy answer',
      insert: 'Insert answer into page',
      answer: '= {value}',
      converted: '{input} = {value}',
      copied: 'Answer copied.',
      inserted: 'Answer added to the page.',
      keypad: 'Keys',
      errors: {
        empty: 'Type something to calculate.',
        'too-long': 'That is too long to calculate.',
        'too-deep': 'That has too many brackets inside brackets.',
        'bad-character': 'There is a character here the calculator does not know.',
        'bad-number': 'That number is not written in a form the calculator reads.',
        'unexpected-token': 'Something here is out of place.',
        'unexpected-end': 'The expression ends too soon.',
        'unclosed-paren': 'A bracket is not closed.',
        'needs-parens': 'That function needs brackets around what it works on.',
        'unknown-name': 'The calculator does not know that name.',
        arity: 'That function is given the wrong number of values.',
        domain: 'There is no answer for those values.',
        'divide-by-zero': 'Dividing by zero has no answer.',
        overflow: 'That answer is too large to show.',
      },
      convertFailed: 'The calculator does not know one of those units, or they measure different things.',
    },
    upcoming: {
      title: 'Upcoming',
      add: 'Add a task',
      addLabel: 'Task and when it is due',
      placeholder: 'Read chapter 4 Fri 5 PM',
      importFile: 'Import a calendar file',
      importFailed: 'OpenNote could not read that file as a calendar.',
      imported: '{count, plural, one {# item} other {# items}} added from the calendar file.',
      empty: 'Nothing due. Add a task above, or import a calendar file.',
      groups: {
        overdue: 'Overdue',
        today: 'Today',
        thisWeek: 'This week',
        later: 'Later',
        undated: 'No date',
      },
      done: 'Done: {title}',
      remove: 'Remove {title}',
      due: 'Due {when}',
      undated: 'No date found. It is saved without one.',
      hidden: 'Show finished',
      added: 'Task added.',
    },
  },
  table: {
    strip: 'Table data',
    data: 'Data',
    cell: 'Cell {address}',
    typed: 'Typed: {typed}',
    totals: 'Column totals',
    filtered: 'Showing {shown} of {total} rows.',
    clearFilter: 'Clear filter',
    sortAscending: 'Sort smallest first',
    sortDescending: 'Sort largest first',
    filter: 'Filter',
    filterEqual: 'Show rows equal to this cell',
    filterNotEmpty: 'Show rows with something in this column',
    filterGreater: 'Show rows greater than this cell',
    filterLess: 'Show rows less than this cell',
    format: 'Number format',
    formats: {
      automatic: 'Automatic',
      number: 'Number',
      currency: 'Currency',
      percent: 'Percent',
      date: 'Date',
      text: 'Text',
    },
    moreDecimals: 'More decimal places',
    fewerDecimals: 'Fewer decimal places',
    total: 'Total at the bottom',
    totalNone: 'None',
    totalKinds: {
      sum: 'Sum',
      average: 'Average',
      count: 'Count',
      min: 'Lowest',
      max: 'Highest',
    },
    totalLabels: {
      sum: 'Sum of {column}',
      average: 'Average of {column}',
      count: 'Count of {column}',
      min: 'Lowest {column}',
      max: 'Highest {column}',
      checked: 'Checked in {column}',
    },
    fillDown: 'Fill down',
    fillRight: 'Fill right',
    sortedAscending: 'Sorted by {column}, smallest first.',
    sortedDescending: 'Sorted by {column}, largest first.',
    filterCleared: 'Filter cleared. Every row is showing.',
    totalOn: 'Total added at the bottom.',
    totalOff: 'Total removed.',
    filledDown: 'Filled down.',
    filledRight: 'Filled right.',
    keywords: 'table sort filter format total fill formula spreadsheet column',
  },
  calculated: {
    menu: 'Calculated column…',
    clear: 'Turn calculated column into values',
    title: 'Calculated column',
    description:
      'Each row works out the formula from its own values. Write column names in square brackets, like [Price] * [Quantity].',
    label: 'Formula for {column}',
    confirm: 'Calculate',
    empty: 'Write a formula, such as [Price] * [Quantity].',
    problem: 'The formula cannot be read: {message}',
    done: 'Every row in {column} is now calculated.',
    cleared: '{column} now holds plain values.',
    keywords: 'calculated column formula every row',
  },
  chart: {
    insert: 'Insert chart',
    insertKeywords: 'chart graph plot bar line pie area scatter table data',
    kinds: {
      bar: 'Bar chart',
      line: 'Line chart',
      area: 'Area chart',
      pie: 'Pie chart',
      scatter: 'Scatter chart',
    },
    options: 'Chart options',
    remove: 'Remove chart',
    patterns: 'Use patterns as well as colors',
    legend: 'Legend',
    slice: '{name}, {percent}%',
    other: 'Other',
    defaultTitle: '{values} by {category}',
    summary: '{kind}: {title}. {count, plural, one {# value} other {# values}}.',
    access: {
      role: 'chart',
      keys: 'Arrow keys step through the data points and read each value.',
      about:
        '{kind}: {title}. {axis} runs along the bottom, and the values are {values}. There {count, plural, one {is # point} other {are # points}}.',
      range: 'The values run from {min} to {max}.',
      trend: {
        rising: 'The values are rising overall.',
        falling: 'The values are falling overall.',
        steady: 'The values stay about the same.',
        mixed: 'The values go up and down with no clear direction.',
      },
      highest: 'The highest is {y} at {x}.',
      lowest: 'The lowest is {y} at {x}.',
      point: '{series}, {x}: {y}',
      pointOne: '{x}: {y}',
      showTable: 'Show as table',
      hideTable: 'Hide table',
      tableCaption: 'The chart’s data',
      editAutomatic: 'Edit summary',
      editWritten: 'Edit your summary',
      edit: 'Summary of this chart',
      save: 'Save summary',
      useAutomatic: 'Use the automatic summary',
    },
    columnsGone: 'This chart’s columns are no longer in the table. Remove it, or add the columns back.',
    nothing: 'This table has no column of numbers to chart yet.',
    added: 'Chart added below the table.',
    removed: 'Chart removed.',
    notes: {
      capped: 'Showing {shown} of {total} bars. The rest are left out.',
      reduced: 'Showing {shown} of {total} points, keeping the peaks.',
      skipped:
        '{total, plural, one {# row has} other {# rows have}} no number and {total, plural, one {is} other {are}} left out.',
      other: 'The smallest slices are gathered under Other, so {shown} of {total} are named.',
    },
  },
} as const;
