// Study tools, tool windows, and productivity features (owner: the tables, math, study, and tools lane). Every
// interface string is a full sentence, never joined from pieces (ARCHITECTURE.md section 19).

export const study = {
  deck: {
    tool: 'Flashcards',
    insert: 'Insert flashcards',
    insertKeywords: 'flashcards cards deck study quiz review memorize',
    open: 'Open flashcards',
    block: 'Flashcards',
    blockFallback: 'Flashcards: {name}',
    inserted: 'Flashcards added to the page.',
    newDeck: 'New deck',
    deckName: 'Deck name',
    create: 'Create deck',
    untitled: 'Deck {number}',
    none: 'There are no decks yet. Make one, import one, or type a line like "Question :: Answer" on a page.',
    cardCount: '{count, plural, =0 {No cards} one {# card} other {# cards}}',
    counts: '{due} due, {fresh} new today',
    back: 'Back to decks',
    review: 'Review',
    edit: 'Edit cards',
    rename: 'Rename deck',
    delete: 'Delete deck',
    deleted: 'Deck deleted.',
    deleteTitle: 'Delete this deck?',
    deleteBody: 'The deck and its review history are removed from this device. This cannot be undone.',
    fromPage: 'Cards from this page',
    nothingDue: 'Nothing is due right now.',
    pageDeck: 'Made from lines on this page',
  },
  review: {
    left: '{count, plural, one {# card left} other {# cards left}}',
    show: 'Show answer',
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',
    gradeHelp: 'Press 1 for Again, 2 for Hard, 3 for Good, or 4 for Easy.',
    done: 'That is everything for now.',
    next: 'Next card',
    right: 'That is right.',
    wrong: 'Not this one. The right answer is marked.',
    pickOne: 'Choose an answer.',
    blank: 'blank',
    emptyDeck: 'This deck has no cards to review.',
    nextDue: 'The next card comes back on {date}.',
  },
  edit: {
    cards: 'Cards',
    add: 'Add a card',
    save: 'Save card',
    cancel: 'Cancel',
    remove: 'Remove card',
    removed: 'Card removed.',
    saved: 'Card saved.',
    kind: 'Card type',
    kinds: {
      basic: 'Question and answer',
      cloze: 'Fill in the blank',
      choice: 'Multiple choice',
      occlusion: 'Image with hidden parts',
    },
    front: 'Question',
    back: 'Answer',
    clozeText: 'Text, with curly brackets around the words to hide',
    clozeNote: 'Put two curly brackets around each word to hide, like {example}.',
    extra: 'Extra words shown with the answer (optional)',
    choices: 'Choices, one per line',
    rightChoice: 'The right choice',
    choiceNumber: 'Choice {number}: {text}',
    prompt: 'What to ask about the image',
    image: 'Image file',
    imageAlt: 'Describe the image in words',
    boxes: 'Hidden parts',
    addBox: 'Add a hidden part',
    removeBox: 'Remove the selected hidden part',
    boxLabel: 'Hidden part {number}. Arrow keys move it. Shift with an arrow key resizes it. Delete removes it.',
    boxesNone: 'Add a hidden part, or drag across the image to draw one.',
    problemFront: 'Write something to ask.',
    problemBack: 'Write the answer.',
    problemBlank: 'Put two curly brackets around at least one word.',
    problemChoices: 'Write at least two choices.',
    problemImage: 'Pick an image and hide at least one part.',
    imageFailed: 'That file could not be read as an image.',
    empty: 'No cards yet.',
    cardLabel: '{kind}: {text}',
  },
  exam: {
    date: 'Exam date',
    none: 'No exam date',
    set: 'Exam on {date}',
    clear: 'Remove the exam date',
    target:
      '{perDay, plural, one {# card a day} other {# cards a day}} until the exam, {daysLeft, plural, one {# day} other {# days}} left.',
    today: 'The exam is today.',
    past: 'The exam date has passed.',
  },
  generate: {
    page: 'Make flashcards from this page',
    selection: 'Make flashcards from the selected text',
    keywords: 'flashcards generate cards from page section transcript study',
    title: 'Cards found in {source}',
    none: 'No cards could be found. Headings with a paragraph under them, “Term: meaning” lines, and bold words make cards.',
    keep: 'Keep {question}',
    reasons: {
      heading: 'From a heading',
      definition: 'From a definition',
      bold: 'From a bold word',
    },
    add: 'Add {count, plural, =0 {no cards} one {# card} other {# cards}}',
    toDeck: 'Add to',
    newDeckNamed: 'A new deck named {name}',
    added: '{count, plural, one {# card} other {# cards}} added to {name}.',
    noPage: 'Open a page first.',
    emptyPage: 'This page has no text to read.',
    emptySelection: 'Select some text first.',
  },
  io: {
    import: 'Import cards',
    importKeywords: 'import flashcards anki csv text deck',
    export: 'Export deck',
    file: 'File to import (CSV, text, or Anki package)',
    paste: 'Or paste cards, one per line, like Question :: Answer',
    deckNamed: 'New deck name',
    read: 'Read the cards',
    summary: '{count, plural, =0 {No new cards} one {# new card} other {# new cards}} found.',
    duplicates: '{count, plural, one {# card is} other {# cards are}} already in a deck and will be left out.',
    addDuplicates: 'Add the repeated cards too',
    skipped: '{count, plural, one {# line was} other {# lines were}} skipped.',
    skippedLine: 'Line {line}: {reason}',
    reasons: {
      empty: 'nothing on this line',
      noAnswer: 'no answer to match the question',
    },
    media: '{count, plural, one {# picture} other {# pictures}} came with the cards.',
    addDeck: 'Add as a new deck',
    imported: 'Added {count, plural, one {# card} other {# cards}} as the deck {name}.',
    failed: 'This file could not be read as cards.',
    unsupported:
      'This Anki package is in a newer format than this app reads. Export it from Anki as a package with older versions supported, then try again.',
    exportCsv: 'Export as CSV',
    exportAnki: 'Export as Anki package',
    exported: 'Saved {name}.',
    exportSkipped:
      '{count, plural, one {# image card was} other {# image cards were}} left out of the CSV, which holds only text.',
    exportFailed: 'The deck could not be saved.',
    csvLabel: 'CSV file',
    ankiLabel: 'Anki package',
  },
  converter: {
    title: 'Unit converter',
    open: 'Open the unit converter',
    keywords: 'unit converter convert length mass temperature volume speed',
    kind: 'Kind of unit',
    categories: {
      length: 'Length',
      mass: 'Mass',
      time: 'Time',
      temperature: 'Temperature',
      area: 'Area',
      volume: 'Volume',
      speed: 'Speed',
      pressure: 'Pressure',
      energy: 'Energy',
      data: 'Data size',
    },
    from: 'From',
    to: 'To',
    unit: 'Unit',
    notNumber: 'Type a number to convert.',
    insert: 'Insert into page',
    inserted: 'The conversion was added to the page.',
    noPage: 'Click in a page first, then insert.',
    note: 'Currency is not included, because exchange rates need the network.',
  },
  reference: {
    title: 'Reference tables',
    open: 'Open the reference tables',
    keywords: 'reference periodic table elements constants prefixes greek letters',
    tabs: { elements: 'Elements', constants: 'Constants', prefixes: 'Prefixes', greek: 'Greek' },
    search: 'Search',
    number: 'Number',
    symbol: 'Symbol',
    name: 'Name',
    mass: 'Atomic mass',
    family: 'Family',
    value: 'Value',
    factor: 'Factor',
    upper: 'Capital',
    lower: 'Small',
    insert: 'Insert',
    insertNamed: 'Insert {name} into the page',
    inserted: 'Added to the page.',
    noPage: 'Click in a page first, then insert.',
    groups: {
      alkali: 'Alkali metal',
      alkaline: 'Alkaline earth metal',
      transition: 'Transition metal',
      post: 'Post-transition metal',
      metalloid: 'Metalloid',
      nonmetal: 'Nonmetal',
      halogen: 'Halogen',
      noble: 'Noble gas',
      lanthanide: 'Lanthanide',
      actinide: 'Actinide',
    },
  },
  dictionary: { title: 'Dictionary' },
  citations: { title: 'Citations' },
} as const;
