// Study tools, tool windows, and productivity features (owner: the tables, math, study, and tools lane). Every
// interface string is a full sentence, never joined from pieces (ARCHITECTURE.md section 19).

export const study = {
  deck: {
    tool: 'Flashcards',
    insert: 'Insert flashcards',
    insertKeywords: 'flashcards cards deck study quiz review memorize',
    open: 'Open flashcards',
    block: 'Flashcards',
    blockFallback: 'Flashcards: {name}',
    inserted: 'Flashcards added to the page.',
    newDeck: 'New deck',
    deckName: 'Deck name',
    create: 'Create deck',
    untitled: 'Deck {number}',
    none: 'There are no decks yet. Make one, import one, or type a line like "Question :: Answer" on a page.',
    cardCount: '{count, plural, =0 {No cards} one {# card} other {# cards}}',
    counts: '{due} due, {fresh} new today',
    back: 'Back to decks',
    review: 'Review',
    edit: 'Edit cards',
    rename: 'Rename deck',
    delete: 'Delete deck',
    deleted: 'Deck deleted.',
    deleteTitle: 'Delete this deck?',
    deleteBody: 'The deck and its review history are removed from this device. This cannot be undone.',
    fromPage: 'Cards from this page',
    nothingDue: 'Nothing is due right now.',
    pageDeck: 'Made from lines on this page',
  },
  review: {
    left: '{count, plural, one {# card left} other {# cards left}}',
    show: 'Show answer',
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',
    gradeHelp: 'Press 1 for Again, 2 for Hard, 3 for Good, or 4 for Easy.',
    done: 'That is everything for now.',
    next: 'Next card',
    right: 'That is right.',
    wrong: 'Not this one. The right answer is marked.',
    pickOne: 'Choose an answer.',
    blank: 'blank',
    emptyDeck: 'This deck has no cards to review.',
    nextDue: 'The next card comes back on {date}.',
  },
  edit: {
    cards: 'Cards',
    add: 'Add a card',
    save: 'Save card',
    cancel: 'Cancel',
    remove: 'Remove card',
    removed: 'Card removed.',
    saved: 'Card saved.',
    kind: 'Card type',
    kinds: {
      basic: 'Question and answer',
      cloze: 'Fill in the blank',
      choice: 'Multiple choice',
      occlusion: 'Image with hidden parts',
    },
    front: 'Question',
    back: 'Answer',
    clozeText: 'Text, with curly brackets around the words to hide',
    clozeNote: 'Put two curly brackets around each word to hide, like {example}.',
    extra: 'Extra words shown with the answer (optional)',
    choices: 'Choices, one per line',
    rightChoice: 'The right choice',
    choiceNumber: 'Choice {number}: {text}',
    prompt: 'What to ask about the image',
    image: 'Image file',
    imageAlt: 'Describe the image in words',
    boxes: 'Hidden parts',
    addBox: 'Add a hidden part',
    removeBox: 'Remove the selected hidden part',
    boxLabel: 'Hidden part {number}. Arrow keys move it. Shift with an arrow key resizes it. Delete removes it.',
    boxesNone: 'Add a hidden part, or drag across the image to draw one.',
    problemFront: 'Write something to ask.',
    problemBack: 'Write the answer.',
    problemBlank: 'Put two curly brackets around at least one word.',
    problemChoices: 'Write at least two choices.',
    problemImage: 'Pick an image and hide at least one part.',
    imageFailed: 'That file could not be read as an image.',
    empty: 'No cards yet.',
    cardLabel: '{kind}: {text}',
  },
  exam: {
    date: 'Exam date',
    none: 'No exam date',
    set: 'Exam on {date}',
    clear: 'Remove the exam date',
    target:
      '{perDay, plural, one {# card a day} other {# cards a day}} until the exam, {daysLeft, plural, one {# day} other {# days}} left.',
    today: 'The exam is today.',
    daysLeft: '{count, plural, one {# day to the exam.} other {# days to the exam.}}',
    past: 'The exam date has passed.',
  },
  generate: {
    page: 'Make flashcards from this page',
    selection: 'Make flashcards from the selected text',
    keywords: 'flashcards generate cards from page section transcript study',
    title: 'Cards found in {source}',
    none: 'No cards could be found. Headings with a paragraph under them, “Term: meaning” lines, and bold words make cards.',
    keep: 'Keep {question}',
    reasons: {
      heading: 'From a heading',
      definition: 'From a definition',
      bold: 'From a bold word',
    },
    add: 'Add {count, plural, =0 {no cards} one {# card} other {# cards}}',
    toDeck: 'Add to',
    newDeckNamed: 'A new deck named {name}',
    added: '{count, plural, one {# card} other {# cards}} added to {name}.',
    noPage: 'Open a page first.',
    emptyPage: 'This page has no text to read.',
    emptySelection: 'Select some text first.',
  },
  io: {
    import: 'Import cards',
    importKeywords: 'import flashcards anki csv text deck',
    export: 'Export deck',
    file: 'File to import (CSV, text, or Anki package)',
    paste: 'Or paste cards, one per line, like Question :: Answer',
    deckNamed: 'New deck name',
    read: 'Read the cards',
    summary: '{count, plural, =0 {No new cards} one {# new card} other {# new cards}} found.',
    duplicates: '{count, plural, one {# card is} other {# cards are}} already in a deck and will be left out.',
    addDuplicates: 'Add the repeated cards too',
    skipped: '{count, plural, one {# line was} other {# lines were}} skipped.',
    skippedLine: 'Line {line}: {reason}',
    reasons: {
      empty: 'nothing on this line',
      noAnswer: 'no answer to match the question',
    },
    media: '{count, plural, one {# picture} other {# pictures}} came with the cards.',
    addDeck: 'Add as a new deck',
    imported: 'Added {count, plural, one {# card} other {# cards}} as the deck {name}.',
    failed: 'This file could not be read as cards.',
    unsupported:
      'This Anki package is in a newer format than this app reads. Export it from Anki as a package with older versions supported, then try again.',
    exportCsv: 'Export as CSV',
    exportAnki: 'Export as Anki package',
    exported: 'Saved {name}.',
    exportSkipped:
      '{count, plural, one {# image card was} other {# image cards were}} left out of the CSV, which holds only text.',
    exportFailed: 'The deck could not be saved.',
    csvLabel: 'CSV file',
    ankiLabel: 'Anki package',
  },
  exams: {
    title: 'Exams',
    daysLeft: '{count, plural, =0 {Today} =1 {Tomorrow} other {# days}}',
    add: 'Add an exam',
    place: 'For a notebook or section',
    noPlace: 'No notebook or section',
    for: 'for {place}',
    name: 'Exam name',
    date: 'Date',
    time: 'Time (optional)',
    deck: 'Flashcard deck (optional)',
    noDeck: 'No deck',
    addButton: 'Add exam',
    added: 'Exam added.',
    remove: 'Remove {name}',
    needDate: 'Give the exam a name and a date.',
  },
  timetable: {
    today: 'Today’s classes',
    noneToday: 'No classes today.',
    next: 'Next class: {name}, {day} at {time}.',
    add: 'Add a class',
    name: 'Class name',
    days: 'Days',
    start: 'Starts',
    end: 'Ends',
    room: 'Room',
    addButton: 'Add class',
    added: 'Class added.',
    remove: 'Remove {name}',
    needFields: 'Give the class a name, at least one day, and times.',
  },
  mindmap: {
    insert: 'Insert mind map',
    insertKeywords: 'mind map outline brainstorm branches ideas diagram',
    block: 'Mind map',
    label: 'Mind map, shown as a nested list',
    mainIdea: 'Main idea',
    empty: 'Empty branch',
    inserted:
      'Mind map added. Press Enter on a branch to write in it, Tab for a branch under it, Enter for one beside it.',
    tools: 'Mind map tools',
    addChild: 'Add branch under',
    addSibling: 'Add branch beside',
    fold: 'Fold branches',
    unfold: 'Unfold branches',
    remove: 'Remove branch',
    toOutline: 'Insert as outline',
    outlineInserted: 'The outline was added to the page.',
    noPage: 'Click in a page first, then insert.',
    childAdded: 'Branch added under it.',
    siblingAdded: 'Branch added beside it.',
    removed: 'Branch removed.',
    branchText: 'Branch text',
    hidden: '{count, plural, one {# branch folded} other {# branches folded}}',
    keys: 'Arrow keys move between branches. Enter writes in a branch. While writing, Tab adds a branch under and Enter adds one beside. Space folds. Delete removes. Escape stops writing.',
  },
  diagram: {
    insert: 'Insert diagram from text',
    insertKeywords: 'diagram mermaid flowchart sequence timeline class chart text',
    block: 'Diagram',
    inserted: 'Diagram added. Change its text and the drawing follows.',
    start: 'Start from an example',
    choose: 'Choose an example',
    kinds: { flowchart: 'Flowchart', sequence: 'Sequence diagram', timeline: 'Timeline', class: 'Class diagram' },
    text: 'Diagram text',
    label: '{kind}, drawn from the diagram text',
    problem: 'The diagram text has a problem. {message}',
    save: 'Save as SVG',
    svgLabel: 'SVG picture',
    saved: 'Diagram saved.',
    saveFailed: 'The diagram could not be saved.',
  },
  planner: { summary: 'Exams and classes' },
  tape: {
    insert: 'Insert study tape',
    insertKeywords: 'study tape cover hide reveal answer quiz',
    showAll: 'Show all study tape',
    hideAll: 'Hide all study tape',
    block: 'Study tape',
    fallback: '________',
    hiddenLabel: 'Study tape, covering part of the page. Press to uncover it.',
    shownLabel: 'Study tape, uncovered. Press to cover it again.',
    hiddenHint: 'Press to uncover',
    shownHint: 'Press to cover',
    inserted: 'Study tape added. Move and resize it over what you want to hide.',
    allShown: 'All study tape is uncovered.',
    allHidden: 'All study tape is covering the page.',
    none: 'There is no study tape on this page.',
  },
  quickMath: {
    title: 'Quick math',
    label: 'Add the answer when I type a sum, an equals sign, and a space',
    help: 'Type 2.5*9.81= and press Space to add the answer. Press Ctrl+Z once to take it back out.',
    error: 'The sum {sum} cannot be worked out.',
  },
  notes: {
    graph: 'Graph this',
    graphThis: 'Graph this equation: {equation}',
  },
  calendar: {
    found: 'Found in {name}',
    kinds: {
      classes: '{count, plural, one {# weekly class} other {# weekly classes}} for the timetable',
      exams: '{count, plural, one {# exam date} other {# exam dates}}',
      items: '{count, plural, one {# assignment or event} other {# assignments and events}}',
    },
    import: 'Add these',
    update: 'Update from this file',
    imported: 'Added {count, plural, one {# item} other {# items}} from the file.',
    updated: 'Updated from the file: {added} added, {removed} removed.',
  },
  reminders: {
    label: 'Remind me with a Windows notification when something is due',
    blocked: 'Windows did not allow notifications for this app. You can allow them in Windows Settings.',
    due: 'Due now',
    timer: 'Timer finished',
  },
  repeat: {
    label: 'Repeat',
    choices: {
      none: 'Does not repeat',
      daily: 'Every day',
      weekly: 'Every week',
      afterDays: 'Some days after I finish it',
    },
    days: 'Days after I finish',
    badge: '(repeats)',
    skip: 'Skip this one',
    skipNamed: 'Skip this one: {title}',
    next: 'The next {title} is set.',
    needsDate: 'A repeating task needs a date, so this one was added without repeating.',
  },
  dueDates: {
    fromPage: 'from {page}',
    pick: 'Change the due date: {date}',
    chip: 'Due {date}',
    changed: 'Due date changed.',
    open: 'Choose a due date',
  },
  converter: {
    title: 'Unit converter',
    open: 'Open the unit converter',
    keywords: 'unit converter convert length mass temperature volume speed',
    kind: 'Kind of unit',
    categories: {
      length: 'Length',
      mass: 'Mass',
      time: 'Time',
      temperature: 'Temperature',
      area: 'Area',
      volume: 'Volume',
      speed: 'Speed',
      pressure: 'Pressure',
      energy: 'Energy',
      power: 'Power',
      angle: 'Angle',
      data: 'Data size',
    },
    from: 'From',
    to: 'To',
    unit: 'Unit',
    notNumber: 'Type a number to convert.',
    insert: 'Insert into page',
    inserted: 'The conversion was added to the page.',
    noPage: 'Click in a page first, then insert.',
    note: 'Currency is not included, because exchange rates need the network.',
  },
  reference: {
    title: 'Reference tables',
    open: 'Open the reference tables',
    keywords: 'reference periodic table elements constants prefixes greek letters',
    tabs: { elements: 'Elements', constants: 'Constants', prefixes: 'Prefixes', greek: 'Greek' },
    search: 'Search',
    number: 'Number',
    symbol: 'Symbol',
    name: 'Name',
    mass: 'Atomic mass',
    family: 'Family',
    groupNumber: 'Group',
    noGroup: 'None',
    configuration: 'Electron configuration',
    insertConfiguration: 'Insert the electron configuration of {name} into the page',
    value: 'Value',
    factor: 'Factor',
    upper: 'Capital',
    lower: 'Small',
    insert: 'Insert',
    insertNamed: 'Insert {name} into the page',
    inserted: 'Added to the page.',
    noPage: 'Click in a page first, then insert.',
    groups: {
      alkali: 'Alkali metal',
      alkaline: 'Alkaline earth metal',
      transition: 'Transition metal',
      post: 'Post-transition metal',
      metalloid: 'Metalloid',
      nonmetal: 'Nonmetal',
      halogen: 'Halogen',
      noble: 'Noble gas',
      lanthanide: 'Lanthanide',
      actinide: 'Actinide',
    },
  },
  dictionary: { title: 'Dictionary' },
  citations: {
    title: 'Citations',
    open: 'Open citations',
    keywords: 'citation bibliography sources references apa mla chicago bibtex ris zotero',
    style: 'Citation style',
    styles: {
      apa: 'APA 7',
      mla: 'MLA 9',
      chicago: 'Chicago (author-date)',
      harvard: 'Harvard',
      ieee: 'IEEE',
    },
    add: 'Add a source',
    fromZotero: 'Import from Zotero',
    none: 'No sources yet. Add one, or import a BibTeX or RIS file.',
    cite: 'Cite',
    citeNamed: 'Insert a citation for {title}',
    edit: 'Edit',
    editNamed: 'Edit {title}',
    removeNamed: 'Remove {title}',
    removed: 'Source removed.',
    saved: 'Source saved.',
    save: 'Save source',
    needTitle: 'A source needs a title.',
    type: 'Kind of source',
    types: { book: 'Book', article: 'Article', web: 'Web page', recording: 'Recording' },
    fields: {
      title: 'Title',
      authors: 'Authors, one to a line',
      container: 'Journal, website, or series',
      publisher: 'Publisher',
      place: 'Place of publication',
      edition: 'Edition',
      volume: 'Volume',
      issue: 'Issue',
      pages: 'Pages',
      url: 'Web address',
      doi: 'DOI',
      year: 'Year',
      month: 'Month, as a number',
      day: 'Day',
      accessed: 'Date you read it, as YYYY-MM-DD',
    },
    bibliography: 'Bibliography',
    insertBibliography: 'Insert bibliography',
    exportText: 'Save as text',
    exportBibtex: 'Save as BibTeX',
    exportRis: 'Save as RIS',
    textLabel: 'Text file',
    bibLabel: 'BibTeX file',
    risLabel: 'RIS file',
    import: 'Import sources',
    file: 'BibTeX or RIS file',
    paste: 'Or paste BibTeX or RIS text',
    importPasted: 'Import pasted text',
    imported:
      'Added {added, plural, one {# source} other {# sources}}. {repeats, plural, =0 {} one {# was already in the list. } other {# were already in the list. }}{unreadable, plural, =0 {} one {# entry could not be read.} other {# entries could not be read.}}',
    nothingFound: 'No sources were found in that text.',
    cited: 'Citation added to the page.',
    inserted: 'Bibliography added to the page.',
    noPage: 'Click in a page first, then insert.',
    zoteroOff:
      'Zotero is running, but it does not allow other programs to read it. In Zotero, open Settings, then Advanced, and turn on communication with other applications.',
    zoteroMissing: 'Zotero is not running on this computer. Open it, then try again.',
    zoteroFailed: 'The Zotero library could not be read.',
  },
} as const;
