// Study tools, tool windows, and productivity features (owner: the tables, math, study, and tools lane). Every
// interface string is a full sentence, never joined from pieces (ARCHITECTURE.md section 19).

export const study = {
  deck: {
    tool: 'Flashcards',
    insert: 'Insert flashcards',
    insertKeywords: 'flashcards cards deck study quiz review memorize',
    open: 'Open flashcards',
    block: 'Flashcards',
    blockFallback: 'Flashcards: {name}',
    inserted: 'Flashcards added to the page.',
    newDeck: 'New deck',
    deckName: 'Deck name',
    create: 'Create deck',
    untitled: 'Deck {number}',
    none: 'There are no decks yet. Make one, import one, or type a line like "Question :: Answer" on a page.',
    cardCount: '{count, plural, =0 {No cards} one {# card} other {# cards}}',
    counts: '{due} due, {fresh} new today',
    back: 'Back to decks',
    review: 'Review',
    edit: 'Edit cards',
    rename: 'Rename deck',
    delete: 'Delete deck',
    deleted: 'Deck deleted.',
    deleteTitle: 'Delete this deck?',
    deleteBody: 'The deck and its review history are removed from this device. This cannot be undone.',
    fromPage: 'Cards from this page',
    nothingDue: 'Nothing is due right now.',
    pageDeck: 'Made from lines on this page',
  },
  quiz: {
    open: 'Quiz',
    insert: 'Insert quiz',
    insertKeywords: 'quiz test flashcards deck random questions score',
    block: 'Quiz',
    blockFallback: 'Quiz: {name}',
    inserted: 'Quiz added to the page.',
    noCards: 'This deck has no cards to ask about yet. Add some cards first.',
    count: 'Number of questions',
    help: 'Questions come from the deck at random, up to {max}. A quiz does not change when your cards come back for review.',
    start: 'Start quiz',
    progress: 'Question {number} of {total}',
    yourAnswer: 'Your answer',
    blankAnswer: 'Answer for blank {number}',
    check: 'Check answer',
    right: 'That is right.',
    notQuite: 'Not this time.',
    countIt: 'I had it right',
    next: 'Next',
    result: 'You answered {right} of {total} correctly.',
    missed: 'To look at again:',
    allRight: 'Every answer was right.',
    again: 'Quiz again',
  },
  review: {
    left: '{count, plural, one {# card left} other {# cards left}}',
    show: 'Show answer',
    again: 'Again',
    hard: 'Hard',
    good: 'Good',
    easy: 'Easy',
    gradeHelp: 'Press 1 for Again, 2 for Hard, 3 for Good, or 4 for Easy.',
    done: 'That is everything for now.',
    next: 'Next card',
    right: 'That is right.',
    wrong: 'Not this one. The right answer is marked.',
    pickOne: 'Choose an answer.',
    blank: 'blank',
    emptyDeck: 'This deck has no cards to review.',
    nextDue: 'The next card comes back on {date}.',
  },
  edit: {
    cards: 'Cards',
    add: 'Add a card',
    save: 'Save card',
    cancel: 'Cancel',
    remove: 'Remove card',
    removed: 'Card removed.',
    saved: 'Card saved.',
    kind: 'Card type',
    kinds: {
      basic: 'Question and answer',
      cloze: 'Fill in the blank',
      choice: 'Multiple choice',
      occlusion: 'Image with hidden parts',
    },
    front: 'Question',
    back: 'Answer',
    clozeText: 'Text, with curly brackets around the words to hide',
    clozeNote: 'Put two curly brackets around each word to hide, like {example}.',
    extra: 'Extra words shown with the answer (optional)',
    choices: 'Choices, one per line',
    rightChoice: 'The right choice',
    choiceNumber: 'Choice {number}: {text}',
    prompt: 'What to ask about the image',
    image: 'Image file',
    imageAlt: 'Describe the image in words',
    boxes: 'Hidden parts',
    addBox: 'Add a hidden part',
    removeBox: 'Remove the selected hidden part',
    boxLabel: 'Hidden part {number}. Arrow keys move it. Shift with an arrow key resizes it. Delete removes it.',
    boxesNone: 'Add a hidden part, or drag across the image to draw one.',
    problemFront: 'Write something to ask.',
    problemBack: 'Write the answer.',
    problemBlank: 'Put two curly brackets around at least one word.',
    problemChoices: 'Write at least two choices.',
    problemImage: 'Pick an image and hide at least one part.',
    imageFailed: 'That file could not be read as an image.',
    empty: 'No cards yet.',
    cardLabel: '{kind}: {text}',
  },
  exam: {
    date: 'Exam date',
    none: 'No exam date',
    set: 'Exam on {date}',
    clear: 'Remove the exam date',
    target:
      '{perDay, plural, one {# card a day} other {# cards a day}} until the exam, {daysLeft, plural, one {# day} other {# days}} left.',
    today: 'The exam is today.',
    daysLeft: '{count, plural, one {# day to the exam.} other {# days to the exam.}}',
    past: 'The exam date has passed.',
  },
  generate: {
    page: 'Make flashcards from this page',
    selection: 'Make flashcards from the selected text',
    keywords: 'flashcards generate cards from page section transcript study',
    title: 'Cards found in {source}',
    none: 'No cards could be found. Headings with a paragraph under them, “Term: meaning” lines, and bold words make cards.',
    keep: 'Keep {question}',
    reasons: {
      heading: 'From a heading',
      definition: 'From a definition',
      bold: 'From a bold word',
    },
    add: 'Add {count, plural, =0 {no cards} one {# card} other {# cards}}',
    toDeck: 'Add to',
    newDeckNamed: 'A new deck named {name}',
    added: '{count, plural, one {# card} other {# cards}} added to {name}.',
    noPage: 'Open a page first.',
    emptyPage: 'This page has no text to read.',
    emptySelection: 'Select some text first.',
    section: 'Make flashcards from this section',
    noSection: 'Choose a section first.',
    emptySection: 'This section has no text to read.',
    sectionSkipped: '{count, plural, one {# page} other {# pages}} could not be read and left out.',
    transcript: 'Make cards',
    emptyTranscript: 'This transcript has no words to read.',
  },
  io: {
    import: 'Import cards',
    importKeywords: 'import flashcards anki csv text deck',
    export: 'Export deck',
    file: 'File to import (CSV, text, or Anki package)',
    paste: 'Or paste cards, one per line, like Question :: Answer',
    deckNamed: 'New deck name',
    read: 'Read the cards',
    summary: '{count, plural, =0 {No new cards} one {# new card} other {# new cards}} found.',
    duplicates: '{count, plural, one {# card is} other {# cards are}} already in a deck and will be left out.',
    addDuplicates: 'Add the repeated cards too',
    skipped: '{count, plural, one {# line was} other {# lines were}} skipped.',
    skippedLine: 'Line {line}: {reason}',
    reasons: {
      empty: 'nothing on this line',
      noAnswer: 'no answer to match the question',
    },
    media: '{count, plural, one {# picture} other {# pictures}} came with the cards.',
    addDeck: 'Add as a new deck',
    imported: 'Added {count, plural, one {# card} other {# cards}} as the deck {name}.',
    failed: 'This file could not be read as cards.',
    unsupported:
      'This Anki package is in a newer format than this app reads. Export it from Anki as a package with older versions supported, then try again.',
    exportCsv: 'Export as CSV',
    exportAnki: 'Export as Anki package',
    exported: 'Saved {name}.',
    exportSkipped:
      '{count, plural, one {# image card was} other {# image cards were}} left out of the CSV, which holds only text.',
    exportFailed: 'The deck could not be saved.',
    csvLabel: 'CSV file',
    ankiLabel: 'Anki package',
  },
  exams: {
    title: 'Exams',
    daysLeft: '{count, plural, =0 {Today} =1 {Tomorrow} other {# days}}',
    add: 'Add an exam',
    place: 'For a notebook or section',
    noPlace: 'No notebook or section',
    for: 'for {place}',
    name: 'Exam name',
    date: 'Date',
    time: 'Time (optional)',
    deck: 'Flashcard deck (optional)',
    noDeck: 'No deck',
    addButton: 'Add exam',
    added: 'Exam added.',
    remove: 'Remove {name}',
    needDate: 'Give the exam a name and a date.',
  },
  timetable: {
    today: 'Today’s classes',
    noneToday: 'No classes today.',
    next: 'Next class: {name}, {day} at {time}.',
    add: 'Add a class',
    name: 'Class name',
    days: 'Days',
    start: 'Starts',
    end: 'Ends',
    room: 'Room',
    addButton: 'Add class',
    added: 'Class added.',
    remove: 'Remove {name}',
    needFields: 'Give the class a name, at least one day, and times.',
    section: 'Section for its notes',
    noSection: 'No section',
    inSection: 'Notes go in {section}.',
    open: 'Open class',
    openNamed: 'Open the page for {name}',
    record: 'Record',
    recordNamed: 'Record {name}',
    opened: 'Opened the page for {name}.',
    made: 'Made the page for {name} from the class template.',
    sectionGone: 'The section for {name} is not there any more. Choose another in the timetable.',
    recordStarted: 'Recording {name}.',
    recordBusy: 'A recording is already running, so a new one was not started.',
    recordWaited: 'The page for {name} did not open in time, so no recording was started.',
    template: 'Class page template',
    templateHelp: 'The words a new class page starts with. You can use {placeholders}.',
    templateReset: 'Use the standard template',
  },
  mindmap: {
    insert: 'Insert mind map',
    insertKeywords: 'mind map outline brainstorm branches ideas diagram',
    block: 'Mind map',
    label: 'Mind map, shown as a nested list',
    mainIdea: 'Main idea',
    empty: 'Empty branch',
    inserted:
      'Mind map added. Press Enter on a branch to write in it, Tab for a branch under it, Enter for one beside it.',
    tools: 'Mind map tools',
    addChild: 'Add branch under',
    addSibling: 'Add branch beside',
    fold: 'Fold branches',
    unfold: 'Unfold branches',
    remove: 'Remove branch',
    toOutline: 'Insert as outline',
    outlineInserted: 'The outline was added to the page.',
    noPage: 'Click in a page first, then insert.',
    childAdded: 'Branch added under it.',
    siblingAdded: 'Branch added beside it.',
    removed: 'Branch removed.',
    branchText: 'Branch text',
    hidden: '{count, plural, one {# branch folded} other {# branches folded}}',
    keys: 'Arrow keys move between branches. Enter writes in a branch. While writing, Tab adds a branch under and Enter adds one beside. Space folds. Delete removes. Escape stops writing.',
  },
  diagram: {
    insert: 'Insert diagram from text',
    insertKeywords: 'diagram mermaid flowchart sequence timeline class chart text',
    block: 'Diagram',
    inserted: 'Diagram added. Change its text and the drawing follows.',
    start: 'Start from an example',
    choose: 'Choose an example',
    kinds: { flowchart: 'Flowchart', sequence: 'Sequence diagram', timeline: 'Timeline', class: 'Class diagram' },
    text: 'Diagram text',
    label: '{kind}, drawn from the diagram text',
    problem: 'The diagram text has a problem. {message}',
    save: 'Save as SVG',
    svgLabel: 'SVG picture',
    saved: 'Diagram saved.',
    saveFailed: 'The diagram could not be saved.',
  },
  planner: { summary: 'Exams and classes' },
  tape: {
    insert: 'Insert study tape',
    insertKeywords: 'study tape cover hide reveal answer quiz',
    showAll: 'Show all study tape',
    hideAll: 'Hide all study tape',
    block: 'Study tape',
    fallback: '________',
    hiddenLabel: 'Study tape, covering part of the page. Press to uncover it.',
    shownLabel: 'Study tape, uncovered. Press to cover it again.',
    hiddenHint: 'Press to uncover',
    shownHint: 'Press to cover',
    inserted: 'Study tape added. Move and resize it over what you want to hide.',
    allShown: 'All study tape is uncovered.',
    allHidden: 'All study tape is covering the page.',
    none: 'There is no study tape on this page.',
  },
  quickMath: {
    title: 'Quick math',
    label: 'Add the answer when I type a sum, an equals sign, and a space',
    help: 'Type 2.5*9.81= and press Space to add the answer. Press Ctrl+Z once to take it back out.',
    error: 'The sum {sum} cannot be worked out.',
  },
  notes: {
    graph: 'Graph this',
    graphThis: 'Graph this equation: {equation}',
  },
  calendar: {
    found: 'Found in {name}',
    kinds: {
      classes: '{count, plural, one {# weekly class} other {# weekly classes}} for the timetable',
      exams: '{count, plural, one {# exam date} other {# exam dates}}',
      items: '{count, plural, one {# assignment or event} other {# assignments and events}}',
    },
    import: 'Add these',
    update: 'Update from this file',
    imported: 'Added {count, plural, one {# item} other {# items}} from the file.',
    updated: 'Updated from the file: {added} added, {removed} removed.',
  },
  reminders: {
    label: 'Allow Windows notifications for reminders and timers',
    blocked: 'Windows did not allow notifications for this app. You can allow them in Windows Settings.',
    due: 'Due now',
    timer: 'Timer finished',
    item: 'Remind me',
    itemNamed: 'Remind me about {title}',
    itemOn: 'A reminder is set for {title}.',
    itemOff: 'The reminder for {title} is off.',
  },
  repeat: {
    label: 'Repeat',
    choices: {
      none: 'Does not repeat',
      daily: 'Every day',
      weekly: 'Every week',
      afterDays: 'Some days after I finish it',
    },
    days: 'Days after I finish',
    badge: '(repeats)',
    badgeWhen: '(repeats {when})',
    when: {
      day: '{count, plural, one {every day} other {every # days}}',
      weekday: 'every weekday',
      week: '{count, plural, one {every week} other {every # weeks}}',
      weekOn: 'every {days}',
      month: '{count, plural, one {every month} other {every # months}}',
      monthOn: '{base} on day {day}',
      monthLast: '{base} on the last day',
    },
    skip: 'Skip this one',
    skipNamed: 'Skip this one: {title}',
    next: 'The next {title} is set.',
    needsDate: 'A repeating task needs a date, so this one was added without repeating.',
  },
  dueDates: {
    checkedOff: 'Checked off {title} on its page.',
    reopened: 'Opened {title} again on its page.',
    moved: 'The line {title} has moved on its page, so nothing was changed. It will update here shortly.',
    checkFailed: 'The page for {title} could not be changed.',
    fromPage: 'from {page}',
    pick: 'Change the due date: {date}',
    chip: 'Due {date}',
    changed: 'Due date changed.',
    open: 'Choose a due date',
  },
  converter: {
    title: 'Unit converter',
    open: 'Open the unit converter',
    keywords: 'unit converter convert length mass temperature volume speed',
    kind: 'Kind of unit',
    categories: {
      length: 'Length',
      mass: 'Mass',
      time: 'Time',
      temperature: 'Temperature',
      area: 'Area',
      volume: 'Volume',
      speed: 'Speed',
      pressure: 'Pressure',
      energy: 'Energy',
      power: 'Power',
      angle: 'Angle',
      data: 'Data size',
    },
    from: 'From',
    to: 'To',
    unit: 'Unit',
    notNumber: 'Type a number to convert.',
    insert: 'Insert into page',
    inserted: 'The conversion was added to the page.',
    noPage: 'Click in a page first, then insert.',
    note: 'Currency is not included, because exchange rates need the network.',
  },
  reference: {
    title: 'Reference tables',
    open: 'Open the reference tables',
    keywords: 'reference periodic table elements constants prefixes greek letters',
    tabs: { elements: 'Elements', constants: 'Constants', prefixes: 'Prefixes', greek: 'Greek' },
    search: 'Search',
    number: 'Number',
    symbol: 'Symbol',
    name: 'Name',
    mass: 'Atomic mass',
    family: 'Family',
    groupNumber: 'Group',
    noGroup: 'None',
    configuration: 'Electron configuration',
    insertConfiguration: 'Insert the electron configuration of {name} into the page',
    value: 'Value',
    factor: 'Factor',
    upper: 'Capital',
    lower: 'Small',
    insert: 'Insert',
    insertNamed: 'Insert {name} into the page',
    inserted: 'Added to the page.',
    noPage: 'Click in a page first, then insert.',
    groups: {
      alkali: 'Alkali metal',
      alkaline: 'Alkaline earth metal',
      transition: 'Transition metal',
      post: 'Post-transition metal',
      metalloid: 'Metalloid',
      nonmetal: 'Nonmetal',
      halogen: 'Halogen',
      noble: 'Noble gas',
      lanthanide: 'Lanthanide',
      actinide: 'Actinide',
    },
  },
  views: {
    views: 'Upcoming views',
    tabs: { list: 'List', week: 'Week', month: 'Month' },
    previousWeek: 'Previous week',
    nextWeek: 'Next week',
    previousMonth: 'Previous month',
    nextMonth: 'Next month',
    goToToday: 'Today',
    weekGrid: 'Week of {range}',
    monthGrid: '{range}',
    count: '{count, plural, =0 {nothing due} one {# item} other {# items}}',
    today: 'today',
    dueOn: 'Due on {date}',
    nothing: 'Nothing is due on this day.',
    open: 'Open page',
    openPage: 'Open the page {page}',
  },
  toolWindows: {
    reset: 'Reset tool windows',
    resetKeywords: 'tool windows reset size position monitor place default',
    resetDone: 'Tool windows are back at their first size and place.',
  },
  dictionary: {
    title: 'Dictionary',
    open: 'Open the dictionary',
    keywords: 'dictionary thesaurus synonyms meaning definition word look up',
    lookupSelection: 'Look up the selected word',
    selectFirst: 'Select a word on the page first.',
    word: 'Word',
    empty: 'Type a word to see what it means and which words mean the same.',
    found: '{word}: {count, plural, one {# part of speech} other {# parts of speech}}.',
    notFound: 'No entry for {word}.',
    baseForm: '(from {query})',
    synonyms: 'Same meaning',
    pos: { n: 'Noun', v: 'Verb', a: 'Adjective', r: 'Adverb' },
    insert: 'Insert synonym',
    insertNamed: 'Insert synonym {word}',
    lookUp: 'Look up',
    lookUpNamed: 'Look up {word}',
    inserted: 'Put {word} in the page.',
    noPage: 'Open a page to put {word} in it.',
    language: 'Language',
    english: 'English',
    about: 'English meanings come with the app and work offline. Other languages are dictionary files you add; they stay on this device.',
    packs: {
      summary: 'Other languages',
      help: 'Choose a dictionary file (JSON) to add a language. It is read here, kept on this device, and never sent anywhere.',
      file: 'Dictionary file',
      added: 'Added {name}, with {count, plural, one {# word} other {# words}}.',
      removed: 'Removed {name}.',
      removeNamed: 'Remove the {name} dictionary',
      size: '{words, plural, one {# word} other {# words}}, {size} KB',
      notJson: 'That file is not a dictionary: it is not JSON.',
      format: 'That file is not a dictionary file. It needs a format, a name, a language, and words with meanings.',
      empty: 'That dictionary has no words.',
      tooLarge: 'That file is too large for a dictionary.',
    },
  },
  citations: {
    title: 'Citations',
    open: 'Open citations',
    keywords: 'citation bibliography sources references apa mla chicago bibtex ris zotero',
    style: 'Citation style',
    styles: {
      apa: 'APA 7',
      mla: 'MLA 9',
      chicago: 'Chicago (author-date)',
      harvard: 'Harvard',
      ieee: 'IEEE',
    },
    lookup: {
      heading: 'Look up a source',
      label: 'DOI or ISBN',
      help: 'Pressing Look up sends that DOI or ISBN, and nothing else, to {hosts}. Nothing is sent until you press it, and never while Work offline is on.',
      button: 'Look up',
      result: 'Source found',
      found: 'Found {title}. Add it to the list if it is right.',
      add: 'Add to the list',
      discard: 'Leave it out',
      badId: 'That does not look like a DOI or an ISBN.',
      offline: 'Work offline is on, so nothing was looked up.',
      notFound: 'No source was found for that.',
      failed: 'The look-up did not work. Check your connection and try again.',
      unavailable: 'Looking up a source is only in the desktop app.',
    },
    live: {
      cite: 'Cite (follows style)',
      citeNamed: 'Insert a citation that follows the style for {title}',
      inserted: 'Citation added. It changes when you change the style.',
      insertBibliography: 'Insert bibliography that follows the style',
      bibliographyInserted: 'Bibliography added. It changes when you change the style or the sources.',
      missing: 'This source is not in the list any more.',
      noSources: 'There are no sources to list.',
      blockCitation: 'Citation',
      blockBibliography: 'Bibliography',
      insertBibliographyCommand: 'Insert bibliography',
      insertBibliographyKeywords: 'bibliography references sources works cited citations style',
    },
    privacy: {
      title: 'Looking up a source',
      detail:
        'When you ask to look up a DOI or ISBN, it is sent to {hosts}. Nothing else is sent, and nothing is sent until you ask.',
      lastRan: 'Last looked up on {date} at {time}.',
      never: 'Never looked up.',
      blocked: 'Blocked while Work offline is on.',
    },
    styleFiles: 'Style files',
    styleFilesHelp:
      'Vancouver, AMA, ACS, Turabian, and Nature come with the app. To add another style, choose a style file (JSON) that lists how an entry and an in-text citation are written.',
    styleFile: 'Style file to add',
    styleAdded: 'The {name} style was added and chosen.',
    styleOwned: 'The app already has a style with the id of {name}, so it was not added.',
    styleRemove: 'Remove the {name} style',
    styleRemoved: 'The {name} style was removed.',
    style_notJson: 'That file is not a style file: it is not JSON.',
    style_template: 'That style file has a template that cannot be read. {problem}',
    style_shape:
      'That file is not a style file: it needs an id, a title, name rules, an in-text template, and an entry for books.',
    add: 'Add a source',
    fromZotero: 'Import from Zotero',
    none: 'No sources yet. Add one, or import a BibTeX or RIS file.',
    cite: 'Cite',
    citeNamed: 'Insert a citation for {title}',
    edit: 'Edit',
    editNamed: 'Edit {title}',
    removeNamed: 'Remove {title}',
    removed: 'Source removed.',
    saved: 'Source saved.',
    save: 'Save source',
    needTitle: 'A source needs a title.',
    type: 'Kind of source',
    types: { book: 'Book', article: 'Article', web: 'Web page', recording: 'Recording' },
    fields: {
      title: 'Title',
      authors: 'Authors, one to a line',
      container: 'Journal, website, or series',
      publisher: 'Publisher',
      place: 'Place of publication',
      edition: 'Edition',
      volume: 'Volume',
      issue: 'Issue',
      pages: 'Pages',
      url: 'Web address',
      doi: 'DOI',
      year: 'Year',
      month: 'Month, as a number',
      day: 'Day',
      accessed: 'Date you read it, as YYYY-MM-DD',
    },
    bibliography: 'Bibliography',
    insertBibliography: 'Insert bibliography',
    exportText: 'Save as text',
    exportBibtex: 'Save as BibTeX',
    exportRis: 'Save as RIS',
    textLabel: 'Text file',
    bibLabel: 'BibTeX file',
    risLabel: 'RIS file',
    import: 'Import sources',
    file: 'BibTeX or RIS file',
    paste: 'Or paste BibTeX or RIS text',
    importPasted: 'Import pasted text',
    imported:
      'Added {added, plural, one {# source} other {# sources}}. {repeats, plural, =0 {} one {# was already in the list. } other {# were already in the list. }}{unreadable, plural, =0 {} one {# entry could not be read.} other {# entries could not be read.}}',
    nothingFound: 'No sources were found in that text.',
    cited: 'Citation added to the page.',
    inserted: 'Bibliography added to the page.',
    noPage: 'Click in a page first, then insert.',
    zoteroOff:
      'Zotero is running, but it does not allow other programs to read it. In Zotero, open Settings, then Advanced, and turn on communication with other applications.',
    zoteroMissing: 'Zotero is not running on this computer. Open it, then try again.',
    zoteroFailed: 'The Zotero library could not be read.',
  },
} as const;
