// The notebooks and pages trees, the page area, and Trash.
// Every interface string is a full sentence here, never joined from pieces (ARCHITECTURE.md section 19).

export const tree = {
  label: {
    notebooks: 'Notebooks',
    pages: 'Pages',
  },
  untitled: {
    notebook: 'Untitled notebook',
    sectionGroup: 'Untitled section group',
    section: 'Untitled section',
    page: 'Untitled page',
  },
  describe: {
    kind: '{kind, select, notebook {Notebook} sectionGroup {Section group} section {Section} other {Page}}',
    colored: '{kind, select, notebook {Notebook} sectionGroup {Section group} other {Section}}, color {color}',
    page: '{level, select, 0 {Page} other {Subpage}}, {date}',
  },
  colors: {
    ink: 'Ink',
    indigo: 'Indigo',
    brick: 'Brick',
    fern: 'Fern',
    plum: 'Plum',
    amber: 'Amber',
    walnut: 'Walnut',
    none: 'No color',
    menu: 'Color',
  },
  commands: {
    newNotebook: 'New notebook',
    newSectionGroup: 'New section group',
    newSection: 'New section',
    newPage: 'New page',
    newSubpage: 'New subpage',
    rename: 'Rename',
    moveUp: 'Move up',
    moveDown: 'Move down',
    indent: 'Make subpage',
    outdent: 'Promote',
    moveTo: 'Move to',
    color: 'Color',
    trash: 'Delete',
    undo: 'Undo',
    redo: 'Redo',
    openTrash: 'Open Trash',
    restore: 'Restore',
    keywords: {
      trash: 'Move to Trash remove',
      newPage: 'Add page create',
      indent: 'Indent subpage level',
      outdent: 'Outdent promote level',
    },
  },
  menu: {
    label: 'Actions for {title}',
    more: 'More actions for {title}',
  },
  empty: {
    notebooks: 'No notebooks yet. Choose New notebook to start one.',
    pages: 'No pages yet. Press {shortcut} or choose New page to start one.',
    pagesNoShortcut: 'No pages yet. Choose New page to start one.',
    noSection: 'Choose a section to see its pages.',
  },
  loading: {
    notebooks: 'Loading notebooks',
    pages: 'Loading pages',
    page: 'Loading page',
    trash: 'Loading Trash',
  },
  rename: {
    label: 'Rename {title}',
    empty: "A name can't be empty.",
    tooLong: "A name can't be longer than {max} characters.",
    reserved: 'Windows reserves the name {name}. Try another name.',
    characters: 'A name can\'t contain \\ / : * ? " < > or |. Try another name.',
    trailingDotOrSpace: "A name can't end with a dot or a space.",
  },
  moves: {
    up: 'Moved {title} up, {position} of {count}.',
    down: 'Moved {title} down, {position} of {count}.',
    alreadyFirst: '{title} is already first.',
    alreadyLast: '{title} is already last.',
    indented: 'Made {title} a subpage.',
    promoted: 'Promoted {title}.',
    cantIndent: "{title} can't be a subpage here.",
    alreadyTop: '{title} is already a page, not a subpage.',
    moved: 'Moved "{title}" to {target}.',
    movedPages: 'Moved {count, plural, one {# page} other {# pages}} to {target}.',
    reordered: 'Moved "{title}".',
    undoHint: 'Press {shortcut} to undo.',
    dragPages: 'Move {count, plural, one {# page} other {# pages}} to {target}',
    dragItem: 'Move "{title}" to {target}',
  },
  moveTo: {
    title: 'Move "{title}" to',
    filter: 'Find a destination',
    destinations: 'Destinations',
    move: 'Move',
    noMatches: 'No destinations match.',
    none: 'There is nowhere else to move this.',
  },
  trash: {
    title: 'Trash',
    open: 'Trash',
    empty: 'Trash is empty.',
    from: 'From {parent}',
    fromLibrary: 'From your notebooks',
    deleted: 'Deleted {date} at {time}',
    pages: '{count, plural, one {# page} other {# pages}}',
    restore: 'Restore',
    restoreLabel: 'Restore {title}',
    restored: 'Restored "{title}".',
    restoreFailed: "Couldn't restore that item. Try again.",
    moved: 'Moved "{title}" to Trash.',
    movedAnnounce: 'Moved "{title}" to Trash. Press {shortcut} to undo.',
    movedAnnounceNoShortcut: 'Moved "{title}" to Trash.',
    undo: 'Undo',
    confirmTitle: 'Delete the notebook "{title}"?',
    confirmBody:
      'Its {count, plural, one {# page moves} other {# pages move}} to Trash, and you can restore them for 30 days.',
    confirm: 'Delete notebook',
  },
  undo: {
    nothing: 'Nothing to undo.',
    nothingToRedo: 'Nothing to redo.',
    created: 'Removed "{title}".',
    recreated: 'Brought back "{title}".',
    renamed: 'Changed the name back to "{title}".',
    renamedAgain: 'Changed the name to "{title}".',
    colored: 'Changed the color of "{title}" back.',
    coloredAgain: 'Changed the color of "{title}" again.',
    moved: 'Moved "{title}" back.',
    movedAgain: 'Moved "{title}" again.',
    restored: 'Restored "{title}".',
    trashedAgain: 'Moved "{title}" to Trash again.',
  },
  errors: {
    invalidMove: '"{title}" can\'t go there, so it stayed where it was.',
    readOnly: '"{title}" is read-only, so nothing changed.',
    unavailable: "The notes folder isn't available, so nothing changed. Check the drive and try again.",
    notFound: '"{title}" is gone, so nothing changed.',
    other: 'Couldn\'t change "{title}". Try again.',
  },
  page: {
    noneTitle: 'No page open',
    none: 'Choose a page to see it here.',
    empty: 'This page is empty. Writing and drawing on pages arrive in a later version.',
    changed: 'Changed {date}',
  },
  snapshot: {
    note:
      "Notes in this test build are kept in a temporary file inside the app's data folder. " +
      'Your notes folder is used once the file format arrives.',
  },
  save: {
    saved: 'Saved',
    saving: 'Saving',
    offline: 'Offline',
    error: "Couldn't save",
    errorAnnounce: "Couldn't save your notes. OpenNote keeps the changes and tries again.",
  },
  exit: {
    unsaved: "Some notes aren't saved yet. Try closing again in a moment.",
  },
  palette: {
    path: '{path}',
  },
} as const;
