// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the pen's barrel button does at contact.
 */
export type BarrelAction = "lasso" | "strokeEraser" | "partialEraser" | "lastHighlighter" | "pan" | "rightClick" | "nothing";
