// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Architecture } from "./Architecture";
import type { Channel } from "./Channel";
import type { DeviceState } from "./DeviceState";
import type { InstallStatus } from "./InstallStatus";
import type { Notice } from "./Notice";
import type { OsAppearance } from "./OsAppearance";
import type { Settings } from "./Settings";
import type { ThemeName } from "./ThemeName";
import type { UpdaterStatus } from "./UpdaterStatus";

/**
 * The boot payload, matching the interface's `BootData`.
 */
export type BootData = { bootVersion: 1, version: string, channel: Channel, architecture: Architecture, 
/**
 * `settings.json` didn't exist.
 */
firstRun: boolean, settings: Settings, 
/**
 * A newer schema's `minWriterSchema` forbids writing the settings file.
 */
settingsReadOnly: boolean, state: DeviceState, os: OsAppearance, 
/**
 * The theme Rust used for the window color.
 */
resolvedTheme: ThemeName, webview2Version: string, install: InstallStatus, updater: UpdaterStatus, 
/**
 * Feature flag overrides, in development and nightly builds only.
 */
flagOverrides: { [key in string]: boolean }, notices: Array<Notice>, perf: { processStartEpochMs: number, }, };
