// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Architecture } from './Architecture';
import type { Channel } from './Channel';
import type { DeviceState } from './DeviceState';
import type { InstallStatus } from './InstallStatus';
import type { Notice } from './Notice';
import type { OsAppearance } from './OsAppearance';
import type { Settings } from './Settings';
import type { ThemeName } from './ThemeName';
import type { UpdaterStatus } from './UpdaterStatus';

export type BootData = {
  bootVersion: 1;
  version: string;
  channel: Channel;
  architecture: Architecture;
  firstRun: boolean;
  settings: Settings;
  settingsReadOnly: boolean;
  state: DeviceState;
  os: OsAppearance;
  resolvedTheme: ThemeName;
  webview2Version: string;
  install: InstallStatus;
  updater: UpdaterStatus;
  flagOverrides: { [key in string]?: boolean };
  notices: Array<Notice>;
  perf: { processStartEpochMs: number };
};
