// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { Rect } from "./Rect";

/**
 * Where the Maximize button is, and its accessible names, matching the interface's `CaptionLayout`.
 */
export type CaptionLayout = { maximize: Rect, labels: { maximize: string, restore: string, }, };
