// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The payload of `window://caption-state`: the overlay's hover and pressed state, drawn by the HTML button.
 */
export type CaptionState = { hovered: boolean, pressed: boolean, };
