// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Ink under a Windows contrast theme: keep pen colors that stand out, or use the theme's text color.
 */
export type ContrastInk = "keepLegible" | "textColor";
