// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PanePref } from './PanePref';
import type { StoredLocation } from './StoredLocation';
import type { WindowPlacement } from './WindowPlacement';

export type DeviceState = {
  stateVersion: 1;
  window: { placement: WindowPlacement | null; maximized: boolean };
  panes: { notebooks: PanePref; pages: PanePref };
  location: StoredLocation;
  expanded: Array<string>;
  lastPageBySection: { [key in string]?: string };
  recentCommands: Array<string>;
  recentPages: Array<string>;
  setup: {
    status: 'notStarted' | 'inProgress' | 'done';
    step: string | null;
    completedSteps: Array<string>;
    draft: unknown | null;
  };
};
