// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InkDeviceState } from "./InkDeviceState";
import type { PageViewState } from "./PageViewState";
import type { PanePref } from "./PanePref";
import type { StoredLocation } from "./StoredLocation";
import type { WindowPlacement } from "./WindowPlacement";

export type DeviceState = { stateVersion: 1, window: { placement: WindowPlacement | null, maximized: boolean, }, panes: { notebooks: PanePref, pages: PanePref, }, location: StoredLocation, expanded: Array<string>, lastPageBySection: { [key in string]: string }, recentCommands: Array<string>, 
/**
 * Page ids, most recent first, so the quick switcher (Ctrl+O) lists recent pages first.
 */
recentPages: Array<string>, setup: { status: "notStarted" | "inProgress" | "done", step: string | null, completedSteps: Array<string>, draft: unknown | null, }, 
/**
 * View state per page id, the 500 most recently used.
 */
pageViews: { [key in string]: PageViewState }, ink: InkDeviceState, };
