// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { AutocorrectEntry } from "./AutocorrectEntry";
import type { FormattingBar } from "./FormattingBar";

export type EditingSettings = { markdownShortcuts: boolean, slashMenu: boolean, formattingBar: FormattingBar, autocorrect: { enabled: boolean, 
/**
 * The person's own pairs; empty means the built-in list.
 */
entries: Array<AutocorrectEntry>, }, paste: { sourceLink: "ask" | "always" | "never", saveWebImages: boolean, joinPdfLines: boolean, }, spelling: { enabled: boolean, 
/**
 * BCP 47 tags; empty means the Windows defaults.
 */
languages: Array<string>, personalWords: Array<string>, ignoreUppercase: boolean, ignoreWithDigits: boolean, }, readAloud: { 
/**
 * A voice id, or `None` for the Windows default.
 */
voice: string | null, 
/**
 * From 0.5 to 2, in steps of 0.25.
 */
rate: number, readCode: boolean, }, history: { keep: "month" | "year" | "forever", }, };
