// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * What the pen's eraser end does.
 */
export type EraserEndAction = "strokeEraser" | "partialEraser" | "highlighterEraser" | "nothing";
