// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Why the app is closing, matching the interface's `ExitReason`.
 */
export type ExitReason = "close" | "restartToUpdate" | "goBack" | "moveApp" | "sessionEnd";
