// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type ExternalTarget =
  | { kind: 'releasePage'; version: string }
  | { kind: 'newIssue'; template: 'bug' | 'rollback' }
  | { kind: 'webview2Download' }
  | { kind: 'folder'; which: 'notes' | 'logs' | 'data' | 'app' };
