// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Phase 5: when a finger draws while an ink tool is active.
 */
export type FingerDraw = "auto" | "on" | "off";
