// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type FolderCheck = { "kind": "ok" } | { "kind": "willCreate" } | { "kind": "hasLibrary", notebookCount: number, } | { "kind": "notWritable" } | { "kind": "insideAppFolder" } | { "kind": "notAbsolute" };
