// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A folded heading or list item, found again by its block, its text, and which occurrence it is.
 */
export type FoldKey = { block: string, kind: "heading" | "item", text: string, occurrence: number, };
