// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When the floating formatting bar shows.
 */
export type FormattingBar = "touchAndPen" | "always" | "never";
