// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { InkTool } from "./InkTool";
import type { PaletteState } from "./PaletteState";
import type { PenDevice } from "./PenDevice";

export type InkDeviceState = { 
/**
 * Settings per pen, by `PointerEvent.persistentDeviceId`, or `default` for pens that report none.
 */
pens: { [key in string]: PenDevice }, palette: PaletteState, lastTool: InkTool, 
/**
 * The id of the last pen slot used.
 */
lastPen: string | null, zoomBoxOpen: boolean, 
/**
 * This device's digitizer reports no hover.
 */
noHoverPen: boolean, };
