// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { ContrastInk } from "./ContrastInk";
import type { Handedness } from "./Handedness";
import type { LassoPick } from "./LassoPick";
import type { LowLatency } from "./LowLatency";
import type { PenSlot } from "./PenSlot";

export type InkSettings = { pens: Array<PenSlot>, penSelectsAndTypes: boolean, handedness: Handedness, touch: { 
/**
 * Draw with a finger when no pen is near.
 */
draws: boolean, 
/**
 * How long a touch stroke waits for a pen before it's committed, 300 to 2,000 ms.
 */
palmGraceMs: number, twoFingerScrollNearPen: boolean, }, eraser: { mode: "stroke" | "partial", 
/**
 * The partial eraser's size in millimeters: 1, 2, 4, 8, or 16.
 */
size: number, erases: "all" | "highlighter" | "pens" | "pen" | "pencil", returnToLastTool: boolean, showTarget: boolean, }, lasso: { shape: "free" | "rectangle", picks: Array<LassoPick>, inside: "mostly" | "any" | "all", }, shapes: { 
/**
 * Holding still at the end of a stroke snaps it to a shape.
 */
hold: boolean, 
/**
 * How long to hold, 300 to 1,500 ms.
 */
holdMs: number, inkToShape: boolean, }, gestures: { scribbleErase: boolean, circleSelect: boolean, twoFingerUndo: boolean, threeFingerRedo: boolean, }, anchorToText: boolean, zoomBox: { 
/**
 * 2, 3, or 4 times.
 */
magnification: number, autoAdvance: boolean, }, contrastInk: ContrastInk, lowLatency: LowLatency, };
