// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InkTool = "select" | "pen" | "pencil" | "highlighter" | "eraser" | "lasso" | "pan" | "insertSpace";
