// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type InstallStatus = { exePath: string, inUserPrograms: boolean, folderWritable: boolean, hasStartMenuShortcut: boolean, isDevBuild: boolean, };
