// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the running exe is and what the app may do there, matching the interface's `InstallStatus`.
 */
export type InstallStatus = { exePath: string, 
/**
 * The exe is in `%LOCALAPPDATA%\Programs\OpenNote\`.
 */
inUserPrograms: boolean, 
/**
 * The exe's folder is writable, so the app can update itself there.
 */
folderWritable: boolean, hasStartMenuShortcut: boolean, isDevBuild: boolean, };
