// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Serialized as `{ code, message, field? }`, matching `IpcError` in the interface's platform types.
 */
export type IpcError = { code: string, message: string, field?: string, };
