// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * OpenNote's own shortcuts, or the optional set that follows OneNote's.
 */
export type KeymapPreset = "default" | "onenote";
