// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Something the interface tells the person once at start, such as a rollback or reset settings.
 */
export type Notice = { "kind": "settingsReset", savedAs: string, } | { "kind": "settingsReadOnly" } | { "kind": "stateReset" } | { "kind": "updated", from: string, to: string, } | { "kind": "rolledBack", from: string, to: string, } | { "kind": "rollbackUnavailable", from: string, previous: string | null, } | { "kind": "moved", ok: boolean, };
