// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type OsAppearance = { dark: boolean, contrast: boolean, animations: boolean, textScale: number, zoom: number, };
