// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The Windows appearance, matching the interface's `OsAppearance`.
 */
export type OsAppearance = { 
/**
 * Windows' app mode is Dark.
 */
dark: boolean, 
/**
 * A Windows contrast theme is on.
 */
contrast: boolean, 
/**
 * Windows' "Animation effects" is on.
 */
animations: boolean, 
/**
 * Windows' text size setting, from 1.0 to 2.25.
 */
textScale: number, 
/**
 * The effective zoom Rust applied to the page (section 10.4).
 */
zoom: number, };
