// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { FoldKey } from "./FoldKey";
import type { PageViewMode } from "./PageViewMode";
import type { UiSelection } from "./UiSelection";

export type PageViewState = { scrollX: number, scrollY: number, zoom: number, 
/**
 * Canvas or Reading, or `None` for the page's own default.
 */
view: PageViewMode | null, folds: Array<FoldKey>, 
/**
 * Remembered block heights in page units, by block id.
 */
heights?: { [key in string]: number }, caret?: UiSelection, 
/**
 * When the page was last shown, in epoch milliseconds, for trimming.
 */
at: number, };
