// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PaletteDock } from "./PaletteDock";

export type PaletteState = { wide: { dock: PaletteDock, x: number, y: number, collapsed: boolean, }, compact: { dock: PaletteDock, collapsed: boolean, }, shown: boolean, 
/**
 * A pen has been seen on this device, so the palette offers pen tools.
 */
penSeen: boolean, };
