// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A pane's width in CSS pixels, and whether it's collapsed to its rail.
 */
export type PanePref = { width: number, collapsed: boolean, };
