// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { BarrelAction } from "./BarrelAction";
import type { EraserEndAction } from "./EraserEndAction";
import type { PenCurve } from "./PenCurve";

export type PenDevice = { curve: PenCurve, 
/**
 * The control points `[x1, y1, x2, y2]` of a custom curve.
 */
customCurve: [number, number, number, number] | null, 
/**
 * The thinnest a light stroke gets, as a fraction of the nominal width, 0 to 0.6.
 */
minWidth: number, 
/**
 * The steady pen's strength, 0 (off) to 10.
 */
steady: number, barrel: BarrelAction, eraserEnd: EraserEndAction, };
