// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { PenTool } from "./PenTool";

/**
 * A slot on the pen palette.
 */
export type PenSlot = { id: string, tool: PenTool, 
/**
 * A palette name, or `#rrggbb` (`#rrggbbaa` for highlighters), as in spec section 2.7.
 */
color: string, 
/**
 * The nominal width in millimeters, 0.1 to 20.
 */
width: number, 
/**
 * Whether pressure changes the width. Highlighters have none.
 */
pressure?: boolean, };
