// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A mark the interface records, matching the interface's `PerfMark`.
 */
export type PerfMark = "firstPaint" | "shellReady" | "pageReady" | "paletteOpen";
