// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A point in physical pixels, relative to the client area.
 */
export type Point = { x: number, y: number, };
