// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * When the page first painted and when the last page was ready, as epoch milliseconds.
 */
export type ReadyTimings = { firstPaintEpochMs: number, pageReadyEpochMs: number, pageId: string | null, };
