// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A top-level settings section that `settings_reset` can put back to its defaults.
 */
export type SettingsSectionKey = "appearance" | "storage" | "startup" | "shortcuts" | "keymap" | "updates" | "setup" | "experimental" | "editing" | "ink";
