// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { KeymapPresetId } from './KeymapPresetId';
import type { TextSize } from './TextSize';
import type { ThemePreference } from './ThemePreference';

export type Settings = {
  schemaVersion: number;
  minWriterSchema: number;
  appearance: {
    theme: ThemePreference;
    pageColor: 'matchTheme' | 'paper';
    textSize: TextSize;
    uiScale: number;
    motion: 'system' | 'reduce';
    density: 'auto' | 'mouse' | 'touch';
  };
  storage: { notesFolder: string | null };
  startup: { openLastPage: boolean };
  shortcuts: { [key in string]?: Array<string> };
  keyboard: { preset: KeymapPresetId };
  updates: { install: 'auto' | 'ask' | 'manual'; channel: 'stable' | 'beta'; skippedVersion: string | null };
  setup: { completedSteps: Array<string> };
  experimental: { flags: { [key in string]?: boolean } };
};
