// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { EditingSettings } from "./EditingSettings";
import type { InkSettings } from "./InkSettings";
import type { KeymapPreset } from "./KeymapPreset";
import type { TextSize } from "./TextSize";
import type { ThemePreference } from "./ThemePreference";

export type Settings = { schemaVersion: number, 
/**
 * The oldest schema version that may still write this file (section 16.6).
 */
minWriterSchema: number, appearance: { theme: ThemePreference, pageColor: "matchTheme" | "paper", 
/**
 * The whole interface's zoom, as WebView2 zoom (section 10.4).
 */
textSize: TextSize, 
/**
 * The size of sidebars, toolbars, and menus, as a percentage in [`UI_SCALE_RANGE`].
 */
uiScale: number, motion: "system" | "reduce", density: "auto" | "mouse" | "touch", }, storage: { 
/**
 * An absolute path, or `None` until setup chooses one.
 */
notesFolder: string | null, }, startup: { openLastPage: boolean, }, 
/**
 * Command id to its chords, for overridden shortcuts only. An empty list unbinds the command.
 */
shortcuts: { [key in string]: Array<string> }, keymap: { preset: KeymapPreset, }, updates: { install: "auto" | "ask" | "manual", channel: "stable" | "beta", skippedVersion: string | null, }, setup: { completedSteps: Array<string>, }, experimental: { flags: { [key in string]: boolean }, }, editing: EditingSettings, ink: InkSettings, };
