// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

export type StoredLocation =
  | { view: 'workspace'; notebookId: string | null; sectionId: string | null; pageId: string | null }
  | { view: 'settings'; section: string }
  | { view: 'setup'; step: string }
  | { view: 'trash' };
