// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A text size in percent, one of [`TEXT_SIZES`]. Anything else fails to parse, so it falls back to 100%.
 */
export type TextSize = 80 | 90 | 100 | 110 | 125 | 150 | 175 | 200;
