// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Light, Dark, or Match Windows.
 */
export type ThemePreference = "light" | "dark" | "system";
