// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * A theme as shown: the preference resolved against Windows.
 */
export type ThemeName = "light" | "dark";
