// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * Where the caret or selection was: text in a block, whole objects, or the page title.
 */
export type UiSelection = { "kind": "text", block: string, anchor: number, head: number, } | { "kind": "objects", blocks: Array<string>, } | { "kind": "title", anchor: number, head: number, };
