// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.
import type { UpdaterPhase } from './UpdaterPhase';

export type UpdaterStatus = {
  phase: UpdaterPhase;
  lastCheck: string | null;
  skippedVersion: string | null;
  previous: { version: string; available: boolean } | null;
};
