// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The updater's phase, matching the interface's `UpdaterPhase` (section 18.2).
 */
export type UpdaterPhase = { "kind": "disabled", reason: "devBuild" | "manualMode" | "notWritable" | "noKey", } | { "kind": "idle" } | { "kind": "checking" } | { "kind": "upToDate" } | { "kind": "available", version: string, notes: string, size: number, waitingForUnmetered: boolean, } | { "kind": "downloading", version: string, received: number, total: number, } | { "kind": "verifying", version: string, } | { "kind": "ready", version: string, notes: string, blockedBy: "unsavedChanges" | "recording" | null, } | { "kind": "applying", version: string, } | { "kind": "error", code: "offline" | "unreachable" | "verifyFailed" | "diskFull" | "swapFailed" | "unknown", retryAt: string | null, };
