// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * The parts of `WINDOWPLACEMENT` the app keeps, matching the interface's `WindowPlacement`.
 */
export type WindowPlacement = { 
/**
 * The `SW_*` show state, such as `SW_SHOWNORMAL` (1).
 */
showCmd: number, 
/**
 * The restored rectangle: left, top, right, and bottom, in workspace coordinates.
 */
normal: [number, number, number, number], };
