// Generated by app/scripts/build-tokens.ts from brand/tokens.json. Do not edit.

export const tokens = {
  "meta": {
    "name": "OpenNote design tokens",
    "version": "0.1.0",
    "description": "Single source of truth for OpenNote's look and motion. See BRAND.md for how each token is used. CHECKS validates contrast and motion limits."
  },
  "color": {
    "light": {
      "surface": {
        "app": "#F3EEE6",
        "page": "#FFFCF6",
        "raised": "#FFFDF9",
        "sunken": "#EAE3D8",
        "hover": "#ECE5DA",
        "selected": "#DDE8DA"
      },
      "text": {
        "primary": "#2B2521",
        "secondary": "#5C534A",
        "muted": "#6B6054",
        "onAccent": "#FFFCF6",
        "link": "#3B6A4D"
      },
      "border": {
        "subtle": "#E3DACC",
        "control": "#877B6C"
      },
      "accent": {
        "primary": "#3B6A4D",
        "primaryHover": "#325C42",
        "primaryPressed": "#2A4D38",
        "primarySubtle": "#E2ECE1",
        "clay": "#A9502F"
      },
      "status": {
        "success": "#35704A",
        "warning": "#855B0C",
        "danger": "#A8342A",
        "recording": "#A8342A"
      },
      "focus": {
        "ring": "#A9502F"
      },
      "selection": {
        "highlight": "#F4DE93"
      }
    },
    "dark": {
      "surface": {
        "app": "#1C1916",
        "page": "#24201C",
        "raised": "#2C2722",
        "sunken": "#171411",
        "hover": "#332C26",
        "selected": "#2E3B30"
      },
      "text": {
        "primary": "#F0E9DE",
        "secondary": "#CFC5B7",
        "muted": "#ABA093",
        "onAccent": "#1C1916",
        "link": "#8FC29D"
      },
      "border": {
        "subtle": "#3A322B",
        "control": "#8D8174"
      },
      "accent": {
        "primary": "#8FC29D",
        "primaryHover": "#A2CEAE",
        "primaryPressed": "#7DB28C",
        "primarySubtle": "#2E3B30",
        "clay": "#E59372"
      },
      "status": {
        "success": "#8FC29D",
        "warning": "#E7BA62",
        "danger": "#F2907F",
        "recording": "#F2907F"
      },
      "focus": {
        "ring": "#E7BA62"
      },
      "selection": {
        "highlight": "#52451F"
      }
    }
  },
  "contrast": [
    {
      "fg": "text.primary",
      "bg": "surface.page",
      "min": 7
    },
    {
      "fg": "text.primary",
      "bg": "surface.app",
      "min": 7
    },
    {
      "fg": "text.primary",
      "bg": "surface.raised",
      "min": 7
    },
    {
      "fg": "text.primary",
      "bg": "surface.sunken",
      "min": 7
    },
    {
      "fg": "text.primary",
      "bg": "surface.selected",
      "min": 7
    },
    {
      "fg": "text.primary",
      "bg": "selection.highlight",
      "min": 7
    },
    {
      "fg": "text.secondary",
      "bg": "surface.page",
      "min": 4.5
    },
    {
      "fg": "text.secondary",
      "bg": "surface.app",
      "min": 4.5
    },
    {
      "fg": "text.secondary",
      "bg": "surface.sunken",
      "min": 4.5
    },
    {
      "fg": "text.muted",
      "bg": "surface.page",
      "min": 4.5
    },
    {
      "fg": "text.muted",
      "bg": "surface.app",
      "min": 4.5
    },
    {
      "fg": "text.muted",
      "bg": "surface.raised",
      "min": 4.5
    },
    {
      "fg": "text.muted",
      "bg": "surface.sunken",
      "min": 4.5
    },
    {
      "fg": "text.link",
      "bg": "surface.page",
      "min": 4.5
    },
    {
      "fg": "text.link",
      "bg": "surface.app",
      "min": 4.5
    },
    {
      "fg": "text.onAccent",
      "bg": "accent.primary",
      "min": 4.5
    },
    {
      "fg": "text.onAccent",
      "bg": "accent.primaryHover",
      "min": 4.5
    },
    {
      "fg": "accent.clay",
      "bg": "surface.page",
      "min": 4.5
    },
    {
      "fg": "status.danger",
      "bg": "surface.page",
      "min": 4.5
    },
    {
      "fg": "status.danger",
      "bg": "surface.app",
      "min": 4.5
    },
    {
      "fg": "status.warning",
      "bg": "surface.page",
      "min": 4.5
    },
    {
      "fg": "status.warning",
      "bg": "surface.app",
      "min": 4.5
    },
    {
      "fg": "status.success",
      "bg": "surface.page",
      "min": 4.5
    },
    {
      "fg": "border.control",
      "bg": "surface.page",
      "min": 3
    },
    {
      "fg": "border.control",
      "bg": "surface.app",
      "min": 3
    },
    {
      "fg": "border.control",
      "bg": "surface.sunken",
      "min": 3
    },
    {
      "fg": "focus.ring",
      "bg": "surface.page",
      "min": 3
    },
    {
      "fg": "focus.ring",
      "bg": "surface.app",
      "min": 3
    },
    {
      "fg": "focus.ring",
      "bg": "surface.selected",
      "min": 3
    }
  ],
  "ink": {
    "pens": [
      {
        "name": "Ink",
        "light": "#2B2521",
        "dark": "#F0E9DE"
      },
      {
        "name": "Indigo",
        "light": "#2F4F9A",
        "dark": "#9DB4EA"
      },
      {
        "name": "Brick",
        "light": "#B0342A",
        "dark": "#F2907F"
      },
      {
        "name": "Fern",
        "light": "#2E7048",
        "dark": "#8FC29D"
      },
      {
        "name": "Plum",
        "light": "#6A4A9C",
        "dark": "#C2ABE8"
      },
      {
        "name": "Amber",
        "light": "#B8620F",
        "dark": "#F0AE68"
      },
      {
        "name": "Walnut",
        "light": "#6E4B2E",
        "dark": "#D6AE86"
      }
    ],
    "highlighters": [
      {
        "name": "Honey",
        "light": "#F2CF4A66",
        "dark": "#C9A42F66"
      },
      {
        "name": "Mint",
        "light": "#8ED6A566",
        "dark": "#4E9A6866"
      },
      {
        "name": "Rose",
        "light": "#F0A0B866",
        "dark": "#B8627B66"
      },
      {
        "name": "Apricot",
        "light": "#F5B77A66",
        "dark": "#B8793D66"
      },
      {
        "name": "Lilac",
        "light": "#C6B2F066",
        "dark": "#7C66B066"
      }
    ]
  },
  "font": {
    "ui": "\"Atkinson Hyperlegible Next Variable\", \"Atkinson Hyperlegible Next\", \"Segoe UI Variable Text\", \"Segoe UI\", system-ui, sans-serif",
    "reading": "\"Literata Variable\", \"Literata\", \"Cambria\", Georgia, serif",
    "mono": "\"Atkinson Hyperlegible Mono\", \"Cascadia Code\", Consolas, monospace",
    "weight": {
      "regular": 400,
      "medium": 500,
      "semibold": 600,
      "bold": 700
    }
  },
  "type": {
    "caption": {
      "size": 12,
      "lineHeight": 16
    },
    "small": {
      "size": 13,
      "lineHeight": 18
    },
    "body": {
      "size": 15,
      "lineHeight": 22
    },
    "note": {
      "size": 16,
      "lineHeight": 26
    },
    "subtitle": {
      "size": 17,
      "lineHeight": 24
    },
    "title3": {
      "size": 20,
      "lineHeight": 28
    },
    "title2": {
      "size": 24,
      "lineHeight": 32
    },
    "title1": {
      "size": 30,
      "lineHeight": 38
    },
    "display": {
      "size": 36,
      "lineHeight": 44
    }
  },
  "space": {
    "0": 0,
    "1": 2,
    "2": 4,
    "3": 8,
    "4": 12,
    "5": 16,
    "6": 20,
    "7": 24,
    "8": 32,
    "9": 40,
    "10": 48,
    "11": 64
  },
  "radius": {
    "sm": 4,
    "md": 8,
    "lg": 12,
    "xl": 16,
    "pill": 999
  },
  "size": {
    "targetMin": 24,
    "targetPointer": 32,
    "targetTouch": 44,
    "iconSm": 16,
    "iconMd": 20,
    "iconLg": 24,
    "toolbarPointer": 44,
    "toolbarTouch": 56,
    "sidebar": 272,
    "pageList": 300,
    "editorMin": 480,
    "readingMeasure": "72ch",
    "focusRingWidth": 2,
    "focusRingOffset": 2,
    "titleBar": 40,
    "titleBarTouch": 48,
    "captionButton": 46,
    "dragMin": 200,
    "rail": 48,
    "sidebarMin": 220,
    "sidebarMax": 400,
    "pageListMin": 240,
    "pageListMax": 420,
    "splitterHit": 8,
    "splitterHitTouch": 24,
    "treeIndent": 16,
    "rowPointer": 32,
    "rowTouch": 44,
    "pageRow": 56,
    "autoScrollStrip": 28,
    "palette": 680,
    "paletteTop": 90,
    "setupCardWidth": 720,
    "setupCardHeight": 600,
    "settingsNav": 240,
    "bottomBar": 64,
    "menuMinWidth": 208,
    "dialogWidth": 440,
    "toastMaxWidth": 480,
    "contentMin": 320,
    "windowMin": 400
  },
  "breakpoint": {
    "medium": 600,
    "expanded": 840,
    "wide": 1200
  },
  "elevation": {
    "1": "0 1px 2px rgba(43, 37, 33, 0.08)",
    "2": "0 4px 12px rgba(43, 37, 33, 0.10)",
    "3": "0 12px 32px rgba(43, 37, 33, 0.14)"
  },
  "layer": {
    "base": 0,
    "sticky": 10,
    "dropdown": 20,
    "overlay": 30,
    "dialog": 40,
    "toast": 50,
    "tooltip": 60
  },
  "motion": {
    "duration": {
      "instant": 0,
      "quick": 100,
      "fast": 150,
      "base": 200,
      "gentle": 250,
      "slow": 320,
      "deliberate": 400
    },
    "easing": {
      "standard": "cubic-bezier(0.2, 0, 0, 1)",
      "enter": "cubic-bezier(0, 0, 0.2, 1)",
      "exit": "cubic-bezier(0.4, 0, 1, 1)",
      "linear": "linear"
    },
    "spring": {
      "stiffness": 420,
      "damping": 42,
      "mass": 1
    },
    "reducedDuration": 100
  },
  "interaction": {
    "longPressMs": 500,
    "typeaheadMs": 700,
    "tooltipDelayMs": 500,
    "loadingDelayMs": 300,
    "toastMs": 6000,
    "themeApplyMinMs": 350,
    "pageOpenDebounceMs": 100
  }
} as const;
