// Generated by app/scripts/build-tokens.ts from brand/tokens.json. Do not edit.

//! Theme colors for Rust, which paints the window before the page loads, colors the frame border, and colors
//! the native title bar if the custom one is ever turned off.

/// A color in the sRGB space, one byte per channel.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct Rgb(pub u8, pub u8, pub u8);

/// A color token's value in the light and dark themes.
#[derive(Debug, Clone, Copy, PartialEq, Eq)]
pub struct ThemePair {
    pub light: Rgb,
    pub dark: Rgb,
}

/// `color.surface.app` in both themes.
pub const SURFACE_APP: ThemePair = ThemePair {
    light: Rgb(0xF3, 0xEE, 0xE6),
    dark: Rgb(0x1C, 0x19, 0x16),
};

/// `color.border.subtle` in both themes.
pub const BORDER_SUBTLE: ThemePair = ThemePair {
    light: Rgb(0xE3, 0xDA, 0xCC),
    dark: Rgb(0x3A, 0x32, 0x2B),
};

/// `color.text.primary` in both themes.
pub const TEXT_PRIMARY: ThemePair = ThemePair {
    light: Rgb(0x2B, 0x25, 0x21),
    dark: Rgb(0xF0, 0xE9, 0xDE),
};
