// @vitest-environment node
import { describe, expect, it } from 'vitest';
import { buildRust, rustConstName, rustRgb, type Tokens } from './build-tokens.ts';

const color: Tokens['color'] = {
  light: { surface: { app: '#F3EEE6' }, border: { subtle: '#e3dacc' } },
  dark: { surface: { app: '#1C1916' }, border: { subtle: '#3A322B' } },
};

describe('rustConstName', () => {
  it('turns token paths into constant names', () => {
    expect(rustConstName('surface.app')).toBe('SURFACE_APP');
    expect(rustConstName('caption.closeHover')).toBe('CAPTION_CLOSE_HOVER');
  });
});

describe('rustRgb', () => {
  it('writes each channel as an uppercase hex byte', () => {
    expect(rustRgb('#1c1916', 'x')).toBe('Rgb(0x1C, 0x19, 0x16)');
  });

  it('rejects colors the window background cannot use', () => {
    expect(() => rustRgb('#2B252147', 'color.light.surface.scrim')).toThrow(/color\.light\.surface\.scrim/);
    expect(() => rustRgb('#FFF', 'x')).toThrow(/six-digit/);
  });
});

describe('buildRust', () => {
  it('writes both themes of each window color', () => {
    const rust = buildRust({ color });
    expect(rust).toContain(
      [
        'pub const SURFACE_APP: ThemePair = ThemePair {',
        '    light: Rgb(0xF3, 0xEE, 0xE6),',
        '    dark: Rgb(0x1C, 0x19, 0x16),',
        '};',
      ].join('\n'),
    );
    expect(rust).toContain('pub const BORDER_SUBTLE: ThemePair = ThemePair {\n    light: Rgb(0xE3, 0xDA, 0xCC),');
    expect(rust.startsWith('// Generated by app/scripts/build-tokens.ts')).toBe(true);
    expect(rust.endsWith('};\n')).toBe(true);
  });

  it('names the token when one is missing', () => {
    const missing = { light: { surface: {} }, dark: color.dark };
    expect(() => buildRust({ color: missing })).toThrow(/color\.light\.surface\.app/);
  });
});
