// Generates app/src/theme/tokens.css and tokens.ts, and the window colors in app/src-tauri/src/theme_tokens.rs,
// from brand/tokens.json (ARCHITECTURE.md section 9.1).
// Run with: npm run tokens     Check that the generated files are current: npm run tokens:check

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..', '..');
const THEME_DIR = join(ROOT, 'app', 'src', 'theme');
const RUST_TOKENS = join(ROOT, 'app', 'src-tauri', 'src', 'theme_tokens.rs');
const HEADER = 'Generated by app/scripts/build-tokens.ts from brand/tokens.json. Do not edit.';

/**
 * The colors Rust needs, as paths inside color.light and color.dark. They are the window background before the
 * page loads (surface.app), the frame border (border.subtle), and the native title bar fallback's text.
 */
const RUST_COLORS = ['surface.app', 'border.subtle', 'text.primary'];

/** How close to rest the spring must be, as a fraction of its travel, to count as settled. */
const SPRING_REST = 0.005;
/** Points in the sampled spring curve, including both ends. */
const SPRING_SAMPLES = 24;
/** BRAND.md section 9: nothing moves for longer. */
const MAX_MOTION_MS = 400;

/**
 * Where the light theme applies inside the page: theme preview cards, and the page region when "Always paper
 * white" is on (data-page-color="paper").
 */
const LIGHT_SCOPES = ['[data-theme-scope="light"]', ':root[data-page-color="paper"] [data-region="page"]'];
const DARK_SCOPES = ['[data-theme-scope="dark"]'];
/** Matches the root with every theme selector above, so the forced colors win without !important. */
const FORCED_ROOT = [':root', ':root[data-theme]', ':root:not([data-theme="light"])'];

type Tree = { [key: string]: string | number | Tree };

export interface InkColor {
  name: string;
  light: string;
  dark: string;
}

export interface Tokens {
  color: { light: Tree; dark: Tree };
  forcedColors?: Record<string, string>;
  font: Tree;
  type: Record<string, { size: number; lineHeight: number }>;
  space: Record<string, number>;
  radius: Record<string, number>;
  size: Record<string, number | string>;
  breakpoint: Record<string, number>;
  elevation: Record<string, string>;
  layer: Record<string, number>;
  motion: {
    duration: Record<string, number>;
    easing: Record<string, string>;
    spring?: { stiffness: number; damping: number; mass: number };
    reducedDuration: number;
  };
  ink: { pens?: InkColor[]; highlighters?: InkColor[] };
}

const kebab = (text: string) => text.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/** Flattens nested tokens into CSS custom properties, e.g. color.surface.page → --color-surface-page. */
function variables(prefix: string, tree: Tree, unit = ''): string[] {
  return Object.entries(tree).flatMap(([key, value]) => {
    const name = `${prefix}-${kebab(key)}`;
    if (typeof value === 'object') return variables(name, value, unit);
    const withUnit = typeof value === 'number' && unit ? `${value}${unit}` : String(value);
    return [`  ${name}: ${withUnit};`];
  });
}

function typeScale(type: Tokens['type']): string[] {
  return Object.entries(type).flatMap(([name, t]) => [
    `  --type-${kebab(name)}-size: ${t.size}px;`,
    `  --type-${kebab(name)}-line: ${t.lineHeight}px;`,
  ]);
}

function sizes(size: Tokens['size']): string[] {
  return Object.entries(size).map(([key, value]) => {
    const css = typeof value === 'number' ? `${value}px` : value;
    return `  --size-${kebab(key)}: ${css};`;
  });
}

/** Each pen as --ink-<name>, for notebook and section color chips (ARCHITECTURE.md section 13.7). */
function pens(tokens: Pick<Tokens, 'ink'>, theme: 'light' | 'dark'): string[] {
  return (tokens.ink.pens ?? []).map(
    (pen) => `  --ink-${kebab(pen.name.charAt(0).toLowerCase() + pen.name.slice(1))}: ${pen[theme]};`,
  );
}

/** A theme's colors and pens, which the root, the scoped blocks, and the fallback all repeat. */
function themeColors(tokens: Tokens, theme: 'light' | 'dark'): string[] {
  return [`  color-scheme: ${theme};`, ...variables('--color', tokens.color[theme]), ...pens(tokens, theme)];
}

/**
 * The spring as a CSS linear() easing, sampled from rest to rest, and the time it takes to settle: after it, the
 * position stays within SPRING_REST of the target. It steps a damped mass on a spring every 0.1 ms for 2 s, which
 * works for any damping ratio.
 */
export function springEasing(spring: { stiffness: number; damping: number; mass: number }): {
  easing: string;
  ms: number;
} {
  const dt = 0.0001;
  const all: number[] = [0];
  let [x, v] = [0, 0];
  for (let step = 0; step < 20_000; step += 1) {
    v += ((-spring.stiffness * (x - 1) - spring.damping * v) / spring.mass) * dt;
    x += v * dt;
    all.push(x);
  }
  const unsettled = all.findLastIndex((position) => Math.abs(1 - position) >= SPRING_REST);
  const positions = all.slice(0, unsettled + 2);
  const ms = Math.ceil(((positions.length - 1) * dt * 1000) / 5) * 5;
  if (ms > MAX_MOTION_MS) throw new Error(`motion.spring settles in ${ms} ms; BRAND.md allows ${MAX_MOTION_MS}.`);
  const points = Array.from({ length: SPRING_SAMPLES }, (_, i) => {
    if (i === SPRING_SAMPLES - 1) return 1;
    const value = positions[Math.round((i / (SPRING_SAMPLES - 1)) * (positions.length - 1))];
    return Math.round(value * 1000) / 1000;
  });
  return { easing: `linear(${points.join(', ')})`, ms };
}

/** Every duration, including the spring's settle time. */
function durations(motion: Tokens['motion']): Record<string, number> {
  return motion.spring ? { ...motion.duration, spring: springEasing(motion.spring).ms } : motion.duration;
}

function easings(motion: Tokens['motion']): Record<string, string> {
  return motion.spring ? { ...motion.easing, spring: springEasing(motion.spring).easing } : motion.easing;
}

function reducedMotion(motion: Tokens['motion']): string[] {
  return Object.entries(durations(motion)).map(([key, ms]) => {
    const reduced = Math.min(ms, motion.reducedDuration);
    return `  --motion-duration-${kebab(key)}: ${reduced}ms;`;
  });
}

function rootBlock(tokens: Tokens): string[] {
  const fontWeights = tokens.font.weight as Tree;
  const fonts = Object.fromEntries(Object.entries(tokens.font).filter(([key]) => key !== 'weight')) as Tree;
  return [
    ...themeColors(tokens, 'light'),
    ...variables('--font', fonts),
    ...variables('--font-weight', fontWeights),
    ...typeScale(tokens.type),
    ...variables('--space', tokens.space, 'px'),
    ...variables('--radius', tokens.radius, 'px'),
    ...sizes(tokens.size),
    ...variables('--breakpoint', tokens.breakpoint, 'px'),
    ...variables('--elevation', tokens.elevation),
    ...variables('--layer', tokens.layer),
    ...variables('--motion-duration', durations(tokens.motion), 'ms'),
    ...variables('--motion-easing', easings(tokens.motion)),
  ];
}

const block = (selectors: readonly string[], lines: string[], indent = '') => [
  `${indent}${selectors.join(`,\n${indent}`)} {`,
  ...lines.map((line) => `${indent}${line}`),
  `${indent}}`,
  '',
];

/** Windows contrast themes: each mapped token becomes its CSS system color (ARCHITECTURE.md section 9.6). */
function forcedColors(tokens: Tokens): string[] {
  const lines = Object.entries(tokens.forcedColors ?? {}).map(
    ([path, keyword]) => `  --color-${path.split('.').map(kebab).join('-')}: ${keyword};`,
  );
  return lines.length
    ? ['@media (forced-colors: active) {', ...block(FORCED_ROOT, lines, '  ').slice(0, -1), '}', '']
    : [];
}

export function buildCss(tokens: Tokens): string {
  const dark = themeColors(tokens, 'dark');
  return [
    `/* ${HEADER} */`,
    '',
    ...block([':root'], rootBlock(tokens)),
    ...block([':root[data-theme="dark"]'], dark),
    '/* Before scripts run in a plain browser, the system setting decides. The app always sets data-theme. */',
    '@media (prefers-color-scheme: dark) {',
    ...block([':root:not([data-theme="light"])'], dark, '  ').slice(0, -1),
    '}',
    '',
    '/* Theme preview cards, and paper-white pages inside the dark theme. */',
    ...block(LIGHT_SCOPES, themeColors(tokens, 'light')),
    ...block(DARK_SCOPES, dark),
    '@media (prefers-reduced-motion: reduce) {',
    ...block([':root'], reducedMotion(tokens.motion), '  ').slice(0, -1),
    '}',
    '',
    '/* The in-app "Always reduce motion" setting. */',
    ...block([':root[data-motion="reduce"]'], reducedMotion(tokens.motion)),
    ...forcedColors(tokens),
  ].join('\n');
}

export function buildTs(tokens: Tokens): string {
  return [`// ${HEADER}`, '', `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;`, ''].join('\n');
}

/** A Rust constant name for a token path, e.g. caption.closeHover → CAPTION_CLOSE_HOVER. */
export function rustConstName(path: string): string {
  return path
    .replace(/[A-Z]/g, (c) => `_${c}`)
    .replace(/\./g, '_')
    .toUpperCase();
}

/** A six-digit hex color as a Rust `Rgb` value. The window has no alpha channel, so other forms are an error. */
export function rustRgb(hex: string, path: string): string {
  const match = /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex);
  if (!match) throw new Error(`${path} must be a six-digit hex color for Rust, not ${hex}.`);
  return `Rgb(${match
    .slice(1)
    .map((pair) => `0x${pair.toUpperCase()}`)
    .join(', ')})`;
}

function colorAt(tree: Tree, theme: string, path: string): string {
  const value = path.split('.').reduce<Tree | string | number | undefined>((node, key) => {
    return typeof node === 'object' ? node[key] : undefined;
  }, tree);
  if (typeof value !== 'string') throw new Error(`color.${theme}.${path} is missing or isn't a color.`);
  return rustRgb(value, `color.${theme}.${path}`);
}

/** The window colors as Rust constants, formatted the way rustfmt formats them. */
export function buildRust(tokens: Pick<Tokens, 'color'>, paths: readonly string[] = RUST_COLORS): string {
  const constants = paths.flatMap((path) => [
    '',
    `/// \`color.${path}\` in both themes.`,
    `pub const ${rustConstName(path)}: ThemePair = ThemePair {`,
    `    light: ${colorAt(tokens.color.light, 'light', path)},`,
    `    dark: ${colorAt(tokens.color.dark, 'dark', path)},`,
    '};',
  ]);
  return [
    `// ${HEADER}`,
    '',
    '//! Theme colors for Rust, which paints the window before the page loads, colors the frame border, and colors',
    '//! the native title bar if the custom one is ever turned off.',
    '',
    '/// A color in the sRGB space, one byte per channel.',
    '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
    'pub struct Rgb(pub u8, pub u8, pub u8);',
    '',
    "/// A color token's value in the light and dark themes.",
    '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
    'pub struct ThemePair {',
    '    pub light: Rgb,',
    '    pub dark: Rgb,',
    '}',
    ...constants,
    '',
  ].join('\n');
}

function main(): void {
  const tokens = JSON.parse(readFileSync(join(ROOT, 'brand', 'tokens.json'), 'utf8')) as Tokens;
  const outputs: [string, string][] = [
    [join(THEME_DIR, 'tokens.css'), buildCss(tokens)],
    [join(THEME_DIR, 'tokens.ts'), buildTs(tokens)],
    [RUST_TOKENS, buildRust(tokens)],
  ];
  const check = process.argv.includes('--check');
  const stale = outputs.filter(([path, content]) => {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      // Missing counts as stale.
    }
    return current !== content;
  });
  if (check) {
    stale.forEach(([path]) => console.error(`Out of date: ${path}. Run npm run tokens.`));
    process.exitCode = stale.length > 0 ? 1 : 0;
    return;
  }
  outputs.forEach(([path, content]) => writeFileSync(path, content));
  console.log(`Wrote ${outputs.length} theme files.`);
}

// Runs only as a script, so tests can import the builders.
if (import.meta.main) main();
