// Generates app/src/theme/tokens.css and tokens.ts from brand/tokens.json.
// Run with: npm run tokens     Check that the generated files are current: npm run tokens:check

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..', '..');
const THEME_DIR = join(ROOT, 'app', 'src', 'theme');
const HEADER = 'Generated by app/scripts/build-tokens.ts from brand/tokens.json. Do not edit.';

type Tree = { [key: string]: string | number | Tree };

interface Tokens {
  color: { light: Tree; dark: Tree };
  font: Tree;
  type: Record<string, { size: number; lineHeight: number }>;
  space: Record<string, number>;
  radius: Record<string, number>;
  size: Record<string, number | string>;
  breakpoint: Record<string, number>;
  elevation: Record<string, string>;
  layer: Record<string, number>;
  motion: { duration: Record<string, number>; easing: Record<string, string>; reducedDuration: number };
  ink: unknown;
}

const kebab = (text: string) => text.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/** Flattens nested tokens into CSS custom properties, e.g. color.surface.page → --color-surface-page. */
function variables(prefix: string, tree: Tree, unit = ''): string[] {
  return Object.entries(tree).flatMap(([key, value]) => {
    const name = `${prefix}-${kebab(key)}`;
    if (typeof value === 'object') return variables(name, value, unit);
    const withUnit = typeof value === 'number' && unit ? `${value}${unit}` : String(value);
    return [`  ${name}: ${withUnit};`];
  });
}

function typeScale(type: Tokens['type']): string[] {
  return Object.entries(type).flatMap(([name, t]) => [
    `  --type-${kebab(name)}-size: ${t.size}px;`,
    `  --type-${kebab(name)}-line: ${t.lineHeight}px;`,
  ]);
}

function sizes(size: Tokens['size']): string[] {
  return Object.entries(size).map(([key, value]) => {
    const css = typeof value === 'number' ? `${value}px` : value;
    return `  --size-${kebab(key)}: ${css};`;
  });
}

function reducedMotion(motion: Tokens['motion']): string[] {
  return Object.entries(motion.duration).map(([key, ms]) => {
    const reduced = Math.min(ms, motion.reducedDuration);
    return `    --motion-duration-${kebab(key)}: ${reduced}ms;`;
  });
}

export function buildCss(tokens: Tokens): string {
  const fontWeights = tokens.font.weight as Tree;
  const fonts = Object.fromEntries(Object.entries(tokens.font).filter(([key]) => key !== 'weight')) as Tree;
  const root = [
    ...variables('--color', tokens.color.light),
    ...variables('--font', fonts),
    ...variables('--font-weight', fontWeights),
    ...typeScale(tokens.type),
    ...variables('--space', tokens.space, 'px'),
    ...variables('--radius', tokens.radius, 'px'),
    ...sizes(tokens.size),
    ...variables('--breakpoint', tokens.breakpoint, 'px'),
    ...variables('--elevation', tokens.elevation),
    ...variables('--layer', tokens.layer),
    ...variables('--motion-duration', tokens.motion.duration, 'ms'),
    ...variables('--motion-easing', tokens.motion.easing),
  ];
  const dark = variables('--color', tokens.color.dark);
  return [
    `/* ${HEADER} */`,
    '',
    ':root {',
    '  color-scheme: light;',
    ...root,
    '}',
    '',
    ':root[data-theme="dark"] {',
    '  color-scheme: dark;',
    ...dark,
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    '  :root:not([data-theme="light"]) {',
    '    color-scheme: dark;',
    ...dark.map((line) => `  ${line}`),
    '  }',
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    ...reducedMotion(tokens.motion),
    '  }',
    '}',
    '',
  ].join('\n');
}

export function buildTs(tokens: Tokens): string {
  return [`// ${HEADER}`, '', `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;`, ''].join('\n');
}

function main(): void {
  const tokens = JSON.parse(readFileSync(join(ROOT, 'brand', 'tokens.json'), 'utf8')) as Tokens;
  const outputs: [string, string][] = [
    [join(THEME_DIR, 'tokens.css'), buildCss(tokens)],
    [join(THEME_DIR, 'tokens.ts'), buildTs(tokens)],
  ];
  const check = process.argv.includes('--check');
  const stale = outputs.filter(([path, content]) => {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      // Missing counts as stale.
    }
    return current !== content;
  });
  if (check) {
    stale.forEach(([path]) => console.error(`Out of date: ${path}. Run npm run tokens.`));
    process.exitCode = stale.length > 0 ? 1 : 0;
    return;
  }
  outputs.forEach(([path, content]) => writeFileSync(path, content));
  console.log(`Wrote ${outputs.length} theme files.`);
}

main();
