// Generates app/src/theme/tokens.css and tokens.ts, and the window colors in app/src-tauri/src/theme_tokens.rs,
// from brand/tokens.json.
// Run with: npm run tokens     Check that the generated files are current: npm run tokens:check

import { readFileSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

const ROOT = join(import.meta.dirname, '..', '..');
const THEME_DIR = join(ROOT, 'app', 'src', 'theme');
const RUST_TOKENS = join(ROOT, 'app', 'src-tauri', 'src', 'theme_tokens.rs');
const HEADER = 'Generated by app/scripts/build-tokens.ts from brand/tokens.json. Do not edit.';

/**
 * The colors Rust needs before the page loads, as paths inside color.light and color.dark: the window background
 * (surface.app) and the frame border (border.subtle).
 */
const RUST_COLORS = ['surface.app', 'border.subtle'];

type Tree = { [key: string]: string | number | Tree };

export interface Tokens {
  color: { light: Tree; dark: Tree };
  font: Tree;
  type: Record<string, { size: number; lineHeight: number }>;
  space: Record<string, number>;
  radius: Record<string, number>;
  size: Record<string, number | string>;
  breakpoint: Record<string, number>;
  elevation: Record<string, string>;
  layer: Record<string, number>;
  motion: { duration: Record<string, number>; easing: Record<string, string>; reducedDuration: number };
  ink: unknown;
}

const kebab = (text: string) => text.replace(/[A-Z]/g, (c) => `-${c.toLowerCase()}`);

/** Flattens nested tokens into CSS custom properties, e.g. color.surface.page → --color-surface-page. */
function variables(prefix: string, tree: Tree, unit = ''): string[] {
  return Object.entries(tree).flatMap(([key, value]) => {
    const name = `${prefix}-${kebab(key)}`;
    if (typeof value === 'object') return variables(name, value, unit);
    const withUnit = typeof value === 'number' && unit ? `${value}${unit}` : String(value);
    return [`  ${name}: ${withUnit};`];
  });
}

function typeScale(type: Tokens['type']): string[] {
  return Object.entries(type).flatMap(([name, t]) => [
    `  --type-${kebab(name)}-size: ${t.size}px;`,
    `  --type-${kebab(name)}-line: ${t.lineHeight}px;`,
  ]);
}

function sizes(size: Tokens['size']): string[] {
  return Object.entries(size).map(([key, value]) => {
    const css = typeof value === 'number' ? `${value}px` : value;
    return `  --size-${kebab(key)}: ${css};`;
  });
}

function reducedMotion(motion: Tokens['motion']): string[] {
  return Object.entries(motion.duration).map(([key, ms]) => {
    const reduced = Math.min(ms, motion.reducedDuration);
    return `    --motion-duration-${kebab(key)}: ${reduced}ms;`;
  });
}

export function buildCss(tokens: Tokens): string {
  const fontWeights = tokens.font.weight as Tree;
  const fonts = Object.fromEntries(Object.entries(tokens.font).filter(([key]) => key !== 'weight')) as Tree;
  const root = [
    ...variables('--color', tokens.color.light),
    ...variables('--font', fonts),
    ...variables('--font-weight', fontWeights),
    ...typeScale(tokens.type),
    ...variables('--space', tokens.space, 'px'),
    ...variables('--radius', tokens.radius, 'px'),
    ...sizes(tokens.size),
    ...variables('--breakpoint', tokens.breakpoint, 'px'),
    ...variables('--elevation', tokens.elevation),
    ...variables('--layer', tokens.layer),
    ...variables('--motion-duration', tokens.motion.duration, 'ms'),
    ...variables('--motion-easing', tokens.motion.easing),
  ];
  const dark = variables('--color', tokens.color.dark);
  return [
    `/* ${HEADER} */`,
    '',
    ':root {',
    '  color-scheme: light;',
    ...root,
    '}',
    '',
    ':root[data-theme="dark"] {',
    '  color-scheme: dark;',
    ...dark,
    '}',
    '',
    '@media (prefers-color-scheme: dark) {',
    '  :root:not([data-theme="light"]) {',
    '    color-scheme: dark;',
    ...dark.map((line) => `  ${line}`),
    '  }',
    '}',
    '',
    '@media (prefers-reduced-motion: reduce) {',
    '  :root {',
    ...reducedMotion(tokens.motion),
    '  }',
    '}',
    '',
  ].join('\n');
}

export function buildTs(tokens: Tokens): string {
  return [`// ${HEADER}`, '', `export const tokens = ${JSON.stringify(tokens, null, 2)} as const;`, ''].join('\n');
}

/** A Rust constant name for a token path, e.g. caption.closeHover → CAPTION_CLOSE_HOVER. */
export function rustConstName(path: string): string {
  return path
    .replace(/[A-Z]/g, (c) => `_${c}`)
    .replace(/\./g, '_')
    .toUpperCase();
}

/** A six-digit hex color as a Rust `Rgb` value. The window has no alpha channel, so other forms are an error. */
export function rustRgb(hex: string, path: string): string {
  const match = /^#([0-9a-f]{2})([0-9a-f]{2})([0-9a-f]{2})$/i.exec(hex);
  if (!match) throw new Error(`${path} must be a six-digit hex color for Rust, not ${hex}.`);
  return `Rgb(${match
    .slice(1)
    .map((pair) => `0x${pair.toUpperCase()}`)
    .join(', ')})`;
}

function colorAt(tree: Tree, theme: string, path: string): string {
  const value = path.split('.').reduce<Tree | string | number | undefined>((node, key) => {
    return typeof node === 'object' ? node[key] : undefined;
  }, tree);
  if (typeof value !== 'string') throw new Error(`color.${theme}.${path} is missing or isn't a color.`);
  return rustRgb(value, `color.${theme}.${path}`);
}

/** The window colors as Rust constants, formatted the way rustfmt formats them. */
export function buildRust(tokens: Pick<Tokens, 'color'>): string {
  const constants = RUST_COLORS.flatMap((path) => [
    '',
    `/// \`color.${path}\` in both themes.`,
    `pub const ${rustConstName(path)}: ThemePair = ThemePair {`,
    `    light: ${colorAt(tokens.color.light, 'light', path)},`,
    `    dark: ${colorAt(tokens.color.dark, 'dark', path)},`,
    '};',
  ]);
  return [
    `// ${HEADER}`,
    '',
    '//! Theme colors for Rust, which paints the window before the page loads and colors the frame border.',
    '',
    '/// A color in the sRGB space, one byte per channel.',
    '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
    'pub struct Rgb(pub u8, pub u8, pub u8);',
    '',
    "/// A color token's value in the light and dark themes.",
    '#[derive(Debug, Clone, Copy, PartialEq, Eq)]',
    'pub struct ThemePair {',
    '    pub light: Rgb,',
    '    pub dark: Rgb,',
    '}',
    ...constants,
    '',
  ].join('\n');
}

function main(): void {
  const tokens = JSON.parse(readFileSync(join(ROOT, 'brand', 'tokens.json'), 'utf8')) as Tokens;
  const outputs: [string, string][] = [
    [join(THEME_DIR, 'tokens.css'), buildCss(tokens)],
    [join(THEME_DIR, 'tokens.ts'), buildTs(tokens)],
    [RUST_TOKENS, buildRust(tokens)],
  ];
  const check = process.argv.includes('--check');
  const stale = outputs.filter(([path, content]) => {
    let current = '';
    try {
      current = readFileSync(path, 'utf8');
    } catch {
      // Missing counts as stale.
    }
    return current !== content;
  });
  if (check) {
    stale.forEach(([path]) => console.error(`Out of date: ${path}. Run npm run tokens.`));
    process.exitCode = stale.length > 0 ? 1 : 0;
    return;
  }
  outputs.forEach(([path, content]) => writeFileSync(path, content));
  console.log(`Wrote ${outputs.length} theme files.`);
}

// Runs only as a script, so tests can import the builders.
if (import.meta.main) main();
